// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminAddPlayerPreviousNameHandler(ReducerEventContext ctx, string identity, string name);
        public event AdminAddPlayerPreviousNameHandler? OnAdminAddPlayerPreviousName;

        public void AdminAddPlayerPreviousName(string identity, string name)
        {
            conn.InternalCallReducer(new Reducer.AdminAddPlayerPreviousName(identity, name), this.SetCallReducerFlags.AdminAddPlayerPreviousNameFlags);
        }

        public bool InvokeAdminAddPlayerPreviousName(ReducerEventContext ctx, Reducer.AdminAddPlayerPreviousName args)
        {
            if (OnAdminAddPlayerPreviousName == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminAddPlayerPreviousName(
                ctx,
                args.Identity,
                args.Name
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminAddPlayerPreviousName : Reducer, IReducerArgs
        {
            [DataMember(Name = "identity")]
            public string Identity;
            [DataMember(Name = "name")]
            public string Name;

            public AdminAddPlayerPreviousName(
                string Identity,
                string Name
            )
            {
                this.Identity = Identity;
                this.Name = Name;
            }

            public AdminAddPlayerPreviousName()
            {
                this.Identity = "";
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "admin_add_player_previous_name";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminAddPlayerPreviousNameFlags;
        public void AdminAddPlayerPreviousName(CallReducerFlags flags) => AdminAddPlayerPreviousNameFlags = flags;
    }
}
