// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminMarkPremiumPurchaseProcessedHandler(ReducerEventContext ctx, ulong entityId);
        public event AdminMarkPremiumPurchaseProcessedHandler? OnAdminMarkPremiumPurchaseProcessed;

        public void AdminMarkPremiumPurchaseProcessed(ulong entityId)
        {
            conn.InternalCallReducer(new Reducer.AdminMarkPremiumPurchaseProcessed(entityId), this.SetCallReducerFlags.AdminMarkPremiumPurchaseProcessedFlags);
        }

        public bool InvokeAdminMarkPremiumPurchaseProcessed(ReducerEventContext ctx, Reducer.AdminMarkPremiumPurchaseProcessed args)
        {
            if (OnAdminMarkPremiumPurchaseProcessed == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminMarkPremiumPurchaseProcessed(
                ctx,
                args.EntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminMarkPremiumPurchaseProcessed : Reducer, IReducerArgs
        {
            [DataMember(Name = "entity_id")]
            public ulong EntityId;

            public AdminMarkPremiumPurchaseProcessed(ulong EntityId)
            {
                this.EntityId = EntityId;
            }

            public AdminMarkPremiumPurchaseProcessed()
            {
            }

            string IReducerArgs.ReducerName => "admin_mark_premium_purchase_processed";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminMarkPremiumPurchaseProcessedFlags;
        public void AdminMarkPremiumPurchaseProcessed(CallReducerFlags flags) => AdminMarkPremiumPurchaseProcessedFlags = flags;
    }
}
