// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminGrantShardsHandler(ReducerEventContext ctx, string identity, int amount);
        public event AdminGrantShardsHandler? OnAdminGrantShards;

        public void AdminGrantShards(string identity, int amount)
        {
            conn.InternalCallReducer(new Reducer.AdminGrantShards(identity, amount), this.SetCallReducerFlags.AdminGrantShardsFlags);
        }

        public bool InvokeAdminGrantShards(ReducerEventContext ctx, Reducer.AdminGrantShards args)
        {
            if (OnAdminGrantShards == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminGrantShards(
                ctx,
                args.Identity,
                args.Amount
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminGrantShards : Reducer, IReducerArgs
        {
            [DataMember(Name = "identity")]
            public string Identity;
            [DataMember(Name = "amount")]
            public int Amount;

            public AdminGrantShards(
                string Identity,
                int Amount
            )
            {
                this.Identity = Identity;
                this.Amount = Amount;
            }

            public AdminGrantShards()
            {
                this.Identity = "";
            }

            string IReducerArgs.ReducerName => "admin_grant_shards";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminGrantShardsFlags;
        public void AdminGrantShards(CallReducerFlags flags) => AdminGrantShardsFlags = flags;
    }
}
