// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminDeleteModerationActionLogEntryHandler(ReducerEventContext ctx, ulong entityId);
        public event AdminDeleteModerationActionLogEntryHandler? OnAdminDeleteModerationActionLogEntry;

        public void AdminDeleteModerationActionLogEntry(ulong entityId)
        {
            conn.InternalCallReducer(new Reducer.AdminDeleteModerationActionLogEntry(entityId), this.SetCallReducerFlags.AdminDeleteModerationActionLogEntryFlags);
        }

        public bool InvokeAdminDeleteModerationActionLogEntry(ReducerEventContext ctx, Reducer.AdminDeleteModerationActionLogEntry args)
        {
            if (OnAdminDeleteModerationActionLogEntry == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminDeleteModerationActionLogEntry(
                ctx,
                args.EntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminDeleteModerationActionLogEntry : Reducer, IReducerArgs
        {
            [DataMember(Name = "entity_id")]
            public ulong EntityId;

            public AdminDeleteModerationActionLogEntry(ulong EntityId)
            {
                this.EntityId = EntityId;
            }

            public AdminDeleteModerationActionLogEntry()
            {
            }

            string IReducerArgs.ReducerName => "admin_delete_moderation_action_log_entry";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminDeleteModerationActionLogEntryFlags;
        public void AdminDeleteModerationActionLogEntry(CallReducerFlags flags) => AdminDeleteModerationActionLogEntryFlags = flags;
    }
}
