// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminRenamePlayerEntityHandler(ReducerEventContext ctx, ulong entityId, string newName);
        public event AdminRenamePlayerEntityHandler? OnAdminRenamePlayerEntity;

        public void AdminRenamePlayerEntity(ulong entityId, string newName)
        {
            conn.InternalCallReducer(new Reducer.AdminRenamePlayerEntity(entityId, newName), this.SetCallReducerFlags.AdminRenamePlayerEntityFlags);
        }

        public bool InvokeAdminRenamePlayerEntity(ReducerEventContext ctx, Reducer.AdminRenamePlayerEntity args)
        {
            if (OnAdminRenamePlayerEntity == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminRenamePlayerEntity(
                ctx,
                args.EntityId,
                args.NewName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminRenamePlayerEntity : Reducer, IReducerArgs
        {
            [DataMember(Name = "entity_id")]
            public ulong EntityId;
            [DataMember(Name = "new_name")]
            public string NewName;

            public AdminRenamePlayerEntity(
                ulong EntityId,
                string NewName
            )
            {
                this.EntityId = EntityId;
                this.NewName = NewName;
            }

            public AdminRenamePlayerEntity()
            {
                this.NewName = "";
            }

            string IReducerArgs.ReducerName => "admin_rename_player_entity";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminRenamePlayerEntityFlags;
        public void AdminRenamePlayerEntity(CallReducerFlags flags) => AdminRenamePlayerEntityFlags = flags;
    }
}
