// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminAddOrUpdateModerationFlagLevelThresholdHandler(ReducerEventContext ctx, byte flagLevel, int pointThreshold);
        public event AdminAddOrUpdateModerationFlagLevelThresholdHandler? OnAdminAddOrUpdateModerationFlagLevelThreshold;

        public void AdminAddOrUpdateModerationFlagLevelThreshold(byte flagLevel, int pointThreshold)
        {
            conn.InternalCallReducer(new Reducer.AdminAddOrUpdateModerationFlagLevelThreshold(flagLevel, pointThreshold), this.SetCallReducerFlags.AdminAddOrUpdateModerationFlagLevelThresholdFlags);
        }

        public bool InvokeAdminAddOrUpdateModerationFlagLevelThreshold(ReducerEventContext ctx, Reducer.AdminAddOrUpdateModerationFlagLevelThreshold args)
        {
            if (OnAdminAddOrUpdateModerationFlagLevelThreshold == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminAddOrUpdateModerationFlagLevelThreshold(
                ctx,
                args.FlagLevel,
                args.PointThreshold
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminAddOrUpdateModerationFlagLevelThreshold : Reducer, IReducerArgs
        {
            [DataMember(Name = "flag_level")]
            public byte FlagLevel;
            [DataMember(Name = "point_threshold")]
            public int PointThreshold;

            public AdminAddOrUpdateModerationFlagLevelThreshold(
                byte FlagLevel,
                int PointThreshold
            )
            {
                this.FlagLevel = FlagLevel;
                this.PointThreshold = PointThreshold;
            }

            public AdminAddOrUpdateModerationFlagLevelThreshold()
            {
            }

            string IReducerArgs.ReducerName => "admin_add_or_update_moderation_flag_level_threshold";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminAddOrUpdateModerationFlagLevelThresholdFlags;
        public void AdminAddOrUpdateModerationFlagLevelThreshold(CallReducerFlags flags) => AdminAddOrUpdateModerationFlagLevelThresholdFlags = flags;
    }
}
