// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminRemoveModerationViolationHandler(ReducerEventContext ctx, byte violationType);
        public event AdminRemoveModerationViolationHandler? OnAdminRemoveModerationViolation;

        public void AdminRemoveModerationViolation(byte violationType)
        {
            conn.InternalCallReducer(new Reducer.AdminRemoveModerationViolation(violationType), this.SetCallReducerFlags.AdminRemoveModerationViolationFlags);
        }

        public bool InvokeAdminRemoveModerationViolation(ReducerEventContext ctx, Reducer.AdminRemoveModerationViolation args)
        {
            if (OnAdminRemoveModerationViolation == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminRemoveModerationViolation(
                ctx,
                args.ViolationType
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminRemoveModerationViolation : Reducer, IReducerArgs
        {
            [DataMember(Name = "violation_type")]
            public byte ViolationType;

            public AdminRemoveModerationViolation(byte ViolationType)
            {
                this.ViolationType = ViolationType;
            }

            public AdminRemoveModerationViolation()
            {
            }

            string IReducerArgs.ReducerName => "admin_remove_moderation_violation";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminRemoveModerationViolationFlags;
        public void AdminRemoveModerationViolation(CallReducerFlags flags) => AdminRemoveModerationViolationFlags = flags;
    }
}
