// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminCreateDirectChatMessageHandler(ReducerEventContext ctx, string username, int titleId, ulong receiverId, string newMessageText);
        public event AdminCreateDirectChatMessageHandler? OnAdminCreateDirectChatMessage;

        public void AdminCreateDirectChatMessage(string username, int titleId, ulong receiverId, string newMessageText)
        {
            conn.InternalCallReducer(new Reducer.AdminCreateDirectChatMessage(username, titleId, receiverId, newMessageText), this.SetCallReducerFlags.AdminCreateDirectChatMessageFlags);
        }

        public bool InvokeAdminCreateDirectChatMessage(ReducerEventContext ctx, Reducer.AdminCreateDirectChatMessage args)
        {
            if (OnAdminCreateDirectChatMessage == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminCreateDirectChatMessage(
                ctx,
                args.Username,
                args.TitleId,
                args.ReceiverId,
                args.NewMessageText
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminCreateDirectChatMessage : Reducer, IReducerArgs
        {
            [DataMember(Name = "username")]
            public string Username;
            [DataMember(Name = "title_id")]
            public int TitleId;
            [DataMember(Name = "receiver_id")]
            public ulong ReceiverId;
            [DataMember(Name = "new_message_text")]
            public string NewMessageText;

            public AdminCreateDirectChatMessage(
                string Username,
                int TitleId,
                ulong ReceiverId,
                string NewMessageText
            )
            {
                this.Username = Username;
                this.TitleId = TitleId;
                this.ReceiverId = ReceiverId;
                this.NewMessageText = NewMessageText;
            }

            public AdminCreateDirectChatMessage()
            {
                this.Username = "";
                this.NewMessageText = "";
            }

            string IReducerArgs.ReducerName => "admin_create_direct_chat_message";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminCreateDirectChatMessageFlags;
        public void AdminCreateDirectChatMessage(CallReducerFlags flags) => AdminCreateDirectChatMessageFlags = flags;
    }
}
