// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminUnassignEmpireChunksHandler(ReducerEventContext ctx, System.Collections.Generic.List<ulong> chunkIndexes);
        public event AdminUnassignEmpireChunksHandler? OnAdminUnassignEmpireChunks;

        public void AdminUnassignEmpireChunks(System.Collections.Generic.List<ulong> chunkIndexes)
        {
            conn.InternalCallReducer(new Reducer.AdminUnassignEmpireChunks(chunkIndexes), this.SetCallReducerFlags.AdminUnassignEmpireChunksFlags);
        }

        public bool InvokeAdminUnassignEmpireChunks(ReducerEventContext ctx, Reducer.AdminUnassignEmpireChunks args)
        {
            if (OnAdminUnassignEmpireChunks == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminUnassignEmpireChunks(
                ctx,
                args.ChunkIndexes
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminUnassignEmpireChunks : Reducer, IReducerArgs
        {
            [DataMember(Name = "chunk_indexes")]
            public System.Collections.Generic.List<ulong> ChunkIndexes;

            public AdminUnassignEmpireChunks(System.Collections.Generic.List<ulong> ChunkIndexes)
            {
                this.ChunkIndexes = ChunkIndexes;
            }

            public AdminUnassignEmpireChunks()
            {
                this.ChunkIndexes = new();
            }

            string IReducerArgs.ReducerName => "admin_unassign_empire_chunks";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminUnassignEmpireChunksFlags;
        public void AdminUnassignEmpireChunks(CallReducerFlags flags) => AdminUnassignEmpireChunksFlags = flags;
    }
}
