// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminRemoveFlaggedWordHandler(ReducerEventContext ctx, ulong id);
        public event AdminRemoveFlaggedWordHandler? OnAdminRemoveFlaggedWord;

        public void AdminRemoveFlaggedWord(ulong id)
        {
            conn.InternalCallReducer(new Reducer.AdminRemoveFlaggedWord(id), this.SetCallReducerFlags.AdminRemoveFlaggedWordFlags);
        }

        public bool InvokeAdminRemoveFlaggedWord(ReducerEventContext ctx, Reducer.AdminRemoveFlaggedWord args)
        {
            if (OnAdminRemoveFlaggedWord == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminRemoveFlaggedWord(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminRemoveFlaggedWord : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public ulong Id;

            public AdminRemoveFlaggedWord(ulong Id)
            {
                this.Id = Id;
            }

            public AdminRemoveFlaggedWord()
            {
            }

            string IReducerArgs.ReducerName => "admin_remove_flagged_word";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminRemoveFlaggedWordFlags;
        public void AdminRemoveFlaggedWord(CallReducerFlags flags) => AdminRemoveFlaggedWordFlags = flags;
    }
}
