// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminRecalculateEmpireUpkeepsHandler(ReducerEventContext ctx);
        public event AdminRecalculateEmpireUpkeepsHandler? OnAdminRecalculateEmpireUpkeeps;

        public void AdminRecalculateEmpireUpkeeps()
        {
            conn.InternalCallReducer(new Reducer.AdminRecalculateEmpireUpkeeps(), this.SetCallReducerFlags.AdminRecalculateEmpireUpkeepsFlags);
        }

        public bool InvokeAdminRecalculateEmpireUpkeeps(ReducerEventContext ctx, Reducer.AdminRecalculateEmpireUpkeeps args)
        {
            if (OnAdminRecalculateEmpireUpkeeps == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminRecalculateEmpireUpkeeps(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminRecalculateEmpireUpkeeps : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "admin_recalculate_empire_upkeeps";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminRecalculateEmpireUpkeepsFlags;
        public void AdminRecalculateEmpireUpkeeps(CallReducerFlags flags) => AdminRecalculateEmpireUpkeepsFlags = flags;
    }
}
