// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminReplaceIdentityHandler(ReducerEventContext ctx, string oldIdentity, string newIdentity);
        public event AdminReplaceIdentityHandler? OnAdminReplaceIdentity;

        public void AdminReplaceIdentity(string oldIdentity, string newIdentity)
        {
            conn.InternalCallReducer(new Reducer.AdminReplaceIdentity(oldIdentity, newIdentity), this.SetCallReducerFlags.AdminReplaceIdentityFlags);
        }

        public bool InvokeAdminReplaceIdentity(ReducerEventContext ctx, Reducer.AdminReplaceIdentity args)
        {
            if (OnAdminReplaceIdentity == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminReplaceIdentity(
                ctx,
                args.OldIdentity,
                args.NewIdentity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminReplaceIdentity : Reducer, IReducerArgs
        {
            [DataMember(Name = "old_identity")]
            public string OldIdentity;
            [DataMember(Name = "new_identity")]
            public string NewIdentity;

            public AdminReplaceIdentity(
                string OldIdentity,
                string NewIdentity
            )
            {
                this.OldIdentity = OldIdentity;
                this.NewIdentity = NewIdentity;
            }

            public AdminReplaceIdentity()
            {
                this.OldIdentity = "";
                this.NewIdentity = "";
            }

            string IReducerArgs.ReducerName => "admin_replace_identity";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminReplaceIdentityFlags;
        public void AdminReplaceIdentity(CallReducerFlags flags) => AdminReplaceIdentityFlags = flags;
    }
}
