// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminSkipQueueIdentityHandler(ReducerEventContext ctx, SpacetimeDB.Identity identity);
        public event AdminSkipQueueIdentityHandler? OnAdminSkipQueueIdentity;

        public void AdminSkipQueueIdentity(SpacetimeDB.Identity identity)
        {
            conn.InternalCallReducer(new Reducer.AdminSkipQueueIdentity(identity), this.SetCallReducerFlags.AdminSkipQueueIdentityFlags);
        }

        public bool InvokeAdminSkipQueueIdentity(ReducerEventContext ctx, Reducer.AdminSkipQueueIdentity args)
        {
            if (OnAdminSkipQueueIdentity == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminSkipQueueIdentity(
                ctx,
                args.Identity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminSkipQueueIdentity : Reducer, IReducerArgs
        {
            [DataMember(Name = "identity")]
            public SpacetimeDB.Identity Identity;

            public AdminSkipQueueIdentity(SpacetimeDB.Identity Identity)
            {
                this.Identity = Identity;
            }

            public AdminSkipQueueIdentity()
            {
            }

            string IReducerArgs.ReducerName => "admin_skip_queue_identity";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminSkipQueueIdentityFlags;
        public void AdminSkipQueueIdentity(CallReducerFlags flags) => AdminSkipQueueIdentityFlags = flags;
    }
}
