// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminRenameEmpireRankHandler(ReducerEventContext ctx, string empireName, byte rank, string newName);
        public event AdminRenameEmpireRankHandler? OnAdminRenameEmpireRank;

        public void AdminRenameEmpireRank(string empireName, byte rank, string newName)
        {
            conn.InternalCallReducer(new Reducer.AdminRenameEmpireRank(empireName, rank, newName), this.SetCallReducerFlags.AdminRenameEmpireRankFlags);
        }

        public bool InvokeAdminRenameEmpireRank(ReducerEventContext ctx, Reducer.AdminRenameEmpireRank args)
        {
            if (OnAdminRenameEmpireRank == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminRenameEmpireRank(
                ctx,
                args.EmpireName,
                args.Rank,
                args.NewName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminRenameEmpireRank : Reducer, IReducerArgs
        {
            [DataMember(Name = "empire_name")]
            public string EmpireName;
            [DataMember(Name = "rank")]
            public byte Rank;
            [DataMember(Name = "new_name")]
            public string NewName;

            public AdminRenameEmpireRank(
                string EmpireName,
                byte Rank,
                string NewName
            )
            {
                this.EmpireName = EmpireName;
                this.Rank = Rank;
                this.NewName = NewName;
            }

            public AdminRenameEmpireRank()
            {
                this.EmpireName = "";
                this.NewName = "";
            }

            string IReducerArgs.ReducerName => "admin_rename_empire_rank";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminRenameEmpireRankFlags;
        public void AdminRenameEmpireRank(CallReducerFlags flags) => AdminRenameEmpireRankFlags = flags;
    }
}
