// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminRemoveModerationThresholdHandler(ReducerEventContext ctx, ulong id);
        public event AdminRemoveModerationThresholdHandler? OnAdminRemoveModerationThreshold;

        public void AdminRemoveModerationThreshold(ulong id)
        {
            conn.InternalCallReducer(new Reducer.AdminRemoveModerationThreshold(id), this.SetCallReducerFlags.AdminRemoveModerationThresholdFlags);
        }

        public bool InvokeAdminRemoveModerationThreshold(ReducerEventContext ctx, Reducer.AdminRemoveModerationThreshold args)
        {
            if (OnAdminRemoveModerationThreshold == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminRemoveModerationThreshold(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminRemoveModerationThreshold : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public ulong Id;

            public AdminRemoveModerationThreshold(ulong Id)
            {
                this.Id = Id;
            }

            public AdminRemoveModerationThreshold()
            {
            }

            string IReducerArgs.ReducerName => "admin_remove_moderation_threshold";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminRemoveModerationThresholdFlags;
        public void AdminRemoveModerationThreshold(CallReducerFlags flags) => AdminRemoveModerationThresholdFlags = flags;
    }
}
