// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminRemoveModerationConsequenceHandler(ReducerEventContext ctx, ulong id);
        public event AdminRemoveModerationConsequenceHandler? OnAdminRemoveModerationConsequence;

        public void AdminRemoveModerationConsequence(ulong id)
        {
            conn.InternalCallReducer(new Reducer.AdminRemoveModerationConsequence(id), this.SetCallReducerFlags.AdminRemoveModerationConsequenceFlags);
        }

        public bool InvokeAdminRemoveModerationConsequence(ReducerEventContext ctx, Reducer.AdminRemoveModerationConsequence args)
        {
            if (OnAdminRemoveModerationConsequence == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminRemoveModerationConsequence(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminRemoveModerationConsequence : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public ulong Id;

            public AdminRemoveModerationConsequence(ulong Id)
            {
                this.Id = Id;
            }

            public AdminRemoveModerationConsequence()
            {
            }

            string IReducerArgs.ReducerName => "admin_remove_moderation_consequence";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminRemoveModerationConsequenceFlags;
        public void AdminRemoveModerationConsequence(CallReducerFlags flags) => AdminRemoveModerationConsequenceFlags = flags;
    }
}
