// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminAddOrUpdateFlaggedWordHandler(ReducerEventContext ctx, ulong id, byte wordType, string word);
        public event AdminAddOrUpdateFlaggedWordHandler? OnAdminAddOrUpdateFlaggedWord;

        public void AdminAddOrUpdateFlaggedWord(ulong id, byte wordType, string word)
        {
            conn.InternalCallReducer(new Reducer.AdminAddOrUpdateFlaggedWord(id, wordType, word), this.SetCallReducerFlags.AdminAddOrUpdateFlaggedWordFlags);
        }

        public bool InvokeAdminAddOrUpdateFlaggedWord(ReducerEventContext ctx, Reducer.AdminAddOrUpdateFlaggedWord args)
        {
            if (OnAdminAddOrUpdateFlaggedWord == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminAddOrUpdateFlaggedWord(
                ctx,
                args.Id,
                args.WordType,
                args.Word
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminAddOrUpdateFlaggedWord : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public ulong Id;
            [DataMember(Name = "word_type")]
            public byte WordType;
            [DataMember(Name = "word")]
            public string Word;

            public AdminAddOrUpdateFlaggedWord(
                ulong Id,
                byte WordType,
                string Word
            )
            {
                this.Id = Id;
                this.WordType = WordType;
                this.Word = Word;
            }

            public AdminAddOrUpdateFlaggedWord()
            {
                this.Word = "";
            }

            string IReducerArgs.ReducerName => "admin_add_or_update_flagged_word";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminAddOrUpdateFlaggedWordFlags;
        public void AdminAddOrUpdateFlaggedWord(CallReducerFlags flags) => AdminAddOrUpdateFlaggedWordFlags = flags;
    }
}
