// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminRenameEmpireRankEntityHandler(ReducerEventContext ctx, ulong empireEntityId, byte rank, string newName);
        public event AdminRenameEmpireRankEntityHandler? OnAdminRenameEmpireRankEntity;

        public void AdminRenameEmpireRankEntity(ulong empireEntityId, byte rank, string newName)
        {
            conn.InternalCallReducer(new Reducer.AdminRenameEmpireRankEntity(empireEntityId, rank, newName), this.SetCallReducerFlags.AdminRenameEmpireRankEntityFlags);
        }

        public bool InvokeAdminRenameEmpireRankEntity(ReducerEventContext ctx, Reducer.AdminRenameEmpireRankEntity args)
        {
            if (OnAdminRenameEmpireRankEntity == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminRenameEmpireRankEntity(
                ctx,
                args.EmpireEntityId,
                args.Rank,
                args.NewName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminRenameEmpireRankEntity : Reducer, IReducerArgs
        {
            [DataMember(Name = "empire_entity_id")]
            public ulong EmpireEntityId;
            [DataMember(Name = "rank")]
            public byte Rank;
            [DataMember(Name = "new_name")]
            public string NewName;

            public AdminRenameEmpireRankEntity(
                ulong EmpireEntityId,
                byte Rank,
                string NewName
            )
            {
                this.EmpireEntityId = EmpireEntityId;
                this.Rank = Rank;
                this.NewName = NewName;
            }

            public AdminRenameEmpireRankEntity()
            {
                this.NewName = "";
            }

            string IReducerArgs.ReducerName => "admin_rename_empire_rank_entity";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminRenameEmpireRankEntityFlags;
        public void AdminRenameEmpireRankEntity(CallReducerFlags flags) => AdminRenameEmpireRankEntityFlags = flags;
    }
}
