// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AuthenticateHandler(ReducerEventContext ctx, string identity);
        public event AuthenticateHandler? OnAuthenticate;

        public void Authenticate(string identity)
        {
            conn.InternalCallReducer(new Reducer.Authenticate(identity), this.SetCallReducerFlags.AuthenticateFlags);
        }

        public bool InvokeAuthenticate(ReducerEventContext ctx, Reducer.Authenticate args)
        {
            if (OnAuthenticate == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAuthenticate(
                ctx,
                args.Identity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Authenticate : Reducer, IReducerArgs
        {
            [DataMember(Name = "identity")]
            public string Identity;

            public Authenticate(string Identity)
            {
                this.Identity = Identity;
            }

            public Authenticate()
            {
                this.Identity = "";
            }

            string IReducerArgs.ReducerName => "authenticate";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AuthenticateFlags;
        public void Authenticate(CallReducerFlags flags) => AuthenticateFlags = flags;
    }
}
