// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void BlockIdentityHandler(ReducerEventContext ctx, string identity);
        public event BlockIdentityHandler? OnBlockIdentity;

        public void BlockIdentity(string identity)
        {
            conn.InternalCallReducer(new Reducer.BlockIdentity(identity), this.SetCallReducerFlags.BlockIdentityFlags);
        }

        public bool InvokeBlockIdentity(ReducerEventContext ctx, Reducer.BlockIdentity args)
        {
            if (OnBlockIdentity == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnBlockIdentity(
                ctx,
                args.Identity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class BlockIdentity : Reducer, IReducerArgs
        {
            [DataMember(Name = "identity")]
            public string Identity;

            public BlockIdentity(string Identity)
            {
                this.Identity = Identity;
            }

            public BlockIdentity()
            {
                this.Identity = "";
            }

            string IReducerArgs.ReducerName => "block_identity";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags BlockIdentityFlags;
        public void BlockIdentity(CallReducerFlags flags) => BlockIdentityFlags = flags;
    }
}
