// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void BlockPlayerHandler(ReducerEventContext ctx, ulong playerEntityId);
        public event BlockPlayerHandler? OnBlockPlayer;

        public void BlockPlayer(ulong playerEntityId)
        {
            conn.InternalCallReducer(new Reducer.BlockPlayer(playerEntityId), this.SetCallReducerFlags.BlockPlayerFlags);
        }

        public bool InvokeBlockPlayer(ReducerEventContext ctx, Reducer.BlockPlayer args)
        {
            if (OnBlockPlayer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnBlockPlayer(
                ctx,
                args.PlayerEntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class BlockPlayer : Reducer, IReducerArgs
        {
            [DataMember(Name = "player_entity_id")]
            public ulong PlayerEntityId;

            public BlockPlayer(ulong PlayerEntityId)
            {
                this.PlayerEntityId = PlayerEntityId;
            }

            public BlockPlayer()
            {
            }

            string IReducerArgs.ReducerName => "block_player";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags BlockPlayerFlags;
        public void BlockPlayer(CallReducerFlags flags) => BlockPlayerFlags = flags;
    }
}
