// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CheatEmpireSiegeCancelHandler(ReducerEventContext ctx, ulong siegeNodeEntityId);
        public event CheatEmpireSiegeCancelHandler? OnCheatEmpireSiegeCancel;

        public void CheatEmpireSiegeCancel(ulong siegeNodeEntityId)
        {
            conn.InternalCallReducer(new Reducer.CheatEmpireSiegeCancel(siegeNodeEntityId), this.SetCallReducerFlags.CheatEmpireSiegeCancelFlags);
        }

        public bool InvokeCheatEmpireSiegeCancel(ReducerEventContext ctx, Reducer.CheatEmpireSiegeCancel args)
        {
            if (OnCheatEmpireSiegeCancel == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCheatEmpireSiegeCancel(
                ctx,
                args.SiegeNodeEntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CheatEmpireSiegeCancel : Reducer, IReducerArgs
        {
            [DataMember(Name = "siege_node_entity_id")]
            public ulong SiegeNodeEntityId;

            public CheatEmpireSiegeCancel(ulong SiegeNodeEntityId)
            {
                this.SiegeNodeEntityId = SiegeNodeEntityId;
            }

            public CheatEmpireSiegeCancel()
            {
            }

            string IReducerArgs.ReducerName => "cheat_empire_siege_cancel";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CheatEmpireSiegeCancelFlags;
        public void CheatEmpireSiegeCancel(CallReducerFlags flags) => CheatEmpireSiegeCancelFlags = flags;
    }
}
