// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EditChatChannelHandler(ReducerEventContext ctx, ulong entityId, string name, string description, BitCraftGlobal.Types.ChatChannelVisibility visibility);
        public event EditChatChannelHandler? OnEditChatChannel;

        public void EditChatChannel(ulong entityId, string name, string description, BitCraftGlobal.Types.ChatChannelVisibility visibility)
        {
            conn.InternalCallReducer(new Reducer.EditChatChannel(entityId, name, description, visibility), this.SetCallReducerFlags.EditChatChannelFlags);
        }

        public bool InvokeEditChatChannel(ReducerEventContext ctx, Reducer.EditChatChannel args)
        {
            if (OnEditChatChannel == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEditChatChannel(
                ctx,
                args.EntityId,
                args.Name,
                args.Description,
                args.Visibility
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EditChatChannel : Reducer, IReducerArgs
        {
            [DataMember(Name = "entity_id")]
            public ulong EntityId;
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "description")]
            public string Description;
            [DataMember(Name = "visibility")]
            public ChatChannelVisibility Visibility;

            public EditChatChannel(
                ulong EntityId,
                string Name,
                string Description,
                ChatChannelVisibility Visibility
            )
            {
                this.EntityId = EntityId;
                this.Name = Name;
                this.Description = Description;
                this.Visibility = Visibility;
            }

            public EditChatChannel()
            {
                this.Name = "";
                this.Description = "";
            }

            string IReducerArgs.ReducerName => "edit_chat_channel";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags EditChatChannelFlags;
        public void EditChatChannel(CallReducerFlags flags) => EditChatChannelFlags = flags;
    }
}
