// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EmpireMoveCapitalHandler(ReducerEventContext ctx, ulong targetClaimEntityId);
        public event EmpireMoveCapitalHandler? OnEmpireMoveCapital;

        public void EmpireMoveCapital(ulong targetClaimEntityId)
        {
            conn.InternalCallReducer(new Reducer.EmpireMoveCapital(targetClaimEntityId), this.SetCallReducerFlags.EmpireMoveCapitalFlags);
        }

        public bool InvokeEmpireMoveCapital(ReducerEventContext ctx, Reducer.EmpireMoveCapital args)
        {
            if (OnEmpireMoveCapital == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEmpireMoveCapital(
                ctx,
                args.TargetClaimEntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EmpireMoveCapital : Reducer, IReducerArgs
        {
            [DataMember(Name = "target_claim_entity_id")]
            public ulong TargetClaimEntityId;

            public EmpireMoveCapital(ulong TargetClaimEntityId)
            {
                this.TargetClaimEntityId = TargetClaimEntityId;
            }

            public EmpireMoveCapital()
            {
            }

            string IReducerArgs.ReducerName => "empire_move_capital";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags EmpireMoveCapitalFlags;
        public void EmpireMoveCapital(CallReducerFlags flags) => EmpireMoveCapitalFlags = flags;
    }
}
