// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EmpireSetPlayerRankHandler(ReducerEventContext ctx, BitCraftGlobal.Types.EmpireSetPlayerRankRequest request);
        public event EmpireSetPlayerRankHandler? OnEmpireSetPlayerRank;

        public void EmpireSetPlayerRank(BitCraftGlobal.Types.EmpireSetPlayerRankRequest request)
        {
            conn.InternalCallReducer(new Reducer.EmpireSetPlayerRank(request), this.SetCallReducerFlags.EmpireSetPlayerRankFlags);
        }

        public bool InvokeEmpireSetPlayerRank(ReducerEventContext ctx, Reducer.EmpireSetPlayerRank args)
        {
            if (OnEmpireSetPlayerRank == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEmpireSetPlayerRank(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EmpireSetPlayerRank : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public EmpireSetPlayerRankRequest Request;

            public EmpireSetPlayerRank(EmpireSetPlayerRankRequest Request)
            {
                this.Request = Request;
            }

            public EmpireSetPlayerRank()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "empire_set_player_rank";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags EmpireSetPlayerRankFlags;
        public void EmpireSetPlayerRank(CallReducerFlags flags) => EmpireSetPlayerRankFlags = flags;
    }
}
