// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void JoinChatChannelHandler(ReducerEventContext ctx, ulong entityId);
        public event JoinChatChannelHandler? OnJoinChatChannel;

        public void JoinChatChannel(ulong entityId)
        {
            conn.InternalCallReducer(new Reducer.JoinChatChannel(entityId), this.SetCallReducerFlags.JoinChatChannelFlags);
        }

        public bool InvokeJoinChatChannel(ReducerEventContext ctx, Reducer.JoinChatChannel args)
        {
            if (OnJoinChatChannel == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnJoinChatChannel(
                ctx,
                args.EntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class JoinChatChannel : Reducer, IReducerArgs
        {
            [DataMember(Name = "entity_id")]
            public ulong EntityId;

            public JoinChatChannel(ulong EntityId)
            {
                this.EntityId = EntityId;
            }

            public JoinChatChannel()
            {
            }

            string IReducerArgs.ReducerName => "join_chat_channel";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags JoinChatChannelFlags;
        public void JoinChatChannel(CallReducerFlags flags) => JoinChatChannelFlags = flags;
    }
}
