// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void LeaveChatChannelHandler(ReducerEventContext ctx, ulong entityId);
        public event LeaveChatChannelHandler? OnLeaveChatChannel;

        public void LeaveChatChannel(ulong entityId)
        {
            conn.InternalCallReducer(new Reducer.LeaveChatChannel(entityId), this.SetCallReducerFlags.LeaveChatChannelFlags);
        }

        public bool InvokeLeaveChatChannel(ReducerEventContext ctx, Reducer.LeaveChatChannel args)
        {
            if (OnLeaveChatChannel == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnLeaveChatChannel(
                ctx,
                args.EntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class LeaveChatChannel : Reducer, IReducerArgs
        {
            [DataMember(Name = "entity_id")]
            public ulong EntityId;

            public LeaveChatChannel(ulong EntityId)
            {
                this.EntityId = EntityId;
            }

            public LeaveChatChannel()
            {
            }

            string IReducerArgs.ReducerName => "leave_chat_channel";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags LeaveChatChannelFlags;
        public void LeaveChatChannel(CallReducerFlags flags) => LeaveChatChannelFlags = flags;
    }
}
