// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerSetNameHandler(ReducerEventContext ctx, BitCraftGlobal.Types.PlayerSetNameRequest request);
        public event PlayerSetNameHandler? OnPlayerSetName;

        public void PlayerSetName(BitCraftGlobal.Types.PlayerSetNameRequest request)
        {
            conn.InternalCallReducer(new Reducer.PlayerSetName(request), this.SetCallReducerFlags.PlayerSetNameFlags);
        }

        public bool InvokePlayerSetName(ReducerEventContext ctx, Reducer.PlayerSetName args)
        {
            if (OnPlayerSetName == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlayerSetName(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerSetName : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerSetNameRequest Request;

            public PlayerSetName(PlayerSetNameRequest Request)
            {
                this.Request = Request;
            }

            public PlayerSetName()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "player_set_name";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PlayerSetNameFlags;
        public void PlayerSetName(CallReducerFlags flags) => PlayerSetNameFlags = flags;
    }
}
