// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerRestoreSkillsHandler(ReducerEventContext ctx, ulong playerEntityId);
        public event PlayerRestoreSkillsHandler? OnPlayerRestoreSkills;

        public void PlayerRestoreSkills(ulong playerEntityId)
        {
            conn.InternalCallReducer(new Reducer.PlayerRestoreSkills(playerEntityId), this.SetCallReducerFlags.PlayerRestoreSkillsFlags);
        }

        public bool InvokePlayerRestoreSkills(ReducerEventContext ctx, Reducer.PlayerRestoreSkills args)
        {
            if (OnPlayerRestoreSkills == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlayerRestoreSkills(
                ctx,
                args.PlayerEntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerRestoreSkills : Reducer, IReducerArgs
        {
            [DataMember(Name = "player_entity_id")]
            public ulong PlayerEntityId;

            public PlayerRestoreSkills(ulong PlayerEntityId)
            {
                this.PlayerEntityId = PlayerEntityId;
            }

            public PlayerRestoreSkills()
            {
            }

            string IReducerArgs.ReducerName => "player_restore_skills";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PlayerRestoreSkillsFlags;
        public void PlayerRestoreSkills(CallReducerFlags flags) => PlayerRestoreSkillsFlags = flags;
    }
}
