// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerCreateHandler(ReducerEventContext ctx);
        public event PlayerCreateHandler? OnPlayerCreate;

        public void PlayerCreate()
        {
            conn.InternalCallReducer(new Reducer.PlayerCreate(), this.SetCallReducerFlags.PlayerCreateFlags);
        }

        public bool InvokePlayerCreate(ReducerEventContext ctx, Reducer.PlayerCreate args)
        {
            if (OnPlayerCreate == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlayerCreate(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerCreate : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "player_create";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PlayerCreateFlags;
        public void PlayerCreate(CallReducerFlags flags) => PlayerCreateFlags = flags;
    }
}
