// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerDismissNotificationHandler(ReducerEventContext ctx);
        public event PlayerDismissNotificationHandler? OnPlayerDismissNotification;

        public void PlayerDismissNotification()
        {
            conn.InternalCallReducer(new Reducer.PlayerDismissNotification(), this.SetCallReducerFlags.PlayerDismissNotificationFlags);
        }

        public bool InvokePlayerDismissNotification(ReducerEventContext ctx, Reducer.PlayerDismissNotification args)
        {
            if (OnPlayerDismissNotification == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlayerDismissNotification(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerDismissNotification : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "player_dismiss_notification";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PlayerDismissNotificationFlags;
        public void PlayerDismissNotification(CallReducerFlags flags) => PlayerDismissNotificationFlags = flags;
    }
}
