// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RemoveChatChannelHandler(ReducerEventContext ctx, ulong entityId);
        public event RemoveChatChannelHandler? OnRemoveChatChannel;

        public void RemoveChatChannel(ulong entityId)
        {
            conn.InternalCallReducer(new Reducer.RemoveChatChannel(entityId), this.SetCallReducerFlags.RemoveChatChannelFlags);
        }

        public bool InvokeRemoveChatChannel(ReducerEventContext ctx, Reducer.RemoveChatChannel args)
        {
            if (OnRemoveChatChannel == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRemoveChatChannel(
                ctx,
                args.EntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RemoveChatChannel : Reducer, IReducerArgs
        {
            [DataMember(Name = "entity_id")]
            public ulong EntityId;

            public RemoveChatChannel(ulong EntityId)
            {
                this.EntityId = EntityId;
            }

            public RemoveChatChannel()
            {
            }

            string IReducerArgs.ReducerName => "remove_chat_channel";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags RemoveChatChannelFlags;
        public void RemoveChatChannel(CallReducerFlags flags) => RemoveChatChannelFlags = flags;
    }
}
