// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ReportTargetedChatMessageHandler(ReducerEventContext ctx, ulong chatMessageId, string reportType, string message);
        public event ReportTargetedChatMessageHandler? OnReportTargetedChatMessage;

        public void ReportTargetedChatMessage(ulong chatMessageId, string reportType, string message)
        {
            conn.InternalCallReducer(new Reducer.ReportTargetedChatMessage(chatMessageId, reportType, message), this.SetCallReducerFlags.ReportTargetedChatMessageFlags);
        }

        public bool InvokeReportTargetedChatMessage(ReducerEventContext ctx, Reducer.ReportTargetedChatMessage args)
        {
            if (OnReportTargetedChatMessage == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnReportTargetedChatMessage(
                ctx,
                args.ChatMessageId,
                args.ReportType,
                args.Message
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ReportTargetedChatMessage : Reducer, IReducerArgs
        {
            [DataMember(Name = "chat_message_id")]
            public ulong ChatMessageId;
            [DataMember(Name = "report_type")]
            public string ReportType;
            [DataMember(Name = "message")]
            public string Message;

            public ReportTargetedChatMessage(
                ulong ChatMessageId,
                string ReportType,
                string Message
            )
            {
                this.ChatMessageId = ChatMessageId;
                this.ReportType = ReportType;
                this.Message = Message;
            }

            public ReportTargetedChatMessage()
            {
                this.ReportType = "";
                this.Message = "";
            }

            string IReducerArgs.ReducerName => "report_targeted_chat_message";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ReportTargetedChatMessageFlags;
        public void ReportTargetedChatMessage(CallReducerFlags flags) => ReportTargetedChatMessageFlags = flags;
    }
}
