// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UnblockPlayerHandler(ReducerEventContext ctx, ulong playerEntityId);
        public event UnblockPlayerHandler? OnUnblockPlayer;

        public void UnblockPlayer(ulong playerEntityId)
        {
            conn.InternalCallReducer(new Reducer.UnblockPlayer(playerEntityId), this.SetCallReducerFlags.UnblockPlayerFlags);
        }

        public bool InvokeUnblockPlayer(ReducerEventContext ctx, Reducer.UnblockPlayer args)
        {
            if (OnUnblockPlayer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUnblockPlayer(
                ctx,
                args.PlayerEntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UnblockPlayer : Reducer, IReducerArgs
        {
            [DataMember(Name = "player_entity_id")]
            public ulong PlayerEntityId;

            public UnblockPlayer(ulong PlayerEntityId)
            {
                this.PlayerEntityId = PlayerEntityId;
            }

            public UnblockPlayer()
            {
            }

            string IReducerArgs.ReducerName => "unblock_player";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UnblockPlayerFlags;
        public void UnblockPlayer(CallReducerFlags flags) => UnblockPlayerFlags = flags;
    }
}
