// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UserModerationDeleteHandler(ReducerEventContext ctx, ulong policyEntityId);
        public event UserModerationDeleteHandler? OnUserModerationDelete;

        public void UserModerationDelete(ulong policyEntityId)
        {
            conn.InternalCallReducer(new Reducer.UserModerationDelete(policyEntityId), this.SetCallReducerFlags.UserModerationDeleteFlags);
        }

        public bool InvokeUserModerationDelete(ReducerEventContext ctx, Reducer.UserModerationDelete args)
        {
            if (OnUserModerationDelete == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUserModerationDelete(
                ctx,
                args.PolicyEntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UserModerationDelete : Reducer, IReducerArgs
        {
            [DataMember(Name = "policy_entity_id")]
            public ulong PolicyEntityId;

            public UserModerationDelete(ulong PolicyEntityId)
            {
                this.PolicyEntityId = PolicyEntityId;
            }

            public UserModerationDelete()
            {
            }

            string IReducerArgs.ReducerName => "user_moderation_delete";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UserModerationDeleteFlags;
        public void UserModerationDelete(CallReducerFlags flags) => UserModerationDeleteFlags = flags;
    }
}
