// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BlockedPlayerState
    {
        [DataMember(Name = "owner_entity_id")]
        public ulong OwnerEntityId;
        [DataMember(Name = "blocked_entity_id")]
        public ulong BlockedEntityId;

        public BlockedPlayerState(
            ulong OwnerEntityId,
            ulong BlockedEntityId
        )
        {
            this.OwnerEntityId = OwnerEntityId;
            this.BlockedEntityId = BlockedEntityId;
        }

        public BlockedPlayerState()
        {
        }
    }
}
