// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ChatChannelState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "lowercase_name")]
        public string LowercaseName;
        [DataMember(Name = "description")]
        public string Description;
        [DataMember(Name = "visibility")]
        public ChatChannelVisibility Visibility;

        public ChatChannelState(
            ulong EntityId,
            string Name,
            string LowercaseName,
            string Description,
            ChatChannelVisibility Visibility
        )
        {
            this.EntityId = EntityId;
            this.Name = Name;
            this.LowercaseName = LowercaseName;
            this.Description = Description;
            this.Visibility = Visibility;
        }

        public ChatChannelState()
        {
            this.Name = "";
            this.LowercaseName = "";
            this.Description = "";
        }
    }
}
