// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DirectMessageState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "username")]
        public string Username;
        [DataMember(Name = "title_id")]
        public int TitleId;
        [DataMember(Name = "sender_entity_id")]
        public ulong SenderEntityId;
        [DataMember(Name = "receiver_entity_id")]
        public ulong ReceiverEntityId;
        [DataMember(Name = "text")]
        public string Text;
        [DataMember(Name = "timestamp")]
        public int Timestamp;
        [DataMember(Name = "language_code")]
        public string? LanguageCode;

        public DirectMessageState(
            ulong EntityId,
            string Username,
            int TitleId,
            ulong SenderEntityId,
            ulong ReceiverEntityId,
            string Text,
            int Timestamp,
            string? LanguageCode
        )
        {
            this.EntityId = EntityId;
            this.Username = Username;
            this.TitleId = TitleId;
            this.SenderEntityId = SenderEntityId;
            this.ReceiverEntityId = ReceiverEntityId;
            this.Text = Text;
            this.Timestamp = Timestamp;
            this.LanguageCode = LanguageCode;
        }

        public DirectMessageState()
        {
            this.Username = "";
            this.Text = "";
        }
    }
}
