// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EmpireUpdatePermissionsRequest
    {
        [DataMember(Name = "empire_entity_id")]
        public ulong EmpireEntityId;
        [DataMember(Name = "rank")]
        public byte Rank;
        [DataMember(Name = "permissions")]
        public System.Collections.Generic.List<bool> Permissions;

        public EmpireUpdatePermissionsRequest(
            ulong EmpireEntityId,
            byte Rank,
            System.Collections.Generic.List<bool> Permissions
        )
        {
            this.EmpireEntityId = EmpireEntityId;
            this.Rank = Rank;
            this.Permissions = Permissions;
        }

        public EmpireUpdatePermissionsRequest()
        {
            this.Permissions = new();
        }
    }
}
