// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EmpireChangeEmblemRequest
    {
        [DataMember(Name = "empire_entity_id")]
        public ulong EmpireEntityId;
        [DataMember(Name = "icon_id")]
        public int IconId;
        [DataMember(Name = "shape_id")]
        public int ShapeId;
        [DataMember(Name = "color1_id")]
        public int Color1Id;
        [DataMember(Name = "color2_id")]
        public int Color2Id;

        public EmpireChangeEmblemRequest(
            ulong EmpireEntityId,
            int IconId,
            int ShapeId,
            int Color1Id,
            int Color2Id
        )
        {
            this.EmpireEntityId = EmpireEntityId;
            this.IconId = IconId;
            this.ShapeId = ShapeId;
            this.Color1Id = Color1Id;
            this.Color2Id = Color2Id;
        }

        public EmpireChangeEmblemRequest()
        {
        }
    }
}
