// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EmpirePlayerJoinRequest
    {
        [DataMember(Name = "empire_entity_id")]
        public ulong EmpireEntityId;

        public EmpirePlayerJoinRequest(ulong EmpireEntityId)
        {
            this.EmpireEntityId = EmpireEntityId;
        }

        public EmpirePlayerJoinRequest()
        {
        }
    }
}
