// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class FriendsState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "owner_entity_id")]
        public ulong OwnerEntityId;
        [DataMember(Name = "friend_entity_id")]
        public ulong FriendEntityId;
        [DataMember(Name = "is_favorite")]
        public bool IsFavorite;

        public FriendsState(
            ulong EntityId,
            ulong OwnerEntityId,
            ulong FriendEntityId,
            bool IsFavorite
        )
        {
            this.EntityId = EntityId;
            this.OwnerEntityId = OwnerEntityId;
            this.FriendEntityId = FriendEntityId;
            this.IsFavorite = IsFavorite;
        }

        public FriendsState()
        {
        }
    }
}
