// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ModConsequenceState
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "point_threshold")]
        public int PointThreshold;
        [DataMember(Name = "consequence_type")]
        public byte ConsequenceType;
        [DataMember(Name = "duration")]
        public int Duration;
        [DataMember(Name = "flag_level_code")]
        public byte FlagLevelCode;

        public ModConsequenceState(
            ulong Id,
            int PointThreshold,
            byte ConsequenceType,
            int Duration,
            byte FlagLevelCode
        )
        {
            this.Id = Id;
            this.PointThreshold = PointThreshold;
            this.ConsequenceType = ConsequenceType;
            this.Duration = Duration;
            this.FlagLevelCode = FlagLevelCode;
        }

        public ModConsequenceState()
        {
        }
    }
}
