// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ModReplacementTextState
    {
        [DataMember(Name = "text_type")]
        public byte TextType;
        [DataMember(Name = "text")]
        public string Text;

        public ModReplacementTextState(
            byte TextType,
            string Text
        )
        {
            this.TextType = TextType;
            this.Text = Text;
        }

        public ModReplacementTextState()
        {
            this.Text = "";
        }
    }
}
