// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ModViolationState
    {
        [DataMember(Name = "violation_type")]
        public byte ViolationType;
        [DataMember(Name = "point_value_min")]
        public int PointValueMin;
        [DataMember(Name = "point_value_max")]
        public int PointValueMax;

        public ModViolationState(
            byte ViolationType,
            int PointValueMin,
            int PointValueMax
        )
        {
            this.ViolationType = ViolationType;
            this.PointValueMin = PointValueMin;
            this.PointValueMax = PointValueMax;
        }

        public ModViolationState()
        {
        }
    }
}
