// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ModWordReplacementState
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "words_to_replace")]
        public System.Collections.Generic.List<string> WordsToReplace;
        [DataMember(Name = "text_replacement")]
        public string TextReplacement;
        [DataMember(Name = "is_developer_url_replacement")]
        public bool IsDeveloperUrlReplacement;

        public ModWordReplacementState(
            ulong Id,
            System.Collections.Generic.List<string> WordsToReplace,
            string TextReplacement,
            bool IsDeveloperUrlReplacement
        )
        {
            this.Id = Id;
            this.WordsToReplace = WordsToReplace;
            this.TextReplacement = TextReplacement;
            this.IsDeveloperUrlReplacement = IsDeveloperUrlReplacement;
        }

        public ModWordReplacementState()
        {
            this.WordsToReplace = new();
            this.TextReplacement = "";
        }
    }
}
