// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TranslationCorrections
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "string_index")]
        public uint StringIndex;
        [DataMember(Name = "player_entity_id")]
        public ulong PlayerEntityId;
        [DataMember(Name = "lang")]
        public string Lang;
        [DataMember(Name = "translation")]
        public string Translation;

        public TranslationCorrections(
            ulong Id,
            uint StringIndex,
            ulong PlayerEntityId,
            string Lang,
            string Translation
        )
        {
            this.Id = Id;
            this.StringIndex = StringIndex;
            this.PlayerEntityId = PlayerEntityId;
            this.Lang = Lang;
            this.Translation = Translation;
        }

        public TranslationCorrections()
        {
            this.Lang = "";
            this.Translation = "";
        }
    }
}
