// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class VisibilityState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "visibility")]
        public VisibilityType Visibility;

        public VisibilityState(
            ulong EntityId,
            VisibilityType Visibility
        )
        {
            this.EntityId = EntityId;
            this.Visibility = Visibility;
        }

        public VisibilityState()
        {
        }
    }
}
