// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminUnassignEmpireChunksArgs {
    pub chunk_indexes: Vec::<u64>,
}

impl From<AdminUnassignEmpireChunksArgs> for super::Reducer {
    fn from(args: AdminUnassignEmpireChunksArgs) -> Self {
        Self::AdminUnassignEmpireChunks {
            chunk_indexes: args.chunk_indexes,
}
}
}

impl __sdk::InModule for AdminUnassignEmpireChunksArgs {
    type Module = super::RemoteModule;
}

pub struct AdminUnassignEmpireChunksCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_unassign_empire_chunks`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_unassign_empire_chunks {
    /// Request that the remote module invoke the reducer `admin_unassign_empire_chunks` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_admin_unassign_empire_chunks`] callbacks.
    fn admin_unassign_empire_chunks(&self, chunk_indexes: Vec::<u64>,
) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `admin_unassign_empire_chunks`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AdminUnassignEmpireChunksCallbackId`] can be passed to [`Self::remove_on_admin_unassign_empire_chunks`]
    /// to cancel the callback.
    fn on_admin_unassign_empire_chunks(&self, callback: impl FnMut(&super::ReducerEventContext, &Vec::<u64>, ) + Send + 'static) -> AdminUnassignEmpireChunksCallbackId;
    /// Cancel a callback previously registered by [`Self::on_admin_unassign_empire_chunks`],
    /// causing it not to run in the future.
    fn remove_on_admin_unassign_empire_chunks(&self, callback: AdminUnassignEmpireChunksCallbackId);
}

impl admin_unassign_empire_chunks for super::RemoteReducers {
    fn admin_unassign_empire_chunks(&self, chunk_indexes: Vec::<u64>,
) -> __sdk::Result<()> {
        self.imp.call_reducer("admin_unassign_empire_chunks", AdminUnassignEmpireChunksArgs { chunk_indexes,  })
    }
    fn on_admin_unassign_empire_chunks(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &Vec::<u64>, ) + Send + 'static,
    ) -> AdminUnassignEmpireChunksCallbackId {
        AdminUnassignEmpireChunksCallbackId(self.imp.on_reducer(
            "admin_unassign_empire_chunks",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event: __sdk::ReducerEvent {
                        reducer: super::Reducer::AdminUnassignEmpireChunks {
                            chunk_indexes, 
                        },
                        ..
                    },
                    ..
                } = ctx else { unreachable!() };
                callback(ctx, chunk_indexes, )
            }),
        ))
    }
    fn remove_on_admin_unassign_empire_chunks(&self, callback: AdminUnassignEmpireChunksCallbackId) {
        self.imp.remove_on_reducer("admin_unassign_empire_chunks", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `admin_unassign_empire_chunks`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_admin_unassign_empire_chunks {
    /// Set the call-reducer flags for the reducer `admin_unassign_empire_chunks` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn admin_unassign_empire_chunks(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_admin_unassign_empire_chunks for super::SetReducerFlags {
    fn admin_unassign_empire_chunks(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("admin_unassign_empire_chunks", flags);
    }
}

