// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminAddOrUpdateWordReplacementArgs {
    pub id: u64,
    pub words_to_replace: Vec::<String>,
    pub text_replacement: String,
    pub is_developer_url_replacement: bool,
}

impl From<AdminAddOrUpdateWordReplacementArgs> for super::Reducer {
    fn from(args: AdminAddOrUpdateWordReplacementArgs) -> Self {
        Self::AdminAddOrUpdateWordReplacement {
            id: args.id,
            words_to_replace: args.words_to_replace,
            text_replacement: args.text_replacement,
            is_developer_url_replacement: args.is_developer_url_replacement,
}
}
}

impl __sdk::InModule for AdminAddOrUpdateWordReplacementArgs {
    type Module = super::RemoteModule;
}

pub struct AdminAddOrUpdateWordReplacementCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_add_or_update_word_replacement`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_add_or_update_word_replacement {
    /// Request that the remote module invoke the reducer `admin_add_or_update_word_replacement` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_admin_add_or_update_word_replacement`] callbacks.
    fn admin_add_or_update_word_replacement(&self, id: u64,
words_to_replace: Vec::<String>,
text_replacement: String,
is_developer_url_replacement: bool,
) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `admin_add_or_update_word_replacement`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AdminAddOrUpdateWordReplacementCallbackId`] can be passed to [`Self::remove_on_admin_add_or_update_word_replacement`]
    /// to cancel the callback.
    fn on_admin_add_or_update_word_replacement(&self, callback: impl FnMut(&super::ReducerEventContext, &u64, &Vec::<String>, &String, &bool, ) + Send + 'static) -> AdminAddOrUpdateWordReplacementCallbackId;
    /// Cancel a callback previously registered by [`Self::on_admin_add_or_update_word_replacement`],
    /// causing it not to run in the future.
    fn remove_on_admin_add_or_update_word_replacement(&self, callback: AdminAddOrUpdateWordReplacementCallbackId);
}

impl admin_add_or_update_word_replacement for super::RemoteReducers {
    fn admin_add_or_update_word_replacement(&self, id: u64,
words_to_replace: Vec::<String>,
text_replacement: String,
is_developer_url_replacement: bool,
) -> __sdk::Result<()> {
        self.imp.call_reducer("admin_add_or_update_word_replacement", AdminAddOrUpdateWordReplacementArgs { id, words_to_replace, text_replacement, is_developer_url_replacement,  })
    }
    fn on_admin_add_or_update_word_replacement(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &Vec::<String>, &String, &bool, ) + Send + 'static,
    ) -> AdminAddOrUpdateWordReplacementCallbackId {
        AdminAddOrUpdateWordReplacementCallbackId(self.imp.on_reducer(
            "admin_add_or_update_word_replacement",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event: __sdk::ReducerEvent {
                        reducer: super::Reducer::AdminAddOrUpdateWordReplacement {
                            id, words_to_replace, text_replacement, is_developer_url_replacement, 
                        },
                        ..
                    },
                    ..
                } = ctx else { unreachable!() };
                callback(ctx, id, words_to_replace, text_replacement, is_developer_url_replacement, )
            }),
        ))
    }
    fn remove_on_admin_add_or_update_word_replacement(&self, callback: AdminAddOrUpdateWordReplacementCallbackId) {
        self.imp.remove_on_reducer("admin_add_or_update_word_replacement", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `admin_add_or_update_word_replacement`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_admin_add_or_update_word_replacement {
    /// Set the call-reducer flags for the reducer `admin_add_or_update_word_replacement` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn admin_add_or_update_word_replacement(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_admin_add_or_update_word_replacement for super::SetReducerFlags {
    fn admin_add_or_update_word_replacement(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("admin_add_or_update_word_replacement", flags);
    }
}

