// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminAddPlayerPreviousNameArgs {
    pub identity: String,
    pub name: String,
}

impl From<AdminAddPlayerPreviousNameArgs> for super::Reducer {
    fn from(args: AdminAddPlayerPreviousNameArgs) -> Self {
        Self::AdminAddPlayerPreviousName {
            identity: args.identity,
            name: args.name,
}
}
}

impl __sdk::InModule for AdminAddPlayerPreviousNameArgs {
    type Module = super::RemoteModule;
}

pub struct AdminAddPlayerPreviousNameCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_add_player_previous_name`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_add_player_previous_name {
    /// Request that the remote module invoke the reducer `admin_add_player_previous_name` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_admin_add_player_previous_name`] callbacks.
    fn admin_add_player_previous_name(&self, identity: String,
name: String,
) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `admin_add_player_previous_name`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AdminAddPlayerPreviousNameCallbackId`] can be passed to [`Self::remove_on_admin_add_player_previous_name`]
    /// to cancel the callback.
    fn on_admin_add_player_previous_name(&self, callback: impl FnMut(&super::ReducerEventContext, &String, &String, ) + Send + 'static) -> AdminAddPlayerPreviousNameCallbackId;
    /// Cancel a callback previously registered by [`Self::on_admin_add_player_previous_name`],
    /// causing it not to run in the future.
    fn remove_on_admin_add_player_previous_name(&self, callback: AdminAddPlayerPreviousNameCallbackId);
}

impl admin_add_player_previous_name for super::RemoteReducers {
    fn admin_add_player_previous_name(&self, identity: String,
name: String,
) -> __sdk::Result<()> {
        self.imp.call_reducer("admin_add_player_previous_name", AdminAddPlayerPreviousNameArgs { identity, name,  })
    }
    fn on_admin_add_player_previous_name(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String, ) + Send + 'static,
    ) -> AdminAddPlayerPreviousNameCallbackId {
        AdminAddPlayerPreviousNameCallbackId(self.imp.on_reducer(
            "admin_add_player_previous_name",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event: __sdk::ReducerEvent {
                        reducer: super::Reducer::AdminAddPlayerPreviousName {
                            identity, name, 
                        },
                        ..
                    },
                    ..
                } = ctx else { unreachable!() };
                callback(ctx, identity, name, )
            }),
        ))
    }
    fn remove_on_admin_add_player_previous_name(&self, callback: AdminAddPlayerPreviousNameCallbackId) {
        self.imp.remove_on_reducer("admin_add_player_previous_name", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `admin_add_player_previous_name`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_admin_add_player_previous_name {
    /// Set the call-reducer flags for the reducer `admin_add_player_previous_name` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn admin_add_player_previous_name(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_admin_add_player_previous_name for super::SetReducerFlags {
    fn admin_add_player_previous_name(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("admin_add_player_previous_name", flags);
    }
}

