// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminPopulateEmpireNamesArgs {
    pub identity_empire_name_row: String,
}

impl From<AdminPopulateEmpireNamesArgs> for super::Reducer {
    fn from(args: AdminPopulateEmpireNamesArgs) -> Self {
        Self::AdminPopulateEmpireNames {
            identity_empire_name_row: args.identity_empire_name_row,
}
}
}

impl __sdk::InModule for AdminPopulateEmpireNamesArgs {
    type Module = super::RemoteModule;
}

pub struct AdminPopulateEmpireNamesCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_populate_empire_names`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_populate_empire_names {
    /// Request that the remote module invoke the reducer `admin_populate_empire_names` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_admin_populate_empire_names`] callbacks.
    fn admin_populate_empire_names(&self, identity_empire_name_row: String,
) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `admin_populate_empire_names`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AdminPopulateEmpireNamesCallbackId`] can be passed to [`Self::remove_on_admin_populate_empire_names`]
    /// to cancel the callback.
    fn on_admin_populate_empire_names(&self, callback: impl FnMut(&super::ReducerEventContext, &String, ) + Send + 'static) -> AdminPopulateEmpireNamesCallbackId;
    /// Cancel a callback previously registered by [`Self::on_admin_populate_empire_names`],
    /// causing it not to run in the future.
    fn remove_on_admin_populate_empire_names(&self, callback: AdminPopulateEmpireNamesCallbackId);
}

impl admin_populate_empire_names for super::RemoteReducers {
    fn admin_populate_empire_names(&self, identity_empire_name_row: String,
) -> __sdk::Result<()> {
        self.imp.call_reducer("admin_populate_empire_names", AdminPopulateEmpireNamesArgs { identity_empire_name_row,  })
    }
    fn on_admin_populate_empire_names(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, ) + Send + 'static,
    ) -> AdminPopulateEmpireNamesCallbackId {
        AdminPopulateEmpireNamesCallbackId(self.imp.on_reducer(
            "admin_populate_empire_names",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event: __sdk::ReducerEvent {
                        reducer: super::Reducer::AdminPopulateEmpireNames {
                            identity_empire_name_row, 
                        },
                        ..
                    },
                    ..
                } = ctx else { unreachable!() };
                callback(ctx, identity_empire_name_row, )
            }),
        ))
    }
    fn remove_on_admin_populate_empire_names(&self, callback: AdminPopulateEmpireNamesCallbackId) {
        self.imp.remove_on_reducer("admin_populate_empire_names", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `admin_populate_empire_names`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_admin_populate_empire_names {
    /// Set the call-reducer flags for the reducer `admin_populate_empire_names` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn admin_populate_empire_names(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_admin_populate_empire_names for super::SetReducerFlags {
    fn admin_populate_empire_names(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("admin_populate_empire_names", flags);
    }
}

