// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminRemoveModerationViolationArgs {
    pub violation_type: u8,
}

impl From<AdminRemoveModerationViolationArgs> for super::Reducer {
    fn from(args: AdminRemoveModerationViolationArgs) -> Self {
        Self::AdminRemoveModerationViolation {
            violation_type: args.violation_type,
}
}
}

impl __sdk::InModule for AdminRemoveModerationViolationArgs {
    type Module = super::RemoteModule;
}

pub struct AdminRemoveModerationViolationCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_remove_moderation_violation`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_remove_moderation_violation {
    /// Request that the remote module invoke the reducer `admin_remove_moderation_violation` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_admin_remove_moderation_violation`] callbacks.
    fn admin_remove_moderation_violation(&self, violation_type: u8,
) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `admin_remove_moderation_violation`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AdminRemoveModerationViolationCallbackId`] can be passed to [`Self::remove_on_admin_remove_moderation_violation`]
    /// to cancel the callback.
    fn on_admin_remove_moderation_violation(&self, callback: impl FnMut(&super::ReducerEventContext, &u8, ) + Send + 'static) -> AdminRemoveModerationViolationCallbackId;
    /// Cancel a callback previously registered by [`Self::on_admin_remove_moderation_violation`],
    /// causing it not to run in the future.
    fn remove_on_admin_remove_moderation_violation(&self, callback: AdminRemoveModerationViolationCallbackId);
}

impl admin_remove_moderation_violation for super::RemoteReducers {
    fn admin_remove_moderation_violation(&self, violation_type: u8,
) -> __sdk::Result<()> {
        self.imp.call_reducer("admin_remove_moderation_violation", AdminRemoveModerationViolationArgs { violation_type,  })
    }
    fn on_admin_remove_moderation_violation(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u8, ) + Send + 'static,
    ) -> AdminRemoveModerationViolationCallbackId {
        AdminRemoveModerationViolationCallbackId(self.imp.on_reducer(
            "admin_remove_moderation_violation",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event: __sdk::ReducerEvent {
                        reducer: super::Reducer::AdminRemoveModerationViolation {
                            violation_type, 
                        },
                        ..
                    },
                    ..
                } = ctx else { unreachable!() };
                callback(ctx, violation_type, )
            }),
        ))
    }
    fn remove_on_admin_remove_moderation_violation(&self, callback: AdminRemoveModerationViolationCallbackId) {
        self.imp.remove_on_reducer("admin_remove_moderation_violation", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `admin_remove_moderation_violation`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_admin_remove_moderation_violation {
    /// Set the call-reducer flags for the reducer `admin_remove_moderation_violation` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn admin_remove_moderation_violation(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_admin_remove_moderation_violation for super::SetReducerFlags {
    fn admin_remove_moderation_violation(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("admin_remove_moderation_violation", flags);
    }
}

