// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminChangeEmpireEmblemArgs {
    pub empire_entity_id: u64,
    pub icon_id: i32,
    pub shape_id: i32,
    pub color_1_id: i32,
    pub color_2_id: i32,
}

impl From<AdminChangeEmpireEmblemArgs> for super::Reducer {
    fn from(args: AdminChangeEmpireEmblemArgs) -> Self {
        Self::AdminChangeEmpireEmblem {
            empire_entity_id: args.empire_entity_id,
            icon_id: args.icon_id,
            shape_id: args.shape_id,
            color_1_id: args.color_1_id,
            color_2_id: args.color_2_id,
}
}
}

impl __sdk::InModule for AdminChangeEmpireEmblemArgs {
    type Module = super::RemoteModule;
}

pub struct AdminChangeEmpireEmblemCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_change_empire_emblem`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_change_empire_emblem {
    /// Request that the remote module invoke the reducer `admin_change_empire_emblem` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_admin_change_empire_emblem`] callbacks.
    fn admin_change_empire_emblem(&self, empire_entity_id: u64,
icon_id: i32,
shape_id: i32,
color_1_id: i32,
color_2_id: i32,
) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `admin_change_empire_emblem`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AdminChangeEmpireEmblemCallbackId`] can be passed to [`Self::remove_on_admin_change_empire_emblem`]
    /// to cancel the callback.
    fn on_admin_change_empire_emblem(&self, callback: impl FnMut(&super::ReducerEventContext, &u64, &i32, &i32, &i32, &i32, ) + Send + 'static) -> AdminChangeEmpireEmblemCallbackId;
    /// Cancel a callback previously registered by [`Self::on_admin_change_empire_emblem`],
    /// causing it not to run in the future.
    fn remove_on_admin_change_empire_emblem(&self, callback: AdminChangeEmpireEmblemCallbackId);
}

impl admin_change_empire_emblem for super::RemoteReducers {
    fn admin_change_empire_emblem(&self, empire_entity_id: u64,
icon_id: i32,
shape_id: i32,
color_1_id: i32,
color_2_id: i32,
) -> __sdk::Result<()> {
        self.imp.call_reducer("admin_change_empire_emblem", AdminChangeEmpireEmblemArgs { empire_entity_id, icon_id, shape_id, color_1_id, color_2_id,  })
    }
    fn on_admin_change_empire_emblem(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &i32, &i32, &i32, &i32, ) + Send + 'static,
    ) -> AdminChangeEmpireEmblemCallbackId {
        AdminChangeEmpireEmblemCallbackId(self.imp.on_reducer(
            "admin_change_empire_emblem",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event: __sdk::ReducerEvent {
                        reducer: super::Reducer::AdminChangeEmpireEmblem {
                            empire_entity_id, icon_id, shape_id, color_1_id, color_2_id, 
                        },
                        ..
                    },
                    ..
                } = ctx else { unreachable!() };
                callback(ctx, empire_entity_id, icon_id, shape_id, color_1_id, color_2_id, )
            }),
        ))
    }
    fn remove_on_admin_change_empire_emblem(&self, callback: AdminChangeEmpireEmblemCallbackId) {
        self.imp.remove_on_reducer("admin_change_empire_emblem", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `admin_change_empire_emblem`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_admin_change_empire_emblem {
    /// Set the call-reducer flags for the reducer `admin_change_empire_emblem` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn admin_change_empire_emblem(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_admin_change_empire_emblem for super::SetReducerFlags {
    fn admin_change_empire_emblem(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("admin_change_empire_emblem", flags);
    }
}

