// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminRemoveReplacementTextArgs {
    pub text_type: u8,
}

impl From<AdminRemoveReplacementTextArgs> for super::Reducer {
    fn from(args: AdminRemoveReplacementTextArgs) -> Self {
        Self::AdminRemoveReplacementText {
            text_type: args.text_type,
}
}
}

impl __sdk::InModule for AdminRemoveReplacementTextArgs {
    type Module = super::RemoteModule;
}

pub struct AdminRemoveReplacementTextCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_remove_replacement_text`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_remove_replacement_text {
    /// Request that the remote module invoke the reducer `admin_remove_replacement_text` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_admin_remove_replacement_text`] callbacks.
    fn admin_remove_replacement_text(&self, text_type: u8,
) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `admin_remove_replacement_text`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AdminRemoveReplacementTextCallbackId`] can be passed to [`Self::remove_on_admin_remove_replacement_text`]
    /// to cancel the callback.
    fn on_admin_remove_replacement_text(&self, callback: impl FnMut(&super::ReducerEventContext, &u8, ) + Send + 'static) -> AdminRemoveReplacementTextCallbackId;
    /// Cancel a callback previously registered by [`Self::on_admin_remove_replacement_text`],
    /// causing it not to run in the future.
    fn remove_on_admin_remove_replacement_text(&self, callback: AdminRemoveReplacementTextCallbackId);
}

impl admin_remove_replacement_text for super::RemoteReducers {
    fn admin_remove_replacement_text(&self, text_type: u8,
) -> __sdk::Result<()> {
        self.imp.call_reducer("admin_remove_replacement_text", AdminRemoveReplacementTextArgs { text_type,  })
    }
    fn on_admin_remove_replacement_text(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u8, ) + Send + 'static,
    ) -> AdminRemoveReplacementTextCallbackId {
        AdminRemoveReplacementTextCallbackId(self.imp.on_reducer(
            "admin_remove_replacement_text",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event: __sdk::ReducerEvent {
                        reducer: super::Reducer::AdminRemoveReplacementText {
                            text_type, 
                        },
                        ..
                    },
                    ..
                } = ctx else { unreachable!() };
                callback(ctx, text_type, )
            }),
        ))
    }
    fn remove_on_admin_remove_replacement_text(&self, callback: AdminRemoveReplacementTextCallbackId) {
        self.imp.remove_on_reducer("admin_remove_replacement_text", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `admin_remove_replacement_text`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_admin_remove_replacement_text {
    /// Set the call-reducer flags for the reducer `admin_remove_replacement_text` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn admin_remove_replacement_text(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_admin_remove_replacement_text for super::SetReducerFlags {
    fn admin_remove_replacement_text(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("admin_remove_replacement_text", flags);
    }
}

