// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminReplaceIdentityArgs {
    pub old_identity: String,
    pub new_identity: String,
}

impl From<AdminReplaceIdentityArgs> for super::Reducer {
    fn from(args: AdminReplaceIdentityArgs) -> Self {
        Self::AdminReplaceIdentity {
            old_identity: args.old_identity,
            new_identity: args.new_identity,
}
}
}

impl __sdk::InModule for AdminReplaceIdentityArgs {
    type Module = super::RemoteModule;
}

pub struct AdminReplaceIdentityCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_replace_identity`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_replace_identity {
    /// Request that the remote module invoke the reducer `admin_replace_identity` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_admin_replace_identity`] callbacks.
    fn admin_replace_identity(&self, old_identity: String,
new_identity: String,
) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `admin_replace_identity`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AdminReplaceIdentityCallbackId`] can be passed to [`Self::remove_on_admin_replace_identity`]
    /// to cancel the callback.
    fn on_admin_replace_identity(&self, callback: impl FnMut(&super::ReducerEventContext, &String, &String, ) + Send + 'static) -> AdminReplaceIdentityCallbackId;
    /// Cancel a callback previously registered by [`Self::on_admin_replace_identity`],
    /// causing it not to run in the future.
    fn remove_on_admin_replace_identity(&self, callback: AdminReplaceIdentityCallbackId);
}

impl admin_replace_identity for super::RemoteReducers {
    fn admin_replace_identity(&self, old_identity: String,
new_identity: String,
) -> __sdk::Result<()> {
        self.imp.call_reducer("admin_replace_identity", AdminReplaceIdentityArgs { old_identity, new_identity,  })
    }
    fn on_admin_replace_identity(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String, ) + Send + 'static,
    ) -> AdminReplaceIdentityCallbackId {
        AdminReplaceIdentityCallbackId(self.imp.on_reducer(
            "admin_replace_identity",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event: __sdk::ReducerEvent {
                        reducer: super::Reducer::AdminReplaceIdentity {
                            old_identity, new_identity, 
                        },
                        ..
                    },
                    ..
                } = ctx else { unreachable!() };
                callback(ctx, old_identity, new_identity, )
            }),
        ))
    }
    fn remove_on_admin_replace_identity(&self, callback: AdminReplaceIdentityCallbackId) {
        self.imp.remove_on_reducer("admin_replace_identity", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `admin_replace_identity`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_admin_replace_identity {
    /// Set the call-reducer flags for the reducer `admin_replace_identity` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn admin_replace_identity(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_admin_replace_identity for super::SetReducerFlags {
    fn admin_replace_identity(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("admin_replace_identity", flags);
    }
}

