// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BlockedPlayerState {
    pub owner_entity_id: u64,
    pub blocked_entity_id: u64,
}


impl __sdk::InModule for BlockedPlayerState {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `BlockedPlayerState`.
///
/// Provides typed access to columns for query building.
pub struct BlockedPlayerStateCols {
    pub owner_entity_id: __sdk::__query_builder::Col<BlockedPlayerState, u64>,
    pub blocked_entity_id: __sdk::__query_builder::Col<BlockedPlayerState, u64>,
}

impl __sdk::__query_builder::HasCols for BlockedPlayerState {
    type Cols = BlockedPlayerStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BlockedPlayerStateCols {
            owner_entity_id: __sdk::__query_builder::Col::new(table_name, "owner_entity_id"),
            blocked_entity_id: __sdk::__query_builder::Col::new(table_name, "blocked_entity_id"),

        }
    }
}

/// Indexed column accessor struct for the table `BlockedPlayerState`.
///
/// Provides typed access to indexed columns for query building.
pub struct BlockedPlayerStateIxCols {
    pub blocked_entity_id: __sdk::__query_builder::IxCol<BlockedPlayerState, u64>,
    pub owner_entity_id: __sdk::__query_builder::IxCol<BlockedPlayerState, u64>,
}

impl __sdk::__query_builder::HasIxCols for BlockedPlayerState {
    type IxCols = BlockedPlayerStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BlockedPlayerStateIxCols {
            blocked_entity_id: __sdk::__query_builder::IxCol::new(table_name, "blocked_entity_id"),
            owner_entity_id: __sdk::__query_builder::IxCol::new(table_name, "owner_entity_id"),

        }
    }
}

