// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::player_chat_post_message_request_type::PlayerChatPostMessageRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ChatPostTargetedMessageArgs {
    pub request: PlayerChatPostMessageRequest,
}

impl From<ChatPostTargetedMessageArgs> for super::Reducer {
    fn from(args: ChatPostTargetedMessageArgs) -> Self {
        Self::ChatPostTargetedMessage {
            request: args.request,
}
}
}

impl __sdk::InModule for ChatPostTargetedMessageArgs {
    type Module = super::RemoteModule;
}

pub struct ChatPostTargetedMessageCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `chat_post_targeted_message`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait chat_post_targeted_message {
    /// Request that the remote module invoke the reducer `chat_post_targeted_message` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_chat_post_targeted_message`] callbacks.
    fn chat_post_targeted_message(&self, request: PlayerChatPostMessageRequest,
) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `chat_post_targeted_message`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ChatPostTargetedMessageCallbackId`] can be passed to [`Self::remove_on_chat_post_targeted_message`]
    /// to cancel the callback.
    fn on_chat_post_targeted_message(&self, callback: impl FnMut(&super::ReducerEventContext, &PlayerChatPostMessageRequest, ) + Send + 'static) -> ChatPostTargetedMessageCallbackId;
    /// Cancel a callback previously registered by [`Self::on_chat_post_targeted_message`],
    /// causing it not to run in the future.
    fn remove_on_chat_post_targeted_message(&self, callback: ChatPostTargetedMessageCallbackId);
}

impl chat_post_targeted_message for super::RemoteReducers {
    fn chat_post_targeted_message(&self, request: PlayerChatPostMessageRequest,
) -> __sdk::Result<()> {
        self.imp.call_reducer("chat_post_targeted_message", ChatPostTargetedMessageArgs { request,  })
    }
    fn on_chat_post_targeted_message(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &PlayerChatPostMessageRequest, ) + Send + 'static,
    ) -> ChatPostTargetedMessageCallbackId {
        ChatPostTargetedMessageCallbackId(self.imp.on_reducer(
            "chat_post_targeted_message",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event: __sdk::ReducerEvent {
                        reducer: super::Reducer::ChatPostTargetedMessage {
                            request, 
                        },
                        ..
                    },
                    ..
                } = ctx else { unreachable!() };
                callback(ctx, request, )
            }),
        ))
    }
    fn remove_on_chat_post_targeted_message(&self, callback: ChatPostTargetedMessageCallbackId) {
        self.imp.remove_on_reducer("chat_post_targeted_message", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `chat_post_targeted_message`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_chat_post_targeted_message {
    /// Set the call-reducer flags for the reducer `chat_post_targeted_message` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn chat_post_targeted_message(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_chat_post_targeted_message for super::SetReducerFlags {
    fn chat_post_targeted_message(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("chat_post_targeted_message", flags);
    }
}

