// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::chat_channel_visibility_type::ChatChannelVisibility;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateChatChannelArgs {
    pub name: String,
    pub description: String,
    pub visibility: ChatChannelVisibility,
}

impl From<CreateChatChannelArgs> for super::Reducer {
    fn from(args: CreateChatChannelArgs) -> Self {
        Self::CreateChatChannel {
            name: args.name,
            description: args.description,
            visibility: args.visibility,
}
}
}

impl __sdk::InModule for CreateChatChannelArgs {
    type Module = super::RemoteModule;
}

pub struct CreateChatChannelCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_chat_channel`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_chat_channel {
    /// Request that the remote module invoke the reducer `create_chat_channel` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_create_chat_channel`] callbacks.
    fn create_chat_channel(&self, name: String,
description: String,
visibility: ChatChannelVisibility,
) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `create_chat_channel`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CreateChatChannelCallbackId`] can be passed to [`Self::remove_on_create_chat_channel`]
    /// to cancel the callback.
    fn on_create_chat_channel(&self, callback: impl FnMut(&super::ReducerEventContext, &String, &String, &ChatChannelVisibility, ) + Send + 'static) -> CreateChatChannelCallbackId;
    /// Cancel a callback previously registered by [`Self::on_create_chat_channel`],
    /// causing it not to run in the future.
    fn remove_on_create_chat_channel(&self, callback: CreateChatChannelCallbackId);
}

impl create_chat_channel for super::RemoteReducers {
    fn create_chat_channel(&self, name: String,
description: String,
visibility: ChatChannelVisibility,
) -> __sdk::Result<()> {
        self.imp.call_reducer("create_chat_channel", CreateChatChannelArgs { name, description, visibility,  })
    }
    fn on_create_chat_channel(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String, &ChatChannelVisibility, ) + Send + 'static,
    ) -> CreateChatChannelCallbackId {
        CreateChatChannelCallbackId(self.imp.on_reducer(
            "create_chat_channel",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event: __sdk::ReducerEvent {
                        reducer: super::Reducer::CreateChatChannel {
                            name, description, visibility, 
                        },
                        ..
                    },
                    ..
                } = ctx else { unreachable!() };
                callback(ctx, name, description, visibility, )
            }),
        ))
    }
    fn remove_on_create_chat_channel(&self, callback: CreateChatChannelCallbackId) {
        self.imp.remove_on_reducer("create_chat_channel", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `create_chat_channel`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_create_chat_channel {
    /// Set the call-reducer flags for the reducer `create_chat_channel` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn create_chat_channel(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_create_chat_channel for super::SetReducerFlags {
    fn create_chat_channel(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("create_chat_channel", flags);
    }
}

