// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DirectMessageState {
    pub entity_id: u64,
    pub username: String,
    pub title_id: i32,
    pub sender_entity_id: u64,
    pub receiver_entity_id: u64,
    pub text: String,
    pub timestamp: i32,
    pub language_code: Option::<String>,
}


impl __sdk::InModule for DirectMessageState {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `DirectMessageState`.
///
/// Provides typed access to columns for query building.
pub struct DirectMessageStateCols {
    pub entity_id: __sdk::__query_builder::Col<DirectMessageState, u64>,
    pub username: __sdk::__query_builder::Col<DirectMessageState, String>,
    pub title_id: __sdk::__query_builder::Col<DirectMessageState, i32>,
    pub sender_entity_id: __sdk::__query_builder::Col<DirectMessageState, u64>,
    pub receiver_entity_id: __sdk::__query_builder::Col<DirectMessageState, u64>,
    pub text: __sdk::__query_builder::Col<DirectMessageState, String>,
    pub timestamp: __sdk::__query_builder::Col<DirectMessageState, i32>,
    pub language_code: __sdk::__query_builder::Col<DirectMessageState, Option::<String>>,
}

impl __sdk::__query_builder::HasCols for DirectMessageState {
    type Cols = DirectMessageStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DirectMessageStateCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            username: __sdk::__query_builder::Col::new(table_name, "username"),
            title_id: __sdk::__query_builder::Col::new(table_name, "title_id"),
            sender_entity_id: __sdk::__query_builder::Col::new(table_name, "sender_entity_id"),
            receiver_entity_id: __sdk::__query_builder::Col::new(table_name, "receiver_entity_id"),
            text: __sdk::__query_builder::Col::new(table_name, "text"),
            timestamp: __sdk::__query_builder::Col::new(table_name, "timestamp"),
            language_code: __sdk::__query_builder::Col::new(table_name, "language_code"),

        }
    }
}

/// Indexed column accessor struct for the table `DirectMessageState`.
///
/// Provides typed access to indexed columns for query building.
pub struct DirectMessageStateIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<DirectMessageState, u64>,
    pub receiver_entity_id: __sdk::__query_builder::IxCol<DirectMessageState, u64>,
    pub sender_entity_id: __sdk::__query_builder::IxCol<DirectMessageState, u64>,
}

impl __sdk::__query_builder::HasIxCols for DirectMessageState {
    type IxCols = DirectMessageStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DirectMessageStateIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            receiver_entity_id: __sdk::__query_builder::IxCol::new(table_name, "receiver_entity_id"),
            sender_entity_id: __sdk::__query_builder::IxCol::new(table_name, "sender_entity_id"),

        }
    }
}

