// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EmpireFoundryState {
    pub entity_id: u64,
    pub empire_entity_id: u64,
    pub hexite_capsules: i32,
    pub queued: i32,
    pub started: __sdk::Timestamp,
}


impl __sdk::InModule for EmpireFoundryState {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `EmpireFoundryState`.
///
/// Provides typed access to columns for query building.
pub struct EmpireFoundryStateCols {
    pub entity_id: __sdk::__query_builder::Col<EmpireFoundryState, u64>,
    pub empire_entity_id: __sdk::__query_builder::Col<EmpireFoundryState, u64>,
    pub hexite_capsules: __sdk::__query_builder::Col<EmpireFoundryState, i32>,
    pub queued: __sdk::__query_builder::Col<EmpireFoundryState, i32>,
    pub started: __sdk::__query_builder::Col<EmpireFoundryState, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for EmpireFoundryState {
    type Cols = EmpireFoundryStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EmpireFoundryStateCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            empire_entity_id: __sdk::__query_builder::Col::new(table_name, "empire_entity_id"),
            hexite_capsules: __sdk::__query_builder::Col::new(table_name, "hexite_capsules"),
            queued: __sdk::__query_builder::Col::new(table_name, "queued"),
            started: __sdk::__query_builder::Col::new(table_name, "started"),

        }
    }
}

/// Indexed column accessor struct for the table `EmpireFoundryState`.
///
/// Provides typed access to indexed columns for query building.
pub struct EmpireFoundryStateIxCols {
    pub empire_entity_id: __sdk::__query_builder::IxCol<EmpireFoundryState, u64>,
    pub entity_id: __sdk::__query_builder::IxCol<EmpireFoundryState, u64>,
}

impl __sdk::__query_builder::HasIxCols for EmpireFoundryState {
    type IxCols = EmpireFoundryStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EmpireFoundryStateIxCols {
            empire_entity_id: __sdk::__query_builder::IxCol::new(table_name, "empire_entity_id"),
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),

        }
    }
}

