// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EmpirePlayerLogState {
    pub entity_id: u64,
    pub empire_entity_id: u64,
    pub last_viewed: u64,
}


impl __sdk::InModule for EmpirePlayerLogState {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `EmpirePlayerLogState`.
///
/// Provides typed access to columns for query building.
pub struct EmpirePlayerLogStateCols {
    pub entity_id: __sdk::__query_builder::Col<EmpirePlayerLogState, u64>,
    pub empire_entity_id: __sdk::__query_builder::Col<EmpirePlayerLogState, u64>,
    pub last_viewed: __sdk::__query_builder::Col<EmpirePlayerLogState, u64>,
}

impl __sdk::__query_builder::HasCols for EmpirePlayerLogState {
    type Cols = EmpirePlayerLogStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EmpirePlayerLogStateCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            empire_entity_id: __sdk::__query_builder::Col::new(table_name, "empire_entity_id"),
            last_viewed: __sdk::__query_builder::Col::new(table_name, "last_viewed"),

        }
    }
}

/// Indexed column accessor struct for the table `EmpirePlayerLogState`.
///
/// Provides typed access to indexed columns for query building.
pub struct EmpirePlayerLogStateIxCols {
    pub empire_entity_id: __sdk::__query_builder::IxCol<EmpirePlayerLogState, u64>,
    pub entity_id: __sdk::__query_builder::IxCol<EmpirePlayerLogState, u64>,
}

impl __sdk::__query_builder::HasIxCols for EmpirePlayerLogState {
    type IxCols = EmpirePlayerLogStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EmpirePlayerLogStateIxCols {
            empire_entity_id: __sdk::__query_builder::IxCol::new(table_name, "empire_entity_id"),
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),

        }
    }
}

