// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EmpireSiegeEngineState {
    pub entity_id: u64,
    pub building_entity_id: u64,
}


impl __sdk::InModule for EmpireSiegeEngineState {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `EmpireSiegeEngineState`.
///
/// Provides typed access to columns for query building.
pub struct EmpireSiegeEngineStateCols {
    pub entity_id: __sdk::__query_builder::Col<EmpireSiegeEngineState, u64>,
    pub building_entity_id: __sdk::__query_builder::Col<EmpireSiegeEngineState, u64>,
}

impl __sdk::__query_builder::HasCols for EmpireSiegeEngineState {
    type Cols = EmpireSiegeEngineStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EmpireSiegeEngineStateCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            building_entity_id: __sdk::__query_builder::Col::new(table_name, "building_entity_id"),

        }
    }
}

/// Indexed column accessor struct for the table `EmpireSiegeEngineState`.
///
/// Provides typed access to indexed columns for query building.
pub struct EmpireSiegeEngineStateIxCols {
    pub building_entity_id: __sdk::__query_builder::IxCol<EmpireSiegeEngineState, u64>,
    pub entity_id: __sdk::__query_builder::IxCol<EmpireSiegeEngineState, u64>,
}

impl __sdk::__query_builder::HasIxCols for EmpireSiegeEngineState {
    type IxCols = EmpireSiegeEngineStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EmpireSiegeEngineStateIxCols {
            building_entity_id: __sdk::__query_builder::IxCol::new(table_name, "building_entity_id"),
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),

        }
    }
}

