// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::minimum_client_version_type::MinimumClientVersion;

/// Table handle for the table `minimum_client_version`.
///
/// Obtain a handle from the [`MinimumClientVersionTableAccess::minimum_client_version`] method on [`super::RemoteTables`],
/// like `ctx.db.minimum_client_version()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.minimum_client_version().on_insert(...)`.
pub struct MinimumClientVersionTableHandle<'ctx> {
    imp: __sdk::TableHandle<MinimumClientVersion>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `minimum_client_version`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MinimumClientVersionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MinimumClientVersionTableHandle`], which mediates access to the table `minimum_client_version`.
    fn minimum_client_version(&self) -> MinimumClientVersionTableHandle<'_>;
}

impl MinimumClientVersionTableAccess for super::RemoteTables {
    fn minimum_client_version(&self) -> MinimumClientVersionTableHandle<'_> {
        MinimumClientVersionTableHandle {
            imp: self.imp.get_table::<MinimumClientVersion>("minimum_client_version"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MinimumClientVersionInsertCallbackId(__sdk::CallbackId);
pub struct MinimumClientVersionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MinimumClientVersionTableHandle<'ctx> {
    type Row = MinimumClientVersion;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = MinimumClientVersion> + '_ { self.imp.iter() }

    type InsertCallbackId = MinimumClientVersionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MinimumClientVersionInsertCallbackId {
        MinimumClientVersionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MinimumClientVersionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MinimumClientVersionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MinimumClientVersionDeleteCallbackId {
        MinimumClientVersionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MinimumClientVersionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

        let _table = client_cache.get_or_make_table::<MinimumClientVersion>("minimum_client_version");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}
pub struct MinimumClientVersionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MinimumClientVersionTableHandle<'ctx> {
    type UpdateCallbackId = MinimumClientVersionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MinimumClientVersionUpdateCallbackId {
        MinimumClientVersionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MinimumClientVersionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}


#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<MinimumClientVersion>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<MinimumClientVersion>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        /// Access to the `entity_id` unique index on the table `minimum_client_version`,
        /// which allows point queries on the field of the same name
        /// via the [`MinimumClientVersionEntityIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.minimum_client_version().entity_id().find(...)`.
        pub struct MinimumClientVersionEntityIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<MinimumClientVersion, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> MinimumClientVersionTableHandle<'ctx> {
            /// Get a handle on the `entity_id` unique index on the table `minimum_client_version`.
            pub fn entity_id(&self) -> MinimumClientVersionEntityIdUnique<'ctx> {
                MinimumClientVersionEntityIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("entity_id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> MinimumClientVersionEntityIdUnique<'ctx> {
            /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<MinimumClientVersion> {
                self.imp.find(col_val)
            }
        }
        
        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `MinimumClientVersion`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait minimum_client_versionQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `MinimumClientVersion`.
            fn minimum_client_version(&self) -> __sdk::__query_builder::Table<MinimumClientVersion>;
        }

        impl minimum_client_versionQueryTableAccess for __sdk::QueryTableAccessor {
            fn minimum_client_version(&self) -> __sdk::__query_builder::Table<MinimumClientVersion> {
                __sdk::__query_builder::Table::new("minimum_client_version")
            }
        }

