// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MinimumClientVersion {
    pub entity_id: u64,
    pub platform: String,
    pub build_number: u32,
}


impl __sdk::InModule for MinimumClientVersion {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `MinimumClientVersion`.
///
/// Provides typed access to columns for query building.
pub struct MinimumClientVersionCols {
    pub entity_id: __sdk::__query_builder::Col<MinimumClientVersion, u64>,
    pub platform: __sdk::__query_builder::Col<MinimumClientVersion, String>,
    pub build_number: __sdk::__query_builder::Col<MinimumClientVersion, u32>,
}

impl __sdk::__query_builder::HasCols for MinimumClientVersion {
    type Cols = MinimumClientVersionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MinimumClientVersionCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            platform: __sdk::__query_builder::Col::new(table_name, "platform"),
            build_number: __sdk::__query_builder::Col::new(table_name, "build_number"),

        }
    }
}

/// Indexed column accessor struct for the table `MinimumClientVersion`.
///
/// Provides typed access to indexed columns for query building.
pub struct MinimumClientVersionIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<MinimumClientVersion, u64>,
    pub platform: __sdk::__query_builder::IxCol<MinimumClientVersion, String>,
}

impl __sdk::__query_builder::HasIxCols for MinimumClientVersion {
    type IxCols = MinimumClientVersionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MinimumClientVersionIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            platform: __sdk::__query_builder::IxCol::new(table_name, "platform"),

        }
    }
}

