// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ModReplacementTextState {
    pub text_type: u8,
    pub text: String,
}


impl __sdk::InModule for ModReplacementTextState {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `ModReplacementTextState`.
///
/// Provides typed access to columns for query building.
pub struct ModReplacementTextStateCols {
    pub text_type: __sdk::__query_builder::Col<ModReplacementTextState, u8>,
    pub text: __sdk::__query_builder::Col<ModReplacementTextState, String>,
}

impl __sdk::__query_builder::HasCols for ModReplacementTextState {
    type Cols = ModReplacementTextStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ModReplacementTextStateCols {
            text_type: __sdk::__query_builder::Col::new(table_name, "text_type"),
            text: __sdk::__query_builder::Col::new(table_name, "text"),

        }
    }
}

/// Indexed column accessor struct for the table `ModReplacementTextState`.
///
/// Provides typed access to indexed columns for query building.
pub struct ModReplacementTextStateIxCols {
    pub text_type: __sdk::__query_builder::IxCol<ModReplacementTextState, u8>,
}

impl __sdk::__query_builder::HasIxCols for ModReplacementTextState {
    type IxCols = ModReplacementTextStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ModReplacementTextStateIxCols {
            text_type: __sdk::__query_builder::IxCol::new(table_name, "text_type"),

        }
    }
}

