// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::mod_violation_state_type::ModViolationState;

/// Table handle for the table `mod_violation_state`.
///
/// Obtain a handle from the [`ModViolationStateTableAccess::mod_violation_state`] method on [`super::RemoteTables`],
/// like `ctx.db.mod_violation_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.mod_violation_state().on_insert(...)`.
pub struct ModViolationStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<ModViolationState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `mod_violation_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ModViolationStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ModViolationStateTableHandle`], which mediates access to the table `mod_violation_state`.
    fn mod_violation_state(&self) -> ModViolationStateTableHandle<'_>;
}

impl ModViolationStateTableAccess for super::RemoteTables {
    fn mod_violation_state(&self) -> ModViolationStateTableHandle<'_> {
        ModViolationStateTableHandle {
            imp: self.imp.get_table::<ModViolationState>("mod_violation_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ModViolationStateInsertCallbackId(__sdk::CallbackId);
pub struct ModViolationStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ModViolationStateTableHandle<'ctx> {
    type Row = ModViolationState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = ModViolationState> + '_ { self.imp.iter() }

    type InsertCallbackId = ModViolationStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ModViolationStateInsertCallbackId {
        ModViolationStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ModViolationStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ModViolationStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ModViolationStateDeleteCallbackId {
        ModViolationStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ModViolationStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

        let _table = client_cache.get_or_make_table::<ModViolationState>("mod_violation_state");
    _table.add_unique_constraint::<u8>("violation_type", |row| &row.violation_type);
}
pub struct ModViolationStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ModViolationStateTableHandle<'ctx> {
    type UpdateCallbackId = ModViolationStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ModViolationStateUpdateCallbackId {
        ModViolationStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ModViolationStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}


#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ModViolationState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<ModViolationState>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        /// Access to the `violation_type` unique index on the table `mod_violation_state`,
        /// which allows point queries on the field of the same name
        /// via the [`ModViolationStateViolationTypeUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.mod_violation_state().violation_type().find(...)`.
        pub struct ModViolationStateViolationTypeUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<ModViolationState, u8>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> ModViolationStateTableHandle<'ctx> {
            /// Get a handle on the `violation_type` unique index on the table `mod_violation_state`.
            pub fn violation_type(&self) -> ModViolationStateViolationTypeUnique<'ctx> {
                ModViolationStateViolationTypeUnique {
                    imp: self.imp.get_unique_constraint::<u8>("violation_type"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> ModViolationStateViolationTypeUnique<'ctx> {
            /// Find the subscribed row whose `violation_type` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u8) -> Option<ModViolationState> {
                self.imp.find(col_val)
            }
        }
        
        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `ModViolationState`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait mod_violation_stateQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `ModViolationState`.
            fn mod_violation_state(&self) -> __sdk::__query_builder::Table<ModViolationState>;
        }

        impl mod_violation_stateQueryTableAccess for __sdk::QueryTableAccessor {
            fn mod_violation_state(&self) -> __sdk::__query_builder::Table<ModViolationState> {
                __sdk::__query_builder::Table::new("mod_violation_state")
            }
        }

