// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::mod_enforcement_config_state_type::ModEnforcementConfigState;

/// Table handle for the table `mod_enforcement_config_state`.
///
/// Obtain a handle from the [`ModEnforcementConfigStateTableAccess::mod_enforcement_config_state`] method on [`super::RemoteTables`],
/// like `ctx.db.mod_enforcement_config_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.mod_enforcement_config_state().on_insert(...)`.
pub struct ModEnforcementConfigStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<ModEnforcementConfigState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `mod_enforcement_config_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ModEnforcementConfigStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ModEnforcementConfigStateTableHandle`], which mediates access to the table `mod_enforcement_config_state`.
    fn mod_enforcement_config_state(&self) -> ModEnforcementConfigStateTableHandle<'_>;
}

impl ModEnforcementConfigStateTableAccess for super::RemoteTables {
    fn mod_enforcement_config_state(&self) -> ModEnforcementConfigStateTableHandle<'_> {
        ModEnforcementConfigStateTableHandle {
            imp: self.imp.get_table::<ModEnforcementConfigState>("mod_enforcement_config_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ModEnforcementConfigStateInsertCallbackId(__sdk::CallbackId);
pub struct ModEnforcementConfigStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ModEnforcementConfigStateTableHandle<'ctx> {
    type Row = ModEnforcementConfigState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = ModEnforcementConfigState> + '_ { self.imp.iter() }

    type InsertCallbackId = ModEnforcementConfigStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ModEnforcementConfigStateInsertCallbackId {
        ModEnforcementConfigStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ModEnforcementConfigStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ModEnforcementConfigStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ModEnforcementConfigStateDeleteCallbackId {
        ModEnforcementConfigStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ModEnforcementConfigStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

        let _table = client_cache.get_or_make_table::<ModEnforcementConfigState>("mod_enforcement_config_state");
    _table.add_unique_constraint::<u8>("id", |row| &row.id);
}
pub struct ModEnforcementConfigStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ModEnforcementConfigStateTableHandle<'ctx> {
    type UpdateCallbackId = ModEnforcementConfigStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ModEnforcementConfigStateUpdateCallbackId {
        ModEnforcementConfigStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ModEnforcementConfigStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}


#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ModEnforcementConfigState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<ModEnforcementConfigState>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        /// Access to the `id` unique index on the table `mod_enforcement_config_state`,
        /// which allows point queries on the field of the same name
        /// via the [`ModEnforcementConfigStateIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.mod_enforcement_config_state().id().find(...)`.
        pub struct ModEnforcementConfigStateIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<ModEnforcementConfigState, u8>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> ModEnforcementConfigStateTableHandle<'ctx> {
            /// Get a handle on the `id` unique index on the table `mod_enforcement_config_state`.
            pub fn id(&self) -> ModEnforcementConfigStateIdUnique<'ctx> {
                ModEnforcementConfigStateIdUnique {
                    imp: self.imp.get_unique_constraint::<u8>("id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> ModEnforcementConfigStateIdUnique<'ctx> {
            /// Find the subscribed row whose `id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u8) -> Option<ModEnforcementConfigState> {
                self.imp.find(col_val)
            }
        }
        
        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `ModEnforcementConfigState`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait mod_enforcement_config_stateQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `ModEnforcementConfigState`.
            fn mod_enforcement_config_state(&self) -> __sdk::__query_builder::Table<ModEnforcementConfigState>;
        }

        impl mod_enforcement_config_stateQueryTableAccess for __sdk::QueryTableAccessor {
            fn mod_enforcement_config_state(&self) -> __sdk::__query_builder::Table<ModEnforcementConfigState> {
                __sdk::__query_builder::Table::new("mod_enforcement_config_state")
            }
        }

