// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ModConsequenceState {
    pub id: u64,
    pub point_threshold: i32,
    pub consequence_type: u8,
    pub duration: i32,
    pub flag_level_code: u8,
}


impl __sdk::InModule for ModConsequenceState {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `ModConsequenceState`.
///
/// Provides typed access to columns for query building.
pub struct ModConsequenceStateCols {
    pub id: __sdk::__query_builder::Col<ModConsequenceState, u64>,
    pub point_threshold: __sdk::__query_builder::Col<ModConsequenceState, i32>,
    pub consequence_type: __sdk::__query_builder::Col<ModConsequenceState, u8>,
    pub duration: __sdk::__query_builder::Col<ModConsequenceState, i32>,
    pub flag_level_code: __sdk::__query_builder::Col<ModConsequenceState, u8>,
}

impl __sdk::__query_builder::HasCols for ModConsequenceState {
    type Cols = ModConsequenceStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ModConsequenceStateCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            point_threshold: __sdk::__query_builder::Col::new(table_name, "point_threshold"),
            consequence_type: __sdk::__query_builder::Col::new(table_name, "consequence_type"),
            duration: __sdk::__query_builder::Col::new(table_name, "duration"),
            flag_level_code: __sdk::__query_builder::Col::new(table_name, "flag_level_code"),

        }
    }
}

/// Indexed column accessor struct for the table `ModConsequenceState`.
///
/// Provides typed access to indexed columns for query building.
pub struct ModConsequenceStateIxCols {
    pub id: __sdk::__query_builder::IxCol<ModConsequenceState, u64>,
}

impl __sdk::__query_builder::HasIxCols for ModConsequenceState {
    type IxCols = ModConsequenceStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ModConsequenceStateIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),

        }
    }
}

