// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::mod_report_config_state_type::ModReportConfigState;

/// Table handle for the table `mod_report_config_state`.
///
/// Obtain a handle from the [`ModReportConfigStateTableAccess::mod_report_config_state`] method on [`super::RemoteTables`],
/// like `ctx.db.mod_report_config_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.mod_report_config_state().on_insert(...)`.
pub struct ModReportConfigStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<ModReportConfigState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `mod_report_config_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ModReportConfigStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ModReportConfigStateTableHandle`], which mediates access to the table `mod_report_config_state`.
    fn mod_report_config_state(&self) -> ModReportConfigStateTableHandle<'_>;
}

impl ModReportConfigStateTableAccess for super::RemoteTables {
    fn mod_report_config_state(&self) -> ModReportConfigStateTableHandle<'_> {
        ModReportConfigStateTableHandle {
            imp: self.imp.get_table::<ModReportConfigState>("mod_report_config_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ModReportConfigStateInsertCallbackId(__sdk::CallbackId);
pub struct ModReportConfigStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ModReportConfigStateTableHandle<'ctx> {
    type Row = ModReportConfigState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = ModReportConfigState> + '_ { self.imp.iter() }

    type InsertCallbackId = ModReportConfigStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ModReportConfigStateInsertCallbackId {
        ModReportConfigStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ModReportConfigStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ModReportConfigStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ModReportConfigStateDeleteCallbackId {
        ModReportConfigStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ModReportConfigStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

        let _table = client_cache.get_or_make_table::<ModReportConfigState>("mod_report_config_state");
    _table.add_unique_constraint::<u8>("id", |row| &row.id);
}
pub struct ModReportConfigStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ModReportConfigStateTableHandle<'ctx> {
    type UpdateCallbackId = ModReportConfigStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ModReportConfigStateUpdateCallbackId {
        ModReportConfigStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ModReportConfigStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}


#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ModReportConfigState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<ModReportConfigState>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        /// Access to the `id` unique index on the table `mod_report_config_state`,
        /// which allows point queries on the field of the same name
        /// via the [`ModReportConfigStateIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.mod_report_config_state().id().find(...)`.
        pub struct ModReportConfigStateIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<ModReportConfigState, u8>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> ModReportConfigStateTableHandle<'ctx> {
            /// Get a handle on the `id` unique index on the table `mod_report_config_state`.
            pub fn id(&self) -> ModReportConfigStateIdUnique<'ctx> {
                ModReportConfigStateIdUnique {
                    imp: self.imp.get_unique_constraint::<u8>("id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> ModReportConfigStateIdUnique<'ctx> {
            /// Find the subscribed row whose `id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u8) -> Option<ModReportConfigState> {
                self.imp.find(col_val)
            }
        }
        
        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `ModReportConfigState`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait mod_report_config_stateQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `ModReportConfigState`.
            fn mod_report_config_state(&self) -> __sdk::__query_builder::Table<ModReportConfigState>;
        }

        impl mod_report_config_stateQueryTableAccess for __sdk::QueryTableAccessor {
            fn mod_report_config_state(&self) -> __sdk::__query_builder::Table<ModReportConfigState> {
                __sdk::__query_builder::Table::new("mod_report_config_state")
            }
        }

