// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct OfficialTranslators {
    pub lang: String,
    pub player_entity_id: u64,
}


impl __sdk::InModule for OfficialTranslators {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `OfficialTranslators`.
///
/// Provides typed access to columns for query building.
pub struct OfficialTranslatorsCols {
    pub lang: __sdk::__query_builder::Col<OfficialTranslators, String>,
    pub player_entity_id: __sdk::__query_builder::Col<OfficialTranslators, u64>,
}

impl __sdk::__query_builder::HasCols for OfficialTranslators {
    type Cols = OfficialTranslatorsCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        OfficialTranslatorsCols {
            lang: __sdk::__query_builder::Col::new(table_name, "lang"),
            player_entity_id: __sdk::__query_builder::Col::new(table_name, "player_entity_id"),

        }
    }
}

/// Indexed column accessor struct for the table `OfficialTranslators`.
///
/// Provides typed access to indexed columns for query building.
pub struct OfficialTranslatorsIxCols {
    pub player_entity_id: __sdk::__query_builder::IxCol<OfficialTranslators, u64>,
}

impl __sdk::__query_builder::HasIxCols for OfficialTranslators {
    type IxCols = OfficialTranslatorsIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        OfficialTranslatorsIxCols {
            player_entity_id: __sdk::__query_builder::IxCol::new(table_name, "player_entity_id"),

        }
    }
}

