// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerShardState {
    pub entity_id: u64,
    pub shards: u32,
    pub last_shard_claim: i32,
}


impl __sdk::InModule for PlayerShardState {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `PlayerShardState`.
///
/// Provides typed access to columns for query building.
pub struct PlayerShardStateCols {
    pub entity_id: __sdk::__query_builder::Col<PlayerShardState, u64>,
    pub shards: __sdk::__query_builder::Col<PlayerShardState, u32>,
    pub last_shard_claim: __sdk::__query_builder::Col<PlayerShardState, i32>,
}

impl __sdk::__query_builder::HasCols for PlayerShardState {
    type Cols = PlayerShardStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerShardStateCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            shards: __sdk::__query_builder::Col::new(table_name, "shards"),
            last_shard_claim: __sdk::__query_builder::Col::new(table_name, "last_shard_claim"),

        }
    }
}

/// Indexed column accessor struct for the table `PlayerShardState`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerShardStateIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<PlayerShardState, u64>,
}

impl __sdk::__query_builder::HasIxCols for PlayerShardState {
    type IxCols = PlayerShardStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerShardStateIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),

        }
    }
}

