// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PremiumPurchaseState {
    pub entity_id: u64,
    pub identity: __sdk::Identity,
    pub collectible_desc_ids: Option::<Vec::<i32>>,
    pub price: u32,
    pub timestamp: __sdk::Timestamp,
    pub processed: bool,
    pub quantity: u32,
}


impl __sdk::InModule for PremiumPurchaseState {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `PremiumPurchaseState`.
///
/// Provides typed access to columns for query building.
pub struct PremiumPurchaseStateCols {
    pub entity_id: __sdk::__query_builder::Col<PremiumPurchaseState, u64>,
    pub identity: __sdk::__query_builder::Col<PremiumPurchaseState, __sdk::Identity>,
    pub collectible_desc_ids: __sdk::__query_builder::Col<PremiumPurchaseState, Option::<Vec::<i32>>>,
    pub price: __sdk::__query_builder::Col<PremiumPurchaseState, u32>,
    pub timestamp: __sdk::__query_builder::Col<PremiumPurchaseState, __sdk::Timestamp>,
    pub processed: __sdk::__query_builder::Col<PremiumPurchaseState, bool>,
    pub quantity: __sdk::__query_builder::Col<PremiumPurchaseState, u32>,
}

impl __sdk::__query_builder::HasCols for PremiumPurchaseState {
    type Cols = PremiumPurchaseStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PremiumPurchaseStateCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            collectible_desc_ids: __sdk::__query_builder::Col::new(table_name, "collectible_desc_ids"),
            price: __sdk::__query_builder::Col::new(table_name, "price"),
            timestamp: __sdk::__query_builder::Col::new(table_name, "timestamp"),
            processed: __sdk::__query_builder::Col::new(table_name, "processed"),
            quantity: __sdk::__query_builder::Col::new(table_name, "quantity"),

        }
    }
}

/// Indexed column accessor struct for the table `PremiumPurchaseState`.
///
/// Provides typed access to indexed columns for query building.
pub struct PremiumPurchaseStateIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<PremiumPurchaseState, u64>,
}

impl __sdk::__query_builder::HasIxCols for PremiumPurchaseState {
    type IxCols = PremiumPurchaseStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PremiumPurchaseStateIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),

        }
    }
}

