// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::previous_player_skills_state_type::PreviousPlayerSkillsState;
use super::experience_stack_type::ExperienceStack;

/// Table handle for the table `previous_player_skills`.
///
/// Obtain a handle from the [`PreviousPlayerSkillsTableAccess::previous_player_skills`] method on [`super::RemoteTables`],
/// like `ctx.db.previous_player_skills()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.previous_player_skills().on_insert(...)`.
pub struct PreviousPlayerSkillsTableHandle<'ctx> {
    imp: __sdk::TableHandle<PreviousPlayerSkillsState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `previous_player_skills`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PreviousPlayerSkillsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PreviousPlayerSkillsTableHandle`], which mediates access to the table `previous_player_skills`.
    fn previous_player_skills(&self) -> PreviousPlayerSkillsTableHandle<'_>;
}

impl PreviousPlayerSkillsTableAccess for super::RemoteTables {
    fn previous_player_skills(&self) -> PreviousPlayerSkillsTableHandle<'_> {
        PreviousPlayerSkillsTableHandle {
            imp: self.imp.get_table::<PreviousPlayerSkillsState>("previous_player_skills"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PreviousPlayerSkillsInsertCallbackId(__sdk::CallbackId);
pub struct PreviousPlayerSkillsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PreviousPlayerSkillsTableHandle<'ctx> {
    type Row = PreviousPlayerSkillsState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = PreviousPlayerSkillsState> + '_ { self.imp.iter() }

    type InsertCallbackId = PreviousPlayerSkillsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PreviousPlayerSkillsInsertCallbackId {
        PreviousPlayerSkillsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PreviousPlayerSkillsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PreviousPlayerSkillsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PreviousPlayerSkillsDeleteCallbackId {
        PreviousPlayerSkillsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PreviousPlayerSkillsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

        let _table = client_cache.get_or_make_table::<PreviousPlayerSkillsState>("previous_player_skills");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PreviousPlayerSkillsState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<PreviousPlayerSkillsState>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `PreviousPlayerSkillsState`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait previous_player_skillsQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `PreviousPlayerSkillsState`.
            fn previous_player_skills(&self) -> __sdk::__query_builder::Table<PreviousPlayerSkillsState>;
        }

        impl previous_player_skillsQueryTableAccess for __sdk::QueryTableAccessor {
            fn previous_player_skills(&self) -> __sdk::__query_builder::Table<PreviousPlayerSkillsState> {
                __sdk::__query_builder::Table::new("previous_player_skills")
            }
        }

