// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RemoveChatChannelArgs {
    pub entity_id: u64,
}

impl From<RemoveChatChannelArgs> for super::Reducer {
    fn from(args: RemoveChatChannelArgs) -> Self {
        Self::RemoveChatChannel {
            entity_id: args.entity_id,
}
}
}

impl __sdk::InModule for RemoveChatChannelArgs {
    type Module = super::RemoteModule;
}

pub struct RemoveChatChannelCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `remove_chat_channel`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait remove_chat_channel {
    /// Request that the remote module invoke the reducer `remove_chat_channel` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_remove_chat_channel`] callbacks.
    fn remove_chat_channel(&self, entity_id: u64,
) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `remove_chat_channel`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RemoveChatChannelCallbackId`] can be passed to [`Self::remove_on_remove_chat_channel`]
    /// to cancel the callback.
    fn on_remove_chat_channel(&self, callback: impl FnMut(&super::ReducerEventContext, &u64, ) + Send + 'static) -> RemoveChatChannelCallbackId;
    /// Cancel a callback previously registered by [`Self::on_remove_chat_channel`],
    /// causing it not to run in the future.
    fn remove_on_remove_chat_channel(&self, callback: RemoveChatChannelCallbackId);
}

impl remove_chat_channel for super::RemoteReducers {
    fn remove_chat_channel(&self, entity_id: u64,
) -> __sdk::Result<()> {
        self.imp.call_reducer("remove_chat_channel", RemoveChatChannelArgs { entity_id,  })
    }
    fn on_remove_chat_channel(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, ) + Send + 'static,
    ) -> RemoveChatChannelCallbackId {
        RemoveChatChannelCallbackId(self.imp.on_reducer(
            "remove_chat_channel",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event: __sdk::ReducerEvent {
                        reducer: super::Reducer::RemoveChatChannel {
                            entity_id, 
                        },
                        ..
                    },
                    ..
                } = ctx else { unreachable!() };
                callback(ctx, entity_id, )
            }),
        ))
    }
    fn remove_on_remove_chat_channel(&self, callback: RemoveChatChannelCallbackId) {
        self.imp.remove_on_reducer("remove_chat_channel", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `remove_chat_channel`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_remove_chat_channel {
    /// Set the call-reducer flags for the reducer `remove_chat_channel` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn remove_chat_channel(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_remove_chat_channel for super::SetReducerFlags {
    fn remove_chat_channel(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("remove_chat_channel", flags);
    }
}

