// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EmpireDecayLoopTimerHandle : RemoteTableHandle<EventContext, EmpireDecayLoopTimer>
        {
            protected override string RemoteTableName => "empire_decay_loop_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EmpireDecayLoopTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(EmpireDecayLoopTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal EmpireDecayLoopTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(EmpireDecayLoopTimer row) => row.ScheduledId;
        }

        public readonly EmpireDecayLoopTimerHandle EmpireDecayLoopTimer;
    }

    public sealed class EmpireDecayLoopTimerCols
    {
        public global::SpacetimeDB.Col<EmpireDecayLoopTimer, ulong> ScheduledId { get; }
        public global::SpacetimeDB.Col<EmpireDecayLoopTimer, SpacetimeDB.ScheduleAt> ScheduledAt { get; }

        public EmpireDecayLoopTimerCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.Col<EmpireDecayLoopTimer, ulong>(tableName, "scheduled_id");
            ScheduledAt = new global::SpacetimeDB.Col<EmpireDecayLoopTimer, SpacetimeDB.ScheduleAt>(tableName, "scheduled_at");
        }
    }

    public sealed class EmpireDecayLoopTimerIxCols
    {
        public global::SpacetimeDB.IxCol<EmpireDecayLoopTimer, ulong> ScheduledId { get; }

        public EmpireDecayLoopTimerIxCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.IxCol<EmpireDecayLoopTimer, ulong>(tableName, "scheduled_id");
        }
    }
}
