// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EmpireSiegeLoopTimerHandle : RemoteTableHandle<EventContext, EmpireSiegeLoopTimer>
        {
            protected override string RemoteTableName => "empire_siege_loop_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EmpireSiegeLoopTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(EmpireSiegeLoopTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal EmpireSiegeLoopTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(EmpireSiegeLoopTimer row) => row.ScheduledId;
        }

        public readonly EmpireSiegeLoopTimerHandle EmpireSiegeLoopTimer;
    }

    public sealed class EmpireSiegeLoopTimerCols
    {
        public global::SpacetimeDB.Col<EmpireSiegeLoopTimer, ulong> ScheduledId { get; }
        public global::SpacetimeDB.Col<EmpireSiegeLoopTimer, SpacetimeDB.ScheduleAt> ScheduledAt { get; }
        public global::SpacetimeDB.Col<EmpireSiegeLoopTimer, bool> FirstTick { get; }

        public EmpireSiegeLoopTimerCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.Col<EmpireSiegeLoopTimer, ulong>(tableName, "scheduled_id");
            ScheduledAt = new global::SpacetimeDB.Col<EmpireSiegeLoopTimer, SpacetimeDB.ScheduleAt>(tableName, "scheduled_at");
            FirstTick = new global::SpacetimeDB.Col<EmpireSiegeLoopTimer, bool>(tableName, "first_tick");
        }
    }

    public sealed class EmpireSiegeLoopTimerIxCols
    {
        public global::SpacetimeDB.IxCol<EmpireSiegeLoopTimer, ulong> ScheduledId { get; }

        public EmpireSiegeLoopTimerIxCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.IxCol<EmpireSiegeLoopTimer, ulong>(tableName, "scheduled_id");
        }
    }
}
