// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EmpirePlayerLogStateHandle : RemoteTableHandle<EventContext, EmpirePlayerLogState>
        {
            protected override string RemoteTableName => "empire_player_log_state";

            public sealed class EmpireEntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(EmpirePlayerLogState row) => row.EmpireEntityId;

                public EmpireEntityIdIndex(EmpirePlayerLogStateHandle table) : base(table) { }
            }

            public readonly EmpireEntityIdIndex EmpireEntityId;

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EmpirePlayerLogState row) => row.EntityId;

                public EntityIdUniqueIndex(EmpirePlayerLogStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal EmpirePlayerLogStateHandle(DbConnection conn) : base(conn)
            {
                EmpireEntityId = new(this);
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(EmpirePlayerLogState row) => row.EntityId;
        }

        public readonly EmpirePlayerLogStateHandle EmpirePlayerLogState;
    }

    public sealed class EmpirePlayerLogStateCols
    {
        public global::SpacetimeDB.Col<EmpirePlayerLogState, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<EmpirePlayerLogState, ulong> EmpireEntityId { get; }
        public global::SpacetimeDB.Col<EmpirePlayerLogState, ulong> LastViewed { get; }

        public EmpirePlayerLogStateCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<EmpirePlayerLogState, ulong>(tableName, "entity_id");
            EmpireEntityId = new global::SpacetimeDB.Col<EmpirePlayerLogState, ulong>(tableName, "empire_entity_id");
            LastViewed = new global::SpacetimeDB.Col<EmpirePlayerLogState, ulong>(tableName, "last_viewed");
        }
    }

    public sealed class EmpirePlayerLogStateIxCols
    {
        public global::SpacetimeDB.IxCol<EmpirePlayerLogState, ulong> EntityId { get; }
        public global::SpacetimeDB.IxCol<EmpirePlayerLogState, ulong> EmpireEntityId { get; }

        public EmpirePlayerLogStateIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<EmpirePlayerLogState, ulong>(tableName, "entity_id");
            EmpireEntityId = new global::SpacetimeDB.IxCol<EmpirePlayerLogState, ulong>(tableName, "empire_entity_id");
        }
    }
}
