// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EmpireDirectiveStateHandle : RemoteTableHandle<EventContext, EmpireDirectiveState>
        {
            protected override string RemoteTableName => "empire_directive_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EmpireDirectiveState row) => row.EntityId;

                public EntityIdUniqueIndex(EmpireDirectiveStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal EmpireDirectiveStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(EmpireDirectiveState row) => row.EntityId;
        }

        public readonly EmpireDirectiveStateHandle EmpireDirectiveState;
    }

    public sealed class EmpireDirectiveStateCols
    {
        public global::SpacetimeDB.Col<EmpireDirectiveState, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<EmpireDirectiveState, string> DirectiveMessage { get; }
        public global::SpacetimeDB.NullableCol<EmpireDirectiveState, SpacetimeDB.Timestamp> DirectiveMessageTimestamp { get; }

        public EmpireDirectiveStateCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<EmpireDirectiveState, ulong>(tableName, "entity_id");
            DirectiveMessage = new global::SpacetimeDB.Col<EmpireDirectiveState, string>(tableName, "directive_message");
            DirectiveMessageTimestamp = new global::SpacetimeDB.NullableCol<EmpireDirectiveState, SpacetimeDB.Timestamp>(tableName, "directive_message_timestamp");
        }
    }

    public sealed class EmpireDirectiveStateIxCols
    {
        public global::SpacetimeDB.IxCol<EmpireDirectiveState, ulong> EntityId { get; }

        public EmpireDirectiveStateIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<EmpireDirectiveState, ulong>(tableName, "entity_id");
        }
    }
}
