// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EmpireLogStateHandle : RemoteTableHandle<EventContext, EmpireLogState>
        {
            protected override string RemoteTableName => "empire_log_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EmpireLogState row) => row.EntityId;

                public EntityIdUniqueIndex(EmpireLogStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal EmpireLogStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(EmpireLogState row) => row.EntityId;
        }

        public readonly EmpireLogStateHandle EmpireLogState;
    }

    public sealed class EmpireLogStateCols
    {
        public global::SpacetimeDB.Col<EmpireLogState, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<EmpireLogState, ulong> LastPosted { get; }

        public EmpireLogStateCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<EmpireLogState, ulong>(tableName, "entity_id");
            LastPosted = new global::SpacetimeDB.Col<EmpireLogState, ulong>(tableName, "last_posted");
        }
    }

    public sealed class EmpireLogStateIxCols
    {
        public global::SpacetimeDB.IxCol<EmpireLogState, ulong> EntityId { get; }

        public EmpireLogStateIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<EmpireLogState, ulong>(tableName, "entity_id");
        }
    }
}
