// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GrantedHubItemStateHandle : RemoteTableHandle<EventContext, GrantedHubItemState>
        {
            protected override string RemoteTableName => "granted_hub_item_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(GrantedHubItemState row) => row.EntityId;

                public EntityIdUniqueIndex(GrantedHubItemStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class IdentityAndItemIdIndex : BTreeIndexBase<(SpacetimeDB.Identity Identity, int ItemId)>
            {
                protected override (SpacetimeDB.Identity Identity, int ItemId) GetKey(GrantedHubItemState row) => (row.Identity, row.ItemId);

                public IdentityAndItemIdIndex(GrantedHubItemStateHandle table) : base(table) { }
            }

            public readonly IdentityAndItemIdIndex IdentityAndItemId;

            internal GrantedHubItemStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
                IdentityAndItemId = new(this);
            }

            protected override object GetPrimaryKey(GrantedHubItemState row) => row.EntityId;
        }

        public readonly GrantedHubItemStateHandle GrantedHubItemState;
    }

    public sealed class GrantedHubItemStateCols
    {
        public global::SpacetimeDB.Col<GrantedHubItemState, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<GrantedHubItemState, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<GrantedHubItemState, HubItemType> ItemType { get; }
        public global::SpacetimeDB.Col<GrantedHubItemState, int> ItemId { get; }
        public global::SpacetimeDB.Col<GrantedHubItemState, uint> Balance { get; }

        public GrantedHubItemStateCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<GrantedHubItemState, ulong>(tableName, "entity_id");
            Identity = new global::SpacetimeDB.Col<GrantedHubItemState, SpacetimeDB.Identity>(tableName, "identity");
            ItemType = new global::SpacetimeDB.Col<GrantedHubItemState, HubItemType>(tableName, "item_type");
            ItemId = new global::SpacetimeDB.Col<GrantedHubItemState, int>(tableName, "item_id");
            Balance = new global::SpacetimeDB.Col<GrantedHubItemState, uint>(tableName, "balance");
        }
    }

    public sealed class GrantedHubItemStateIxCols
    {
        public global::SpacetimeDB.IxCol<GrantedHubItemState, ulong> EntityId { get; }
        public global::SpacetimeDB.IxCol<GrantedHubItemState, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.IxCol<GrantedHubItemState, int> ItemId { get; }

        public GrantedHubItemStateIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<GrantedHubItemState, ulong>(tableName, "entity_id");
            Identity = new global::SpacetimeDB.IxCol<GrantedHubItemState, SpacetimeDB.Identity>(tableName, "identity");
            ItemId = new global::SpacetimeDB.IxCol<GrantedHubItemState, int>(tableName, "item_id");
        }
    }
}
