// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MinimumClientVersionHandle : RemoteTableHandle<EventContext, MinimumClientVersion>
        {
            protected override string RemoteTableName => "minimum_client_version";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MinimumClientVersion row) => row.EntityId;

                public EntityIdUniqueIndex(MinimumClientVersionHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class PlatformIndex : BTreeIndexBase<string>
            {
                protected override string GetKey(MinimumClientVersion row) => row.Platform;

                public PlatformIndex(MinimumClientVersionHandle table) : base(table) { }
            }

            public readonly PlatformIndex Platform;

            internal MinimumClientVersionHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
                Platform = new(this);
            }

            protected override object GetPrimaryKey(MinimumClientVersion row) => row.EntityId;
        }

        public readonly MinimumClientVersionHandle MinimumClientVersion;
    }

    public sealed class MinimumClientVersionCols
    {
        public global::SpacetimeDB.Col<MinimumClientVersion, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<MinimumClientVersion, string> Platform { get; }
        public global::SpacetimeDB.Col<MinimumClientVersion, uint> BuildNumber { get; }

        public MinimumClientVersionCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<MinimumClientVersion, ulong>(tableName, "entity_id");
            Platform = new global::SpacetimeDB.Col<MinimumClientVersion, string>(tableName, "platform");
            BuildNumber = new global::SpacetimeDB.Col<MinimumClientVersion, uint>(tableName, "build_number");
        }
    }

    public sealed class MinimumClientVersionIxCols
    {
        public global::SpacetimeDB.IxCol<MinimumClientVersion, ulong> EntityId { get; }
        public global::SpacetimeDB.IxCol<MinimumClientVersion, string> Platform { get; }

        public MinimumClientVersionIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<MinimumClientVersion, ulong>(tableName, "entity_id");
            Platform = new global::SpacetimeDB.IxCol<MinimumClientVersion, string>(tableName, "platform");
        }
    }
}
