// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ModEnforcementConfigStateHandle : RemoteTableHandle<EventContext, ModEnforcementConfigState>
        {
            protected override string RemoteTableName => "mod_enforcement_config_state";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(ModEnforcementConfigState row) => row.Id;

                public IdUniqueIndex(ModEnforcementConfigStateHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ModEnforcementConfigStateHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ModEnforcementConfigState row) => row.Id;
        }

        public readonly ModEnforcementConfigStateHandle ModEnforcementConfigState;
    }

    public sealed class ModEnforcementConfigStateCols
    {
        public global::SpacetimeDB.Col<ModEnforcementConfigState, byte> Id { get; }
        public global::SpacetimeDB.Col<ModEnforcementConfigState, bool> ModerationEnforcementActive { get; }
        public global::SpacetimeDB.Col<ModEnforcementConfigState, bool> ChatModerationEnforcementActive { get; }
        public global::SpacetimeDB.Col<ModEnforcementConfigState, bool> UsernameModerationEnforcementActive { get; }
        public global::SpacetimeDB.Col<ModEnforcementConfigState, bool> EntityModerationEnforcementActive { get; }
        public global::SpacetimeDB.Col<ModEnforcementConfigState, byte> ModeratedEntityNameTypes { get; }
        public global::SpacetimeDB.Col<ModEnforcementConfigState, bool> CheckForLinks { get; }
        public global::SpacetimeDB.Col<ModEnforcementConfigState, bool> CheckForFlaggedWords { get; }
        public global::SpacetimeDB.Col<ModEnforcementConfigState, bool> CheckForContextFlaggedWords { get; }
        public global::SpacetimeDB.Col<ModEnforcementConfigState, bool> DeleteFlaggedMessages { get; }
        public global::SpacetimeDB.Col<ModEnforcementConfigState, bool> AllowLinksCwl { get; }
        public global::SpacetimeDB.Col<ModEnforcementConfigState, int> TitleIdCwl { get; }
        public global::SpacetimeDB.Col<ModEnforcementConfigState, int> HttpRequestMaxRetries { get; }

        public ModEnforcementConfigStateCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ModEnforcementConfigState, byte>(tableName, "id");
            ModerationEnforcementActive = new global::SpacetimeDB.Col<ModEnforcementConfigState, bool>(tableName, "moderation_enforcement_active");
            ChatModerationEnforcementActive = new global::SpacetimeDB.Col<ModEnforcementConfigState, bool>(tableName, "chat_moderation_enforcement_active");
            UsernameModerationEnforcementActive = new global::SpacetimeDB.Col<ModEnforcementConfigState, bool>(tableName, "username_moderation_enforcement_active");
            EntityModerationEnforcementActive = new global::SpacetimeDB.Col<ModEnforcementConfigState, bool>(tableName, "entity_moderation_enforcement_active");
            ModeratedEntityNameTypes = new global::SpacetimeDB.Col<ModEnforcementConfigState, byte>(tableName, "moderated_entity_name_types");
            CheckForLinks = new global::SpacetimeDB.Col<ModEnforcementConfigState, bool>(tableName, "check_for_links");
            CheckForFlaggedWords = new global::SpacetimeDB.Col<ModEnforcementConfigState, bool>(tableName, "check_for_flagged_words");
            CheckForContextFlaggedWords = new global::SpacetimeDB.Col<ModEnforcementConfigState, bool>(tableName, "check_for_context_flagged_words");
            DeleteFlaggedMessages = new global::SpacetimeDB.Col<ModEnforcementConfigState, bool>(tableName, "delete_flagged_messages");
            AllowLinksCwl = new global::SpacetimeDB.Col<ModEnforcementConfigState, bool>(tableName, "allow_links_cwl");
            TitleIdCwl = new global::SpacetimeDB.Col<ModEnforcementConfigState, int>(tableName, "title_id_cwl");
            HttpRequestMaxRetries = new global::SpacetimeDB.Col<ModEnforcementConfigState, int>(tableName, "http_request_max_retries");
        }
    }

    public sealed class ModEnforcementConfigStateIxCols
    {
        public global::SpacetimeDB.IxCol<ModEnforcementConfigState, byte> Id { get; }

        public ModEnforcementConfigStateIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ModEnforcementConfigState, byte>(tableName, "id");
        }
    }
}
