// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ModFlagLevelThresholdStateHandle : RemoteTableHandle<EventContext, ModFlagLevelThresholdState>
        {
            protected override string RemoteTableName => "mod_flag_level_threshold_state";

            public sealed class FlagLevelUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(ModFlagLevelThresholdState row) => row.FlagLevel;

                public FlagLevelUniqueIndex(ModFlagLevelThresholdStateHandle table) : base(table) { }
            }

            public readonly FlagLevelUniqueIndex FlagLevel;

            internal ModFlagLevelThresholdStateHandle(DbConnection conn) : base(conn)
            {
                FlagLevel = new(this);
            }

            protected override object GetPrimaryKey(ModFlagLevelThresholdState row) => row.FlagLevel;
        }

        public readonly ModFlagLevelThresholdStateHandle ModFlagLevelThresholdState;
    }

    public sealed class ModFlagLevelThresholdStateCols
    {
        public global::SpacetimeDB.Col<ModFlagLevelThresholdState, byte> FlagLevel { get; }
        public global::SpacetimeDB.Col<ModFlagLevelThresholdState, int> PointThreshold { get; }

        public ModFlagLevelThresholdStateCols(string tableName)
        {
            FlagLevel = new global::SpacetimeDB.Col<ModFlagLevelThresholdState, byte>(tableName, "flag_level");
            PointThreshold = new global::SpacetimeDB.Col<ModFlagLevelThresholdState, int>(tableName, "point_threshold");
        }
    }

    public sealed class ModFlagLevelThresholdStateIxCols
    {
        public global::SpacetimeDB.IxCol<ModFlagLevelThresholdState, byte> FlagLevel { get; }

        public ModFlagLevelThresholdStateIxCols(string tableName)
        {
            FlagLevel = new global::SpacetimeDB.IxCol<ModFlagLevelThresholdState, byte>(tableName, "flag_level");
        }
    }
}
