// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ModReportConfigStateHandle : RemoteTableHandle<EventContext, ModReportConfigState>
        {
            protected override string RemoteTableName => "mod_report_config_state";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(ModReportConfigState row) => row.Id;

                public IdUniqueIndex(ModReportConfigStateHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ModReportConfigStateHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ModReportConfigState row) => row.Id;
        }

        public readonly ModReportConfigStateHandle ModReportConfigState;
    }

    public sealed class ModReportConfigStateCols
    {
        public global::SpacetimeDB.Col<ModReportConfigState, byte> Id { get; }
        public global::SpacetimeDB.Col<ModReportConfigState, string> Model { get; }
        public global::SpacetimeDB.Col<ModReportConfigState, string> ModelDoubleCheck { get; }
        public global::SpacetimeDB.Col<ModReportConfigState, string> ModelTranslate { get; }
        public global::SpacetimeDB.Col<ModReportConfigState, float> OffenseCountWindowMinutes { get; }
        public global::SpacetimeDB.Col<ModReportConfigState, float> MinMinutesBetweenOffenses { get; }
        public global::SpacetimeDB.Col<ModReportConfigState, int> ReportableMessageMaxAge { get; }
        public global::SpacetimeDB.Col<ModReportConfigState, bool> CountAdminModerationActions { get; }
        public global::SpacetimeDB.Col<ModReportConfigState, string> DiscordWebhookUrlUserReports { get; }

        public ModReportConfigStateCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ModReportConfigState, byte>(tableName, "id");
            Model = new global::SpacetimeDB.Col<ModReportConfigState, string>(tableName, "model");
            ModelDoubleCheck = new global::SpacetimeDB.Col<ModReportConfigState, string>(tableName, "model_double_check");
            ModelTranslate = new global::SpacetimeDB.Col<ModReportConfigState, string>(tableName, "model_translate");
            OffenseCountWindowMinutes = new global::SpacetimeDB.Col<ModReportConfigState, float>(tableName, "offense_count_window_minutes");
            MinMinutesBetweenOffenses = new global::SpacetimeDB.Col<ModReportConfigState, float>(tableName, "min_minutes_between_offenses");
            ReportableMessageMaxAge = new global::SpacetimeDB.Col<ModReportConfigState, int>(tableName, "reportable_message_max_age");
            CountAdminModerationActions = new global::SpacetimeDB.Col<ModReportConfigState, bool>(tableName, "count_admin_moderation_actions");
            DiscordWebhookUrlUserReports = new global::SpacetimeDB.Col<ModReportConfigState, string>(tableName, "discord_webhook_url_user_reports");
        }
    }

    public sealed class ModReportConfigStateIxCols
    {
        public global::SpacetimeDB.IxCol<ModReportConfigState, byte> Id { get; }

        public ModReportConfigStateIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ModReportConfigState, byte>(tableName, "id");
        }
    }
}
