// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ModReplacementTextStateHandle : RemoteTableHandle<EventContext, ModReplacementTextState>
        {
            protected override string RemoteTableName => "mod_replacement_text_state";

            public sealed class TextTypeUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(ModReplacementTextState row) => row.TextType;

                public TextTypeUniqueIndex(ModReplacementTextStateHandle table) : base(table) { }
            }

            public readonly TextTypeUniqueIndex TextType;

            internal ModReplacementTextStateHandle(DbConnection conn) : base(conn)
            {
                TextType = new(this);
            }

            protected override object GetPrimaryKey(ModReplacementTextState row) => row.TextType;
        }

        public readonly ModReplacementTextStateHandle ModReplacementTextState;
    }

    public sealed class ModReplacementTextStateCols
    {
        public global::SpacetimeDB.Col<ModReplacementTextState, byte> TextType { get; }
        public global::SpacetimeDB.Col<ModReplacementTextState, string> Text { get; }

        public ModReplacementTextStateCols(string tableName)
        {
            TextType = new global::SpacetimeDB.Col<ModReplacementTextState, byte>(tableName, "text_type");
            Text = new global::SpacetimeDB.Col<ModReplacementTextState, string>(tableName, "text");
        }
    }

    public sealed class ModReplacementTextStateIxCols
    {
        public global::SpacetimeDB.IxCol<ModReplacementTextState, byte> TextType { get; }

        public ModReplacementTextStateIxCols(string tableName)
        {
            TextType = new global::SpacetimeDB.IxCol<ModReplacementTextState, byte>(tableName, "text_type");
        }
    }
}
