// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ModWordReplacementStateHandle : RemoteTableHandle<EventContext, ModWordReplacementState>
        {
            protected override string RemoteTableName => "mod_word_replacement_state";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ModWordReplacementState row) => row.Id;

                public IdUniqueIndex(ModWordReplacementStateHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ModWordReplacementStateHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ModWordReplacementState row) => row.Id;
        }

        public readonly ModWordReplacementStateHandle ModWordReplacementState;
    }

    public sealed class ModWordReplacementStateCols
    {
        public global::SpacetimeDB.Col<ModWordReplacementState, ulong> Id { get; }
        public global::SpacetimeDB.Col<ModWordReplacementState, System.Collections.Generic.List<string>> WordsToReplace { get; }
        public global::SpacetimeDB.Col<ModWordReplacementState, string> TextReplacement { get; }
        public global::SpacetimeDB.Col<ModWordReplacementState, bool> IsDeveloperUrlReplacement { get; }

        public ModWordReplacementStateCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ModWordReplacementState, ulong>(tableName, "id");
            WordsToReplace = new global::SpacetimeDB.Col<ModWordReplacementState, System.Collections.Generic.List<string>>(tableName, "words_to_replace");
            TextReplacement = new global::SpacetimeDB.Col<ModWordReplacementState, string>(tableName, "text_replacement");
            IsDeveloperUrlReplacement = new global::SpacetimeDB.Col<ModWordReplacementState, bool>(tableName, "is_developer_url_replacement");
        }
    }

    public sealed class ModWordReplacementStateIxCols
    {
        public global::SpacetimeDB.IxCol<ModWordReplacementState, ulong> Id { get; }

        public ModWordReplacementStateIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ModWordReplacementState, ulong>(tableName, "id");
        }
    }
}
