// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PreviousPlayerSkillsHandle : RemoteTableHandle<EventContext, PreviousPlayerSkillsState>
        {
            protected override string RemoteTableName => "previous_player_skills";

            internal PreviousPlayerSkillsHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly PreviousPlayerSkillsHandle PreviousPlayerSkills;
    }

    public sealed class PreviousPlayerSkillsCols
    {
        public global::SpacetimeDB.Col<PreviousPlayerSkillsState, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<PreviousPlayerSkillsState, System.Collections.Generic.List<ExperienceStack>> ExperienceStacks { get; }

        public PreviousPlayerSkillsCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<PreviousPlayerSkillsState, SpacetimeDB.Identity>(tableName, "identity");
            ExperienceStacks = new global::SpacetimeDB.Col<PreviousPlayerSkillsState, System.Collections.Generic.List<ExperienceStack>>(tableName, "experience_stacks");
        }
    }

    public sealed class PreviousPlayerSkillsIxCols
    {

        public PreviousPlayerSkillsIxCols(string tableName)
        {
        }
    }
}
