// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class UserCreationTimestampStateHandle : RemoteTableHandle<EventContext, UserCreationTimestampState>
        {
            protected override string RemoteTableName => "user_creation_timestamp_state";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(UserCreationTimestampState row) => row.Identity;

                public IdentityUniqueIndex(UserCreationTimestampStateHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal UserCreationTimestampStateHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(UserCreationTimestampState row) => row.Identity;
        }

        public readonly UserCreationTimestampStateHandle UserCreationTimestampState;
    }

    public sealed class UserCreationTimestampStateCols
    {
        public global::SpacetimeDB.Col<UserCreationTimestampState, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<UserCreationTimestampState, SpacetimeDB.Timestamp> Timestamp { get; }

        public UserCreationTimestampStateCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<UserCreationTimestampState, SpacetimeDB.Identity>(tableName, "identity");
            Timestamp = new global::SpacetimeDB.Col<UserCreationTimestampState, SpacetimeDB.Timestamp>(tableName, "timestamp");
        }
    }

    public sealed class UserCreationTimestampStateIxCols
    {
        public global::SpacetimeDB.IxCol<UserCreationTimestampState, SpacetimeDB.Identity> Identity { get; }

        public UserCreationTimestampStateIxCols(string tableName)
        {
            Identity = new global::SpacetimeDB.IxCol<UserCreationTimestampState, SpacetimeDB.Identity>(tableName, "identity");
        }
    }
}
