// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import OffsetCoordinatesFloat from "./offset_coordinates_float_type";


export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  targetEntityId: __t.u64().name("target_entity_id"),
  get currentDestination() {
    return OffsetCoordinatesFloat.name("current_destination");
  },
  get currentPosition() {
    return OffsetCoordinatesFloat.name("current_position");
  },
  get targetPosition() {
    return OffsetCoordinatesFloat.name("target_position");
  },
  dp: __t.f32(),
});
