// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `AbilityTypeEnum`.
const AbilityTypeEnum = __t.enum("AbilityTypeEnum", {_Unsupported: __t.unit(),
  Eat: __t.unit(),
  CombatAction: __t.unit(),
  AutoAttack: __t.unit(),
  SelfBuff: __t.unit(),
  Custom: __t.unit(),
  Prospecting: __t.unit(),
  Equip: __t.unit(),
  DeployableDeploy: __t.unit(),
  AddToToolbelt: __t.unit(),
  DeployableToggle: __t.unit(),
  Emote: __t.unit(),
});

export default AbilityTypeEnum;


