// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("ActionBarState", {
  entityId: __t.u64(),
  playerEntityId: __t.u64(),
  actionBarIndex: __t.u8(),
  localAbilityIndex: __t.u8(),
  abilityEntityId: __t.u64(),
});


