// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ItemStack from "./item_stack_type";


export default __t.object("ActionLogDataSpaceAllocator", {
  get item1() {
    return ItemStack;
  },
  get item2() {
    return ItemStack;
  },
  val1: __t.u64(),
  val2: __t.u64(),
});


