// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  scheduledId: __t.u64().primaryKey().name("scheduled_id"),
  scheduledAt: __t.scheduleAt().name("scheduled_at"),
  username: __t.string(),
  restorePosition: __t.bool().name("restore_position"),
  forceSignout: __t.bool().name("force_signout"),
  restoreAllDeployablesPositions: __t.bool().name("restore_all_deployables_positions"),
  storeDeployables: __t.bool().name("store_deployables"),
  clearCargo: __t.bool().name("clear_cargo"),
  clearItems: __t.bool().name("clear_items"),
  clearToolbelt: __t.bool().name("clear_toolbelt"),
});
