// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `AlertType`.
const AlertType = __t.enum("AlertType", {None: __t.unit(),
  EvictionWarning: __t.unit(),
  EvictionStatement: __t.unit(),
  DismissableTest: __t.unit(),
  OutOfSupplies: __t.unit(),
  OutOfSuppliesInOneTick: __t.unit(),
  OutOfSuppliesInTwelveTicks: __t.unit(),
  NewLostItems: __t.unit(),
  CoOwnerClaimOwnershipTransferIn24h: __t.unit(),
  CoOwnerClaimOwnershipTransfer: __t.unit(),
  OfficerClaimOwnershipTransfer: __t.unit(),
  MemberClaimOwnershipTransfer: __t.unit(),
});

export default AlertType;


