// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import EntityType from "./entity_type_type";


export default __t.object("AttackImpactTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  attackerEntityId: __t.u64(),
  defenderEntityId: __t.u64(),
  combatActionId: __t.i32(),
  get attackerType() {
    return EntityType;
  },
  get defenderType() {
    return EntityType;
  },
});


