// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import EntityType from "./entity_type_type";


export default __t.row({
  scheduledId: __t.u64().primaryKey().name("scheduled_id"),
  scheduledAt: __t.scheduleAt().name("scheduled_at"),
  attackerEntityId: __t.u64().name("attacker_entity_id"),
  defenderEntityId: __t.u64().name("defender_entity_id"),
  combatActionId: __t.i32().name("combat_action_id"),
  get attackerType() {
    return EntityType.name("attacker_type");
  },
  get defenderType() {
    return EntityType.name("defender_type");
  },
});
