// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("AuctionListingState", {
  entityId: __t.u64(),
  ownerEntityId: __t.u64(),
  claimEntityId: __t.u64(),
  itemId: __t.i32(),
  itemType: __t.i32(),
  priceThreshold: __t.i32(),
  quantity: __t.i32(),
  timestamp: __t.timestamp(),
  storedCoins: __t.i32(),
});


