// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `BuffCategory`.
const BuffCategory = __t.enum("BuffCategory", {None: __t.unit(),
  Generic: __t.unit(),
  Rested: __t.unit(),
  RezSicknessShortTerm: __t.unit(),
  RezSicknessLongTerm: __t.unit(),
  InnerLight: __t.unit(),
  Darkness: __t.unit(),
  CarryCargo: __t.unit(),
  Freezing: __t.unit(),
  Overheating: __t.unit(),
  FriendWarpDebuff: __t.unit(),
  Starving: __t.unit(),
  ElevatorSickness: __t.unit(),
  NearbyFlame: __t.unit(),
  Sprint: __t.unit(),
});

export default BuffCategory;


