// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import BuildingNicknameState from "./building_nickname_state_type";


// The tagged union or sum type for the algebraic type `BuildingNicknameStateOp`.
const BuildingNicknameStateOp = __t.enum("BuildingNicknameStateOp", {get Insert() {
    return BuildingNicknameState;
  },
  get Delete() {
    return BuildingNicknameState;
  },
});

export default BuildingNicknameStateOp;


