// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import BuildingFunction from "./building_function_type";
import FootprintTile from "./footprint_tile_type";
import BuildingInteractionLevel from "./building_interaction_level_type";


export default __t.object("BuildingDesc", {
  id: __t.i32(),
  get functions() {
    return __t.array(BuildingFunction);
  },
  name: __t.string(),
  description: __t.string(),
  restedBuffDuration: __t.i32(),
  lightRadius: __t.i32(),
  modelAssetName: __t.string(),
  iconAssetName: __t.string(),
  unenterable: __t.bool(),
  wilderness: __t.bool(),
  get footprint() {
    return __t.array(FootprintTile);
  },
  maxHealth: __t.i32(),
  ignoreDamage: __t.bool(),
  defenseLevel: __t.i32(),
  decay: __t.f32(),
  maintenance: __t.f32(),
  get buildPermission() {
    return BuildingInteractionLevel;
  },
  get interactPermission() {
    return BuildingInteractionLevel;
  },
  hasAction: __t.bool(),
  showInCompendium: __t.bool(),
  isRuins: __t.bool(),
  notDeconstructible: __t.bool(),
  destroyOnUnclaim: __t.bool(),
});


