// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import BuildingSpawnType from "./building_spawn_type_type";
import NpcType from "./npc_type_type";
import EnemyType from "./enemy_type_type";


export default __t.row({
  id: __t.i32().primaryKey(),
  buildingId: __t.i32().name("building_id"),
  x: __t.i32(),
  z: __t.i32(),
  direction: __t.i32(),
  get spawnType() {
    return BuildingSpawnType.name("spawn_type");
  },
  get travelerType() {
    return __t.option(NpcType).name("traveler_type");
  },
  get enemyType() {
    return __t.option(EnemyType).name("enemy_type");
  },
  spawnIds: __t.array(__t.i32()).name("spawn_ids"),
  respawnTimeMin: __t.f32().name("respawn_time_min"),
  respawnTimeMax: __t.f32().name("respawn_time_max"),
});
