// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import Rarity from "./rarity_type";


export default __t.row({
  id: __t.i32().primaryKey(),
  name: __t.string(),
  description: __t.string(),
  volume: __t.i32(),
  secondaryKnowledgeId: __t.i32().name("secondary_knowledge_id"),
  modelAssetName: __t.string().name("model_asset_name"),
  iconAssetName: __t.string().name("icon_asset_name"),
  carriedModelAssetName: __t.string().name("carried_model_asset_name"),
  pickUpAnimationStart: __t.string().name("pick_up_animation_start"),
  pickUpAnimationEnd: __t.string().name("pick_up_animation_end"),
  dropAnimationStart: __t.string().name("drop_animation_start"),
  dropAnimationEnd: __t.string().name("drop_animation_end"),
  pickUpTime: __t.f32().name("pick_up_time"),
  placeTime: __t.f32().name("place_time"),
  animatorState: __t.string().name("animator_state"),
  movementModifier: __t.f32().name("movement_modifier"),
  blocksPath: __t.bool().name("blocks_path"),
  onDestroyYieldCargos: __t.array(__t.i32()).name("on_destroy_yield_cargos"),
  despawnTime: __t.f32().name("despawn_time"),
  tier: __t.i32(),
  tag: __t.string(),
  get rarity() {
    return Rarity;
  },
  notPickupable: __t.bool().name("not_pickupable"),
});
