// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import Rarity from "./rarity_type";


export default __t.object("CargoDesc", {
  id: __t.i32(),
  name: __t.string(),
  description: __t.string(),
  volume: __t.i32(),
  secondaryKnowledgeId: __t.i32(),
  modelAssetName: __t.string(),
  iconAssetName: __t.string(),
  carriedModelAssetName: __t.string(),
  pickUpAnimationStart: __t.string(),
  pickUpAnimationEnd: __t.string(),
  dropAnimationStart: __t.string(),
  dropAnimationEnd: __t.string(),
  pickUpTime: __t.f32(),
  placeTime: __t.f32(),
  animatorState: __t.string(),
  movementModifier: __t.f32(),
  blocksPath: __t.bool(),
  onDestroyYieldCargos: __t.array(__t.i32()),
  despawnTime: __t.f32(),
  tier: __t.i32(),
  tag: __t.string(),
  get rarity() {
    return Rarity;
  },
  notPickupable: __t.bool(),
});


