// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `CharacterStatType`.
const CharacterStatType = __t.enum("CharacterStatType", {MaxHealth: __t.unit(),
  MaxStamina: __t.unit(),
  PassiveHealthRegenRate: __t.unit(),
  PassiveStaminaRegenRate: __t.unit(),
  MovementMultiplier: __t.unit(),
  SprintMultiplier: __t.unit(),
  SprintStaminaDrain: __t.unit(),
  Armor: __t.unit(),
  CooldownMultiplier: __t.unit(),
  HuntingWeaponPower: __t.unit(),
  Strength: __t.unit(),
  ColdProtection: __t.unit(),
  HeatProtection: __t.unit(),
  Evasion: __t.unit(),
  ToolbeltSlots: __t.unit(),
  CraftingSpeed: __t.unit(),
  GatheringSpeed: __t.unit(),
  BuildingSpeed: __t.unit(),
  SatiationRegenRate: __t.unit(),
  MaxSatiation: __t.unit(),
  DefenseLevel: __t.unit(),
  ForestrySpeed: __t.unit(),
  CarpentrySpeed: __t.unit(),
  MasonrySpeed: __t.unit(),
  MiningSpeed: __t.unit(),
  SmithingSpeed: __t.unit(),
  ScholarSpeed: __t.unit(),
  LeatherworkingSpeed: __t.unit(),
  HuntingSpeed: __t.unit(),
  TailoringSpeed: __t.unit(),
  FarmingSpeed: __t.unit(),
  FishingSpeed: __t.unit(),
  CookingSpeed: __t.unit(),
  ForagingSpeed: __t.unit(),
  ForestryPower: __t.unit(),
  CarpentryPower: __t.unit(),
  MasonryPower: __t.unit(),
  MiningPower: __t.unit(),
  SmithingPower: __t.unit(),
  ScholarPower: __t.unit(),
  LeatherworkingPower: __t.unit(),
  HuntingPower: __t.unit(),
  TailoringPower: __t.unit(),
  FarmingPower: __t.unit(),
  FishingPower: __t.unit(),
  CookingPower: __t.unit(),
  ForagingPower: __t.unit(),
  ActiveHealthRegenRate: __t.unit(),
  ActiveStaminaRegenRate: __t.unit(),
  ClimbProficiency: __t.unit(),
  ExperienceRate: __t.unit(),
  Accuracy: __t.unit(),
  MaxTeleportationEnergy: __t.unit(),
  TeleportationEnergyRegenRate: __t.unit(),
  ConstructionPower: __t.unit(),
});

export default CharacterStatType;


