// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("CharacterStatDesc", {
  statType: __t.i32(),
  name: __t.string(),
  value: __t.f32(),
  minValue: __t.f32(),
  maxValue: __t.f32(),
  suffix: __t.string(),
  desc: __t.string(),
});


