// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `ChatChannel`.
const ChatChannel = __t.enum("ChatChannel", {System: __t.unit(),
  Global: __t.unit(),
  Local: __t.unit(),
  Region: __t.unit(),
  Claim: __t.unit(),
  EmpirePublic: __t.unit(),
  EmpireInternal: __t.unit(),
  LookingForGroup: __t.unit(),
  Trade: __t.unit(),
});

export default ChatChannel;


