// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  username: __t.string(),
  titleId: __t.i32().name("title_id"),
  channelId: __t.i32().name("channel_id"),
  targetId: __t.u64().name("target_id"),
  text: __t.string(),
  timestamp: __t.i32(),
  ownerEntityId: __t.u64().name("owner_entity_id"),
});
