// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  claimEntityId: __t.u64().name("claim_entity_id"),
  remainingStock: __t.i32().name("remaining_stock"),
  requiredSkillId: __t.i32().name("required_skill_id"),
  requiredSkillLevel: __t.i32().name("required_skill_level"),
  requiredApproval: __t.bool().name("required_approval"),
});
