// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `ClaimTechType`.
const ClaimTechType = __t.enum("ClaimTechType", {Undefined: __t.unit(),
  TierUpgrade: __t.unit(),
  MemberCount: __t.unit(),
  MaxSupplies: __t.unit(),
  ClaimArea: __t.unit(),
  Settlement: __t.unit(),
  Forestry: __t.unit(),
  Carpentry: __t.unit(),
  Masonry: __t.unit(),
  Mining: __t.unit(),
  Smithing: __t.unit(),
  Scholar: __t.unit(),
  Leatherworking: __t.unit(),
  Hunting: __t.unit(),
  Tailoring: __t.unit(),
  Farming: __t.unit(),
  Fishing: __t.unit(),
  Foraging: __t.unit(),
  Empire: __t.unit(),
  TownBank: __t.unit(),
  LargeHouse: __t.unit(),
  TownMarket: __t.unit(),
});

export default ClaimTechType;


