// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ClaimState from "./claim_state_type";


// The tagged union or sum type for the algebraic type `ClaimStateOp`.
const ClaimStateOp = __t.enum("ClaimStateOp", {get Insert() {
    return ClaimState;
  },
  get Delete() {
    return ClaimState;
  },
});

export default ClaimStateOp;


