// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `CollectibleType`.
const CollectibleType = __t.enum("CollectibleType", {Default: __t.unit(),
  Hair: __t.unit(),
  Mask: __t.unit(),
  MaskPattern: __t.unit(),
  HairColor: __t.unit(),
  Nameplate: __t.unit(),
  BodyColor: __t.unit(),
  Emblem: __t.unit(),
  ClothesHead: __t.unit(),
  ClothesBelt: __t.unit(),
  ClothesTorso: __t.unit(),
  ClothesArms: __t.unit(),
  ClothesLegs: __t.unit(),
  ClothesFeet: __t.unit(),
  Deployable: __t.unit(),
  Title: __t.unit(),
  Crown: __t.unit(),
  Pet: __t.unit(),
  ClothesCape: __t.unit(),
  PremiumItem: __t.unit(),
  Emote: __t.unit(),
  HousingWalls: __t.unit(),
  HousingFloor: __t.unit(),
});

export default CollectibleType;


