// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ActionCooldown from "./action_cooldown_type";


export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  lastAttackedTimestamp: __t.u64().name("last_attacked_timestamp"),
  lastPerformedActionEntityId: __t.u64().name("last_performed_action_entity_id"),
  get globalCooldown() {
    return __t.option(ActionCooldown).name("global_cooldown");
  },
});
