// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import FootprintTile from "./footprint_tile_type";


export default __t.row({
  id: __t.i32().primaryKey(),
  get areaFootprint() {
    return __t.array(FootprintTile).name("area_footprint");
  },
  maxSecondaryTargets: __t.i32().name("max_secondary_targets"),
  secondaryTargetMultiplier: __t.f32().name("secondary_target_multiplier"),
});
