// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import BuffEffect from "./buff_effect_type";
import LevelRequirement from "./level_requirement_type";


export default __t.object("CombatActionDesc", {
  name: __t.string(),
  id: __t.i32(),
  learnedByPlayer: __t.bool(),
  range: __t.u32(),
  maxRange: __t.f32(),
  autoCast: __t.bool(),
  weaponTypeRequirements: __t.array(__t.i32()),
  leadInTime: __t.f32(),
  inactionTime: __t.f32(),
  canMoveDuringLeadIn: __t.bool(),
  cooldown: __t.f32(),
  globalCooldown: __t.f32(),
  ignoreGlobalCooldown: __t.bool(),
  strengthMultiplier: __t.f32(),
  accuracyMultiplier: __t.f32(),
  staminaUse: __t.f32(),
  weaponDurabilityLost: __t.i32(),
  get selfBuffs() {
    return __t.array(BuffEffect);
  },
  get targetBuffs() {
    return __t.array(BuffEffect);
  },
  get levelRequirement() {
    return __t.option(LevelRequirement);
  },
  iconAssetName: __t.string(),
  playerAnimationId: __t.i32(),
  npcAnimationName: __t.string(),
  hitVfx: __t.string(),
  projectileSpeed: __t.f32(),
  projectileVfx: __t.string(),
  description: __t.string(),
  selfThreatAgainstBuildings: __t.f32(),
  selfThreatAgainstEnemies: __t.f32(),
  baseThreat: __t.f32(),
  threatPerDamage: __t.f32(),
  isSelfTargeting: __t.bool(),
  isTauntAction: __t.bool(),
});


