// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import OffsetCoordinatesSmallMessage from "./offset_coordinates_small_message_type";


export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  get originalLocation() {
    return OffsetCoordinatesSmallMessage.name("original_location");
  },
  get crumbLocations() {
    return __t.array(OffsetCoordinatesSmallMessage).name("crumb_locations");
  },
  crumbRadiuses: __t.array(__t.i32()).name("crumb_radiuses"),
  get prizeLocation() {
    return OffsetCoordinatesSmallMessage.name("prize_location");
  },
  activeStep: __t.i32().name("active_step"),
  prizeEntityIds: __t.array(__t.u64()).name("prize_entity_ids"),
  joinRadius: __t.i32().name("join_radius"),
  cleanUpCounter: __t.i32().name("clean_up_counter"),
});
