// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  buildingId: __t.u64().name("building_id"),
  collapseRespawnTimestamp: __t.u64().name("collapse_respawn_timestamp"),
  rentEntityId: __t.u64().name("rent_entity_id"),
  claimEntityId: __t.u64().name("claim_entity_id"),
  entranceDimensionId: __t.u32().name("entrance_dimension_id"),
  isCollapsed: __t.bool().name("is_collapsed"),
});
