// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("ElevatorDesc", {
  buildingId: __t.i32(),
  maxCliffHeight: __t.u32(),
  speed: __t.f32(),
  usableWithDeployable: __t.bool(),
  topPlatformAddress: __t.string(),
  basketAddress: __t.string(),
  bottomPlatformAddress: __t.string(),
});


