// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import EmpirePlayerDataState from "./empire_player_data_state_type";


// The tagged union or sum type for the algebraic type `EmpirePlayerDataStateOp`.
const EmpirePlayerDataStateOp = __t.enum("EmpirePlayerDataStateOp", {get Insert() {
    return EmpirePlayerDataState;
  },
  get Delete() {
    return EmpirePlayerDataState;
  },
});

export default EmpirePlayerDataStateOp;


