// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import OffsetCoordinatesSmallMessage from "./offset_coordinates_small_message_type";
import EmpireOwnerType from "./empire_owner_type_type";


export default __t.object("EmpireState", {
  entityId: __t.u64(),
  capitalBuildingEntityId: __t.u64(),
  name: __t.string(),
  shardTreasury: __t.u32(),
  nobilityThreshold: __t.i32(),
  numClaims: __t.i32(),
  get location() {
    return OffsetCoordinatesSmallMessage;
  },
  empireCurrencyTreasury: __t.u32(),
  get ownerType() {
    return EmpireOwnerType;
  },
});


