// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import EmpireState from "./empire_state_type";


// The tagged union or sum type for the algebraic type `EmpireStateOp`.
const EmpireStateOp = __t.enum("EmpireStateOp", {get Insert() {
    return EmpireState;
  },
  get Delete() {
    return EmpireState;
  },
});

export default EmpireStateOp;


