// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import OffsetCoordinatesSmallMessage from "./offset_coordinates_small_message_type";
import EnemyType from "./enemy_type_type";


export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  get enemyType() {
    return EnemyType.name("enemy_type");
  },
  herdEntityId: __t.u64().name("herd_entity_id"),
  get herdLocation() {
    return OffsetCoordinatesSmallMessage.name("herd_location");
  },
});
