// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import OffsetCoordinatesSmallMessage from "./offset_coordinates_small_message_type";
import EnemyType from "./enemy_type_type";


export default __t.object("EnemyMobMonitorState", {
  entityId: __t.u64(),
  get enemyType() {
    return EnemyType;
  },
  herdEntityId: __t.u64(),
  get herdLocation() {
    return OffsetCoordinatesSmallMessage;
  },
});


