// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `EnemyType`.
const EnemyType = __t.enum("EnemyType", {None: __t.unit(),
  PracticeDummy: __t.unit(),
  GrassBird: __t.unit(),
  DesertBird: __t.unit(),
  SwampBird: __t.unit(),
  Goat: __t.unit(),
  MountainGoat: __t.unit(),
  DeerFemale: __t.unit(),
  DeerMale: __t.unit(),
  Elk: __t.unit(),
  BoarFemale: __t.unit(),
  BoarMale: __t.unit(),
  BoarElder: __t.unit(),
  PlainsOx: __t.unit(),
  TundraOx: __t.unit(),
  JungleLargeBird: __t.unit(),
  DesertLargeBird: __t.unit(),
  Jakyl: __t.unit(),
  AlphaJakyl: __t.unit(),
  KingJakyl: __t.unit(),
  RockCrab: __t.unit(),
  DesertCrab: __t.unit(),
  FrostCrab: __t.unit(),
  ForestToad: __t.unit(),
  SwampToad: __t.unit(),
  FrostToad: __t.unit(),
  Umbura: __t.unit(),
  AlphaUmbura: __t.unit(),
  KingUmbura: __t.unit(),
  Drone: __t.unit(),
  Soldier: __t.unit(),
  Queen: __t.unit(),
  Sentinel: __t.unit(),
  SentinelDungeonJakyl: __t.unit(),
  SentinelDungeonSkitch: __t.unit(),
  SentinelDungeonLargeJakyl: __t.unit(),
  CrabDungeonCrabBoss: __t.unit(),
  CrabDungeonCrabTrash: __t.unit(),
  SpiderDungeonEliteSpider: __t.unit(),
  SpiderDungeonSmallSpider: __t.unit(),
  SpiderDungeonSpiderNest: __t.unit(),
  EnragedAlphaJakyl: __t.unit(),
});

export default EnemyType;


