// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import EnemyType from "./enemy_type_type";
import EnemyStatus from "./enemy_status_type";


export default __t.object("EnemyState", {
  entityId: __t.u64(),
  herdEntityId: __t.u64(),
  direction: __t.i32(),
  get status() {
    return EnemyStatus;
  },
  lastRangedAttackTimestamp: __t.timestamp(),
  get enemyType() {
    return EnemyType;
  },
});


