// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import EnvironmentResistanceType from "./environment_resistance_type_type";


export default __t.object("EnvironmentDebuffDesc", {
  buffId: __t.i32(),
  get resistanceType() {
    return EnvironmentResistanceType;
  },
  resistanceLevel: __t.i32(),
  groundDamage: __t.i32(),
  waterDamage: __t.i32(),
  resistanceUnmetText: __t.string(),
  resistanceMetText: __t.string(),
});


