// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import LevelRequirement from "./level_requirement_type";
import ToolRequirement from "./tool_requirement_type";
import InputItemStack from "./input_item_stack_type";
import ExperienceStackF32 from "./experience_stack_f_32_type";
import ProbabilisticItemStack from "./probabilistic_item_stack_type";


export default __t.object("ExtractionRecipeDesc", {
  id: __t.i32(),
  resourceId: __t.i32(),
  cargoId: __t.i32(),
  discoveryTriggers: __t.array(__t.i32()),
  requiredKnowledges: __t.array(__t.i32()),
  blockingKnowledges: __t.array(__t.i32()),
  timeRequirement: __t.f32(),
  staminaRequirement: __t.f32(),
  toolDurabilityLost: __t.i32(),
  get extractedItemStacks() {
    return __t.array(ProbabilisticItemStack);
  },
  get consumedItemStacks() {
    return __t.array(InputItemStack);
  },
  range: __t.i32(),
  get toolRequirements() {
    return __t.array(ToolRequirement);
  },
  allowUseHands: __t.bool(),
  get levelRequirements() {
    return __t.array(LevelRequirement);
  },
  get experiencePerProgress() {
    return __t.array(ExperienceStackF32);
  },
  verbPhrase: __t.string(),
  toolMeshIndex: __t.i32(),
  recipePerformanceId: __t.i32(),
  empireRankRequirement: __t.option(__t.i32()),
  showInProgression: __t.bool(),
});


