// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import HexDirection from "./hex_direction_type";
import FloatHexTileMessage from "./float_hex_tile_message_type";
import ChunkCoordinatesMessage from "./chunk_coordinates_message_type";
import ClaimPermission from "./claim_permission_type";
import LargeHexTileMessage from "./large_hex_tile_message_type";
import TerrainCell from "./terrain_cell_type";
import ItemConversionLocationContext from "./item_conversion_location_context_type";


export default __t.row({
  get hexDirection() {
    return HexDirection.name("hex_direction");
  },
  get floatHexTile() {
    return FloatHexTileMessage.name("float_hex_tile");
  },
  get chunkCoordinatesMessage() {
    return ChunkCoordinatesMessage.name("chunk_coordinates_message");
  },
  get claimPermission() {
    return ClaimPermission.name("claim_permission");
  },
  get largeHexTileMessage() {
    return LargeHexTileMessage.name("large_hex_tile_message");
  },
  get terrainCell() {
    return TerrainCell.name("terrain_cell");
  },
  get itemConversionLocatinContext() {
    return ItemConversionLocationContext.name("item_conversion_locatin_context");
  },
});
