// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import DimensionType from "./dimension_type_type";


export default __t.row({
  buildingId: __t.i32().primaryKey().name("building_id"),
  get dimensionType() {
    return DimensionType.name("dimension_type");
  },
  triggerCollapseTime: __t.u32().name("trigger_collapse_time"),
  respawnTime: __t.u32().name("respawn_time"),
  childInteriorInstances: __t.array(__t.i32()).name("child_interior_instances"),
});
