// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("InteriorPortalConnectionsDesc", {
  id: __t.i32(),
  entranceSpawnId: __t.i32(),
  entrancePortalId: __t.i32(),
  exitSpawnId: __t.i32(),
  exitPortalId: __t.i32(),
});


