// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import DimensionType from "./dimension_type_type";


export default __t.object("InteriorNetworkDesc", {
  buildingId: __t.i32(),
  get dimensionType() {
    return DimensionType;
  },
  triggerCollapseTime: __t.u32(),
  respawnTime: __t.u32(),
  childInteriorInstances: __t.array(__t.i32()),
});


