// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("KnowledgeScrollDesc", {
  itemId: __t.i32(),
  scrollType: __t.i32(),
  secondaryKnowledgeId: __t.i32(),
  knownByDefault: __t.bool(),
  autoCollect: __t.bool(),
  title: __t.string(),
  tag: __t.string(),
  content: __t.string(),
});


