// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ProbabilisticItemStack from "./probabilistic_item_stack_type";


export default __t.object("LootTableDesc", {
  id: __t.i32(),
  lootRarity: __t.i32(),
  get lootItemStacks() {
    return __t.array(ProbabilisticItemStack);
  },
});


