// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  reportEntityId: __t.u64().name("report_entity_id"),
  reportedPlayerEntityId: __t.u64().name("reported_player_entity_id"),
  adminName: __t.string().name("admin_name"),
  reportedPlayerUsername: __t.string().name("reported_player_username"),
  actionType: __t.string().name("action_type"),
  moderationNotice: __t.string().name("moderation_notice"),
  details: __t.string(),
  timestamp: __t.i32(),
});
