// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("NpcDesc", {
  npcType: __t.i32(),
  name: __t.string(),
  population: __t.f32(),
  speed: __t.i32(),
  minTimeAtRuin: __t.i32(),
  maxTimeAtRuin: __t.i32(),
  prefabAddress: __t.string(),
  iconAddress: __t.string(),
  forceMarketMode: __t.bool(),
  taskSkillCheck: __t.array(__t.i32()),
});


