// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import NpcType from "./npc_type_type";


export default __t.object("NpcState", {
  entityId: __t.u64(),
  get npcType() {
    return NpcType;
  },
  direction: __t.i32(),
  buildingEntityId: __t.u64(),
  nextActionTimestamp: __t.timestamp(),
  moveDuration: __t.f32(),
  startedMoving: __t.u64(),
  previousBuildings: __t.array(__t.u64()),
  traveling: __t.bool(),
});


