// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("OnDurabilityZeroTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  playerEntityId: __t.u64(),
  brokenItemId: __t.i32(),
  convertInto: __t.i32(),
  stillEquipped: __t.bool(),
  addedToInventory: __t.bool(),
});


