// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import MovementSpeed from "./movement_speed_type";


export default __t.object("ParametersPlayerMoveDesc", {
  version: __t.i32(),
  get defaultSpeed() {
    return __t.array(MovementSpeed);
  },
});


