// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import PathfindingTraversalOption from "./pathfinding_traversal_option_type";


export default __t.row({
  id: __t.i32().primaryKey(),
  canWalkOnLand: __t.bool().name("can_walk_on_land"),
  canSwim: __t.bool().name("can_swim"),
  requiresTransitions: __t.bool().name("requires_transitions"),
  minWaterDepth: __t.i32().name("min_water_depth"),
  maxWaterDepth: __t.i32().name("max_water_depth"),
  maxSwimHeightDelta: __t.i32().name("max_swim_height_delta"),
  avoidLight: __t.bool().name("avoid_light"),
  get climbUpOptions() {
    return __t.array(PathfindingTraversalOption).name("climb_up_options");
  },
  get climbDownOptions() {
    return __t.array(PathfindingTraversalOption).name("climb_down_options");
  },
});
