// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import CsvStatEntry from "./csv_stat_entry_type";
import InputItemStack from "./input_item_stack_type";
import ExperienceStackF32 from "./experience_stack_f_32_type";


export default __t.row({
  id: __t.i32().primaryKey(),
  name: __t.string(),
  get consumedItemStacks() {
    return __t.array(InputItemStack).name("consumed_item_stacks");
  },
  inputCargoId: __t.i32().name("input_cargo_id"),
  inputCargoDiscoveryScore: __t.i32().name("input_cargo_discovery_score"),
  get experiencePerProgress() {
    return __t.array(ExperienceStackF32).name("experience_per_progress");
  },
  discoveryTriggers: __t.array(__t.i32()).name("discovery_triggers"),
  requiredKnowledges: __t.array(__t.i32()).name("required_knowledges"),
  fullDiscoveryScore: __t.i32().name("full_discovery_score"),
  pavingDuration: __t.f32().name("paving_duration"),
  prefabAddress: __t.string().name("prefab_address"),
  tier: __t.i32(),
  get statEffects() {
    return __t.array(CsvStatEntry).name("stat_effects");
  },
  iconAddress: __t.string().name("icon_address"),
  description: __t.string(),
});
