// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("PlayerClaimSetMemberPermissionsRequest", {
  playerEntityId: __t.u64(),
  claimEntityId: __t.u64(),
  inventory: __t.bool(),
  build: __t.bool(),
  officer: __t.bool(),
  coOwner: __t.bool(),
});


