// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import TeleportLocation from "./teleport_location_type";


export default __t.row({
  get teleportLocation() {
    return TeleportLocation.name("teleport_location");
  },
  entityId: __t.u64().primaryKey().name("entity_id"),
  timePlayed: __t.i32().name("time_played"),
  sessionStartTimestamp: __t.i32().name("session_start_timestamp"),
  timeSignedIn: __t.i32().name("time_signed_in"),
  signInTimestamp: __t.i32().name("sign_in_timestamp"),
  signedIn: __t.bool().name("signed_in"),
  travelerTasksExpiration: __t.i32().name("traveler_tasks_expiration"),
});
