// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import OffsetCoordinatesFloat from "./offset_coordinates_float_type";


export default __t.object("PlayerClimbRequest", {
  get destination() {
    return OffsetCoordinatesFloat;
  },
  get origin() {
    return OffsetCoordinatesFloat;
  },
  timestamp: __t.u64(),
  climbType: __t.i32(),
});


