// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import PlayerActionLayer from "./player_action_layer_type";


export default __t.object("PlayerActionDesc", {
  actionTypeId: __t.i32(),
  get layer() {
    return PlayerActionLayer;
  },
  allowedConcurrentActionIds: __t.array(__t.i32()),
});


