// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import PremiumServiceType from "./premium_service_type_type";


export default __t.object("PremiumServiceDesc", {
  id: __t.i32(),
  name: __t.string(),
  description: __t.string(),
  imageAddress: __t.string(),
  get serviceType() {
    return PremiumServiceType;
  },
  price: __t.u32(),
  basePrice: __t.u32(),
  isEnabled: __t.bool(),
});


