// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ItemStack from "./item_stack_type";


export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  constructionRecipeId: __t.i32().name("construction_recipe_id"),
  resourcePlacementRecipeId: __t.i32().name("resource_placement_recipe_id"),
  get items() {
    return __t.array(ItemStack);
  },
  get cargos() {
    return __t.array(ItemStack);
  },
  progress: __t.i32(),
  lastCritOutcome: __t.i32().name("last_crit_outcome"),
  ownerId: __t.u64().name("owner_id"),
  direction: __t.i32(),
  lastHitTimestamp: __t.timestamp().name("last_hit_timestamp"),
});
