// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import QuestRequirement from "./quest_requirement_type";
import QuestReward from "./quest_reward_type";


export default __t.object("QuestChainDesc", {
  id: __t.i32(),
  name: __t.string(),
  isHint: __t.bool(),
  stages: __t.array(__t.i32()),
  get requirements() {
    return __t.array(QuestRequirement);
  },
  get rewards() {
    return __t.array(QuestReward);
  },
  get implicitRewards() {
    return __t.array(QuestReward);
  },
  unstartable: __t.bool(),
  isSecret: __t.bool(),
});


