// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import RegionSignInParameters from "./region_sign_in_parameters_type";


// The tagged union or sum type for the algebraic type `RegionSignInParametersOp`.
const RegionSignInParametersOp = __t.enum("RegionSignInParametersOp", {get Insert() {
    return RegionSignInParameters;
  },
  get Delete() {
    return RegionSignInParameters;
  },
});

export default RegionSignInParametersOp;


