// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  dimensionNetworkId: __t.u64().name("dimension_network_id"),
  claimEntityId: __t.u64().name("claim_entity_id"),
  whiteList: __t.array(__t.u64()).name("white_list"),
  dailyRent: __t.u32().name("daily_rent"),
  paidRent: __t.u32().name("paid_rent"),
  active: __t.bool(),
  defaulted: __t.bool(),
  evictionTimestamp: __t.option(__t.timestamp()).name("eviction_timestamp"),
});
