// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import SmallHexTileMessage from "./small_hex_tile_message_type";


export default __t.object("ResourceSpawnTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  entityId: __t.option(__t.u64()),
  resourceId: __t.i32(),
  get coordinates() {
    return SmallHexTileMessage;
  },
  directionIndex: __t.i32(),
  health: __t.i32(),
  checkBuildings: __t.bool(),
  checkResources: __t.bool(),
});


