// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ResourceClumpInfo from "./resource_clump_info_type";
import ResourceInfo from "./resource_info_type";
import CommonRng from "./common_rng_type";


export default __t.object("ResourcesLog", {
  version: __t.i32(),
  worldWidth: __t.u64(),
  worldHeight: __t.u64(),
  get resourceClumps() {
    return __t.array(ResourceClumpInfo);
  },
  get resources() {
    return __t.array(ResourceInfo);
  },
  get random() {
    return CommonRng;
  },
});


