// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import SmallHexTileMessage from "./small_hex_tile_message_type";


export default __t.object("RespawnResourceInChunkTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  chunkIndex: __t.u64(),
  resourceClumpId: __t.i32(),
  get coord() {
    return SmallHexTileMessage;
  },
});


