// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `ServerTeleportReason`.
const ServerTeleportReason = __t.enum("ServerTeleportReason", {RuinCollapse: __t.unit(),
  InteriorDeconstructed: __t.unit(),
  PlayerDied: __t.unit(),
  TeleportItem: __t.unit(),
  PlayerHousingChangedLocation: __t.unit(),
  PlayerHousingUnderMaintenance: __t.unit(),
  PlayerHousingDeconstructed: __t.unit(),
});

export default ServerTeleportReason;


