// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ResourceClumpInfo from "./resource_clump_info_type";


export default __t.row({
  clumpId: __t.i32().primaryKey().name("clump_id"),
  get resourceClumpInfo() {
    return ResourceClumpInfo.name("resource_clump_info");
  },
});
