// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import LevelRequirement from "./level_requirement_type";
import ToolRequirement from "./tool_requirement_type";
import InputItemStack from "./input_item_stack_type";
import ExperienceStackF32 from "./experience_stack_f_32_type";


export default __t.row({
  id: __t.i32().primaryKey(),
  name: __t.string(),
  timeRequirement: __t.f32().name("time_requirement"),
  staminaRequirement: __t.f32().name("stamina_requirement"),
  consumedBuilding: __t.i32().name("consumed_building"),
  requiredInteriorTier: __t.i32().name("required_interior_tier"),
  get levelRequirements() {
    return __t.array(LevelRequirement).name("level_requirements");
  },
  get toolRequirements() {
    return __t.array(ToolRequirement).name("tool_requirements");
  },
  get consumedItemStacks() {
    return __t.array(InputItemStack).name("consumed_item_stacks");
  },
  get consumedCargoStacks() {
    return __t.array(InputItemStack).name("consumed_cargo_stacks");
  },
  consumedShards: __t.i32().name("consumed_shards"),
  get experiencePerProgress() {
    return __t.array(ExperienceStackF32).name("experience_per_progress");
  },
  discoveryTriggers: __t.array(__t.i32()).name("discovery_triggers"),
  requiredKnowledges: __t.array(__t.i32()).name("required_knowledges"),
  requiredClaimTechIds: __t.array(__t.i32()).name("required_claim_tech_ids"),
  fullDiscoveryScore: __t.i32().name("full_discovery_score"),
  toolMeshIndex: __t.i32().name("tool_mesh_index"),
  buildingDescriptionId: __t.i32().name("building_description_id"),
  requiredPavingTier: __t.i32().name("required_paving_tier"),
  actionsRequired: __t.i32().name("actions_required"),
  instantlyBuilt: __t.bool().name("instantly_built"),
  recipePerformanceId: __t.i32().name("recipe_performance_id"),
});
