// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ToolRequirement from "./tool_requirement_type";


export default __t.row({
  difference: __t.i16().primaryKey(),
  actionsCount: __t.i32().name("actions_count"),
  get toolRequirement() {
    return __t.option(ToolRequirement).name("tool_requirement");
  },
  staminaPerAction: __t.f32().name("stamina_per_action"),
  timePerAction: __t.f32().name("time_per_action"),
  toolMeshIndex: __t.i32().name("tool_mesh_index"),
  recipePerformanceId: __t.i32().name("recipe_performance_id"),
});
