// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  statType: __t.i32().primaryKey().name("stat_type"),
  name: __t.string(),
  value: __t.f32(),
  minValue: __t.f32().name("min_value"),
  maxValue: __t.f32().name("max_value"),
  suffix: __t.string(),
  desc: __t.string(),
});
