// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import PremiumServiceType from "./premium_service_type_type";


export default __t.row({
  id: __t.i32().primaryKey(),
  name: __t.string(),
  description: __t.string(),
  imageAddress: __t.string().name("image_address"),
  get serviceType() {
    return PremiumServiceType.name("service_type");
  },
  price: __t.u32(),
  basePrice: __t.u32().name("base_price"),
  isEnabled: __t.bool().name("is_enabled"),
});
