// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import CsvStatEntry from "./csv_stat_entry_type";
import ExperienceStackF32 from "./experience_stack_f_32_type";
import DeployableType from "./deployable_type_type";
import MovementType from "./movement_type_type";
import MovementSpeed from "./movement_speed_type";


export default __t.row({
  id: __t.i32().primaryKey(),
  name: __t.string(),
  deployFromCollectibleId: __t.i32().name("deploy_from_collectible_id"),
  deployTime: __t.f32().name("deploy_time"),
  get deployableType() {
    return DeployableType.name("deployable_type");
  },
  pathfindingId: __t.i32().name("pathfinding_id"),
  get movementType() {
    return MovementType.name("movement_type");
  },
  canEnterPortals: __t.bool().name("can_enter_portals"),
  canAutoFollow: __t.bool().name("can_auto_follow"),
  affectedByWind: __t.f32().name("affected_by_wind"),
  get speed() {
    return __t.array(MovementSpeed);
  },
  usePlayerSpeedModifier: __t.bool().name("use_player_speed_modifier"),
  placeableOnLand: __t.bool().name("placeable_on_land"),
  placeableInWater: __t.bool().name("placeable_in_water"),
  capacity: __t.i32(),
  storage: __t.i32(),
  stockpile: __t.i32(),
  barter: __t.i32(),
  itemSlotSize: __t.i32().name("item_slot_size"),
  cargoSlotSize: __t.i32().name("cargo_slot_size"),
  modelAddress: __t.string().name("model_address"),
  get stats() {
    return __t.array(CsvStatEntry);
  },
  playerAnimationsInDeployableSlots: __t.array(__t.i32()).name("player_animations_in_deployable_slots"),
  allowDriverExtract: __t.bool().name("allow_driver_extract"),
  allowPassengerExtract: __t.bool().name("allow_passenger_extract"),
  showForSecsAfterOwnerLogout: __t.i32().name("show_for_secs_after_owner_logout"),
  allowEmoteWhileDriver: __t.bool().name("allow_emote_while_driver"),
  allowEmoteWhilePassenger: __t.bool().name("allow_emote_while_passenger"),
  get experiencePerProgress() {
    return __t.array(ExperienceStackF32).name("experience_per_progress");
  },
  mountingRadius: __t.f32().name("mounting_radius"),
  radius: __t.f32(),
  allowHunting: __t.bool().name("allow_hunting"),
});
