// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  enemyTypeId: __t.i32().name("enemy_type_id"),
  requiredPlayersCount: __t.i32().name("required_players_count"),
  scaledArmorBonus: __t.i32().name("scaled_armor_bonus"),
  strengthBonus: __t.i32().name("strength_bonus"),
  accuracyBonus: __t.i32().name("accuracy_bonus"),
  evasionBonus: __t.i32().name("evasion_bonus"),
  minDamageBonus: __t.i32().name("min_damage_bonus"),
  maxDamageBonus: __t.i32().name("max_damage_bonus"),
});
