// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  itemId: __t.i32().primaryKey().name("item_id"),
  scrollType: __t.i32().name("scroll_type"),
  secondaryKnowledgeId: __t.i32().name("secondary_knowledge_id"),
  knownByDefault: __t.bool().name("known_by_default"),
  autoCollect: __t.bool().name("auto_collect"),
  title: __t.string(),
  tag: __t.string(),
  content: __t.string(),
});
