// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import OffsetCoordinatesFloat from "./offset_coordinates_float_type";
import ServerTeleportReason from "./server_teleport_reason_type";


export default __t.row({
  scheduledId: __t.u64().primaryKey().name("scheduled_id"),
  scheduledAt: __t.scheduleAt().name("scheduled_at"),
  get location() {
    return OffsetCoordinatesFloat;
  },
  playerEntityId: __t.u64().name("player_entity_id"),
  get reason() {
    return ServerTeleportReason;
  },
});
