// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import OffsetCoordinatesFloat from "./offset_coordinates_float_type";
import ServerTeleportReason from "./server_teleport_reason_type";


export default __t.object("TeleportPlayerTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  get location() {
    return OffsetCoordinatesFloat;
  },
  playerEntityId: __t.u64(),
  get reason() {
    return ServerTeleportReason;
  },
});


