// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import TradeSessionStatus from "./trade_session_status_type";
import TradePocket from "./trade_pocket_type";


export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  get status() {
    return TradeSessionStatus;
  },
  initiatorEntityId: __t.u64().name("initiator_entity_id"),
  acceptorEntityId: __t.u64().name("acceptor_entity_id"),
  get initiatorOffer() {
    return __t.array(TradePocket).name("initiator_offer");
  },
  get acceptorOffer() {
    return __t.array(TradePocket).name("acceptor_offer");
  },
  updatedAt: __t.timestamp().name("updated_at"),
  resolutionMessage: __t.string().name("resolution_message"),
});
