// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ItemStack from "./item_stack_type";


export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  shopEntityId: __t.u64().name("shop_entity_id"),
  remainingStock: __t.i32().name("remaining_stock"),
  get offerItems() {
    return __t.array(ItemStack).name("offer_items");
  },
  offerCargoId: __t.array(__t.i32()).name("offer_cargo_id"),
  get requiredItems() {
    return __t.array(ItemStack).name("required_items");
  },
  requiredCargoId: __t.array(__t.i32()).name("required_cargo_id"),
  travelerTradeOrderId: __t.option(__t.i32()).name("traveler_trade_order_id"),
});
