// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import TradeSessionStatus from "./trade_session_status_type";
import TradePocket from "./trade_pocket_type";


export default __t.object("TradeSessionState", {
  entityId: __t.u64(),
  get status() {
    return TradeSessionStatus;
  },
  initiatorEntityId: __t.u64(),
  acceptorEntityId: __t.u64(),
  get initiatorOffer() {
    return __t.array(TradePocket);
  },
  get acceptorOffer() {
    return __t.array(TradePocket);
  },
  updatedAt: __t.timestamp(),
  resolutionMessage: __t.string(),
});


