// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import FloatHexTileMessage from "./float_hex_tile_message_type";


export default __t.object("TransferPlayerTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  entityId: __t.u64(),
  get destination() {
    return FloatHexTileMessage;
  },
  newRegionIndex: __t.u8(),
  withVehicle: __t.bool(),
  teleportEnergyCost: __t.f32(),
});


