// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import UserModerationPolicy from "./user_moderation_policy_type";


export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  targetIdentity: __t.identity().name("target_identity"),
  createdByIdentity: __t.identity().name("created_by_identity"),
  get userModerationPolicy() {
    return UserModerationPolicy.name("user_moderation_policy");
  },
  createdTime: __t.timestamp().name("created_time"),
  expirationTime: __t.timestamp().name("expiration_time"),
});
