// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import WorldGenResourceDefinition from "./world_gen_resource_definition_type";


export default __t.object("WorldGenResourcesMapDefinition", {
  seed: __t.i32(),
  get resources() {
    return __t.array(WorldGenResourceDefinition);
  },
});


