// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("WorldRegionState", {
  id: __t.u8(),
  regionMinChunkX: __t.u16(),
  regionMinChunkZ: __t.u16(),
  regionWidthChunks: __t.u16(),
  regionHeightChunks: __t.u16(),
  regionIndex: __t.u8(),
  regionCount: __t.u8(),
  regionCountSqrt: __t.u8(),
});


