// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ResourceState from "./resource_state_type";


export default __t.object("WorldGenGeneratedResourceDeposit", {
  x: __t.i32(),
  z: __t.i32(),
  get deposit() {
    return __t.option(ResourceState);
  },
  dimension: __t.u32(),
});


