// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import WorldGenAnimationCurve from "./world_gen_animation_curve_type";
import WorldGenNoiseSpecs from "./world_gen_noise_specs_type";
import WorldGenNoiseBasedElevationLayer from "./world_gen_noise_based_elevation_layer_type";
import WorldGenRiverGenerationSettings from "./world_gen_river_generation_settings_type";


export default __t.object("WorldGenBiomeDefinition", {
  get distanceToSeaCurve() {
    return WorldGenAnimationCurve;
  },
  get distanceToBiomesCurve() {
    return WorldGenAnimationCurve;
  },
  transitionLength: __t.i32(),
  get noiseSeaMultiplier() {
    return WorldGenAnimationCurve;
  },
  get noiseBasedElevationLayers() {
    return __t.array(WorldGenNoiseBasedElevationLayer);
  },
  maxLakeDepth: __t.i32(),
  terracing: __t.bool(),
  grassDensity: __t.i32(),
  get lakeNoiseSpecs() {
    return WorldGenNoiseSpecs;
  },
  lakeNoiseThreshold: __t.f32(),
  lakeDepthMultiplier: __t.i32(),
  lakeDepthSmoothing: __t.f32(),
  lakeSeaBarriers: __t.bool(),
  get riverGenerationSettings() {
    return __t.option(WorldGenRiverGenerationSettings);
  },
});


