// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import WorldGenVector2Int from "./world_gen_vector_2_int_type";


export default __t.object("WorldGenRiverPathfindingCosts", {
  get elevationDifferenceRange() {
    return WorldGenVector2Int;
  },
  pathfindingCosts: __t.f32(),
});


