// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u8().primaryKey(),
  regionMinChunkX: __t.u16().name("region_min_chunk_x"),
  regionMinChunkZ: __t.u16().name("region_min_chunk_z"),
  regionWidthChunks: __t.u16().name("region_width_chunks"),
  regionHeightChunks: __t.u16().name("region_height_chunks"),
  regionIndex: __t.u8().name("region_index"),
  regionCount: __t.u8().name("region_count"),
  regionCountSqrt: __t.u8().name("region_count_sqrt"),
});
