// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ResourceClumpInfo from "./resource_clump_info_type";
import ResourcePlacement from "./resource_placement_type";


export default __t.object("WorldPlaceResourceRequest", {
  get resources() {
    return __t.array(ResourcePlacement);
  },
  get resourceClumpInfo() {
    return ResourceClumpInfo;
  },
  dryRun: __t.bool(),
  addToResourcesLog: __t.bool(),
  logResults: __t.bool(),
  ignoreBiome: __t.bool(),
});


