// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import WorldGenNoiseSpecs from "./world_gen_noise_specs_type";
import WorldGenVector2 from "./world_gen_vector_2_type";


export default __t.object("WorldGenResourceBiome", {
  biomeDefinitionIndex: __t.i32(),
  chance: __t.f32(),
  get noiseThreshold() {
    return WorldGenVector2;
  },
  get noiseSpecs() {
    return WorldGenNoiseSpecs;
  },
});


