// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import OffsetCoordinatesSmallMessage from "./offset_coordinates_small_message_type";

export default {
  get watchtowerPositions() {
    return __t.array(OffsetCoordinatesSmallMessage);
  },
  watchtowerChunkIndexes: __t.array(__t.array(__t.u64())),
  energy: __t.i32(),
  upkeep: __t.i32(),
  buildingDescId: __t.i32(),
  biomes: __t.array(__t.i32()),
  dryRun: __t.bool(),
  logResults: __t.bool(),
  clearAndLevelGround: __t.bool(),
  ignoreBiomes: __t.bool(),
  ignoreClaims: __t.bool(),
  ignoreDimensionRules: __t.bool(),
};
