// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import WorldGenAnimationCurve from "./world_gen_animation_curve_type";
import WorldGenRiverPathfindingCosts from "./world_gen_river_pathfinding_costs_type";


export default __t.object("WorldGenRiverGenerationSettings", {
  radius: __t.i32(),
  get depthCurve() {
    return WorldGenAnimationCurve;
  },
  erosion: __t.f32(),
  minLakeCircumference: __t.i32(),
  pathfindingNodeLimit: __t.i32(),
  get pathfindingCosts() {
    return __t.array(WorldGenRiverPathfindingCosts);
  },
});


