// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import BuffEffect from "./buff_effect_type";


export default __t.object("AbilityCustomDesc", {
  id: __t.i32(),
  abilityName: __t.string(),
  staminaCost: __t.i32(),
  healthCost: __t.i32(),
  castTime: __t.f32(),
  range: __t.f32(),
  friendly: __t.bool(),
  radius: __t.f32(),
  get buffs() {
    return __t.array(BuffEffect);
  },
  buffToggle: __t.bool(),
  damage: __t.i32(),
  threatValue: __t.f32(),
  cooldown: __t.f32(),
  globalCooldown: __t.f32(),
  linkedAbilityBuffDescId: __t.i32(),
  animation: __t.string(),
  iconPath: __t.string(),
});


