// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `AbilityType`.
const AbilityType = __t.enum("AbilityType", {_Unsupported: __t.u128(),
  Eat: __t.i32(),
  CombatAction: __t.i32(),
  AutoAttack: __t.unit(),
  Custom: __t.i32(),
  Prospecting: __t.i32(),
  Equip: __t.i32(),
  DeployableDeploy: __t.i32(),
  AddToToolbelt: __t.i32(),
  DeployableToggle: __t.i32(),
  Emote: __t.i32(),
});

export default AbilityType;


