// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ActionCooldown from "./action_cooldown_type";


export default __t.object("ActionState", {
  entityId: __t.u64(),
  ownerEntityId: __t.u64(),
  actionId: __t.i32(),
  get cooldown() {
    return ActionCooldown;
  },
});


