// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  moderationEnforcementActive: __t.bool(),
  chatModerationEnforcementActive: __t.bool(),
  usernameModerationEnforcementActive: __t.bool(),
  entityModerationEnforcementActive: __t.bool(),
  moderatedEntityNameTypes: __t.u8(),
  checkForLinks: __t.bool(),
  checkForFlaggedWords: __t.bool(),
  checkForContextFlaggedWords: __t.bool(),
  deleteFlaggedMessages: __t.bool(),
  allowLinksCwl: __t.bool(),
  titleIdCwl: __t.i32(),
  httpRequestMaxRetries: __t.i32(),
};
