// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  reportEntityId: __t.u64(),
  reportedPlayerEntityId: __t.u64(),
  adminName: __t.string(),
  reportedPlayerUsername: __t.string(),
  actionType: __t.string(),
  moderationNotice: __t.string(),
  details: __t.string(),
};
