// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  model: __t.string(),
  modelDoubleCheck: __t.string(),
  modelTranslate: __t.string(),
  offenseCountWindowMinutes: __t.f32(),
  minMinutesBetweenOffenses: __t.f32(),
  reportableMessageMaxAge: __t.i32(),
  countAdminModerationActions: __t.bool(),
  discordWebhookUrlUserReports: __t.string(),
};
