// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import CsvStatEntry from "./csv_stat_entry_type";
import VfxAttachmentPoint from "./vfx_attachment_point_type";


export default __t.row({
  id: __t.i32().primaryKey(),
  buffTypeId: __t.i32().name("buff_type_id"),
  description: __t.string(),
  priority: __t.i32(),
  duration: __t.i32(),
  warnTime: __t.f32().name("warn_time"),
  onlineTimestamp: __t.bool().name("online_timestamp"),
  beneficial: __t.bool(),
  iconAssetName: __t.string().name("icon_asset_name"),
  get stats() {
    return __t.array(CsvStatEntry);
  },
  vfx: __t.string(),
  get vfxAttachmentPoint() {
    return VfxAttachmentPoint.name("vfx_attachment_point");
  },
});
