// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ClaimType from "./claim_type_type";


export default __t.row({
  buildingId: __t.i32().primaryKey().name("building_id"),
  get claimType() {
    return ClaimType.name("claim_type");
  },
  radius: __t.i32(),
  tier: __t.i32(),
});
