// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `BuildingSpawnType`.
const BuildingSpawnType = __t.enum("BuildingSpawnType", {TravelerCamp: __t.unit(),
  Chest: __t.unit(),
  Building: __t.unit(),
  Resource: __t.unit(),
  StationaryNpc: __t.unit(),
  Paving: __t.unit(),
  Enemy: __t.unit(),
});

export default BuildingSpawnType;


