// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  claimEntityId: __t.u64().name("claim_entity_id"),
  directionIndex: __t.i32().name("direction_index"),
  buildingDescriptionId: __t.i32().name("building_description_id"),
  constructedByPlayerEntityId: __t.u64().name("constructed_by_player_entity_id"),
});
