// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  ownerEntityId: __t.u64().name("owner_entity_id"),
  claimEntityId: __t.u64().name("claim_entity_id"),
  itemId: __t.i32().name("item_id"),
  itemType: __t.i32().name("item_type"),
  priceThreshold: __t.i32().name("price_threshold"),
  quantity: __t.i32(),
  timestamp: __t.timestamp(),
  storedCoins: __t.i32().name("stored_coins"),
});
