// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  claimEntityId: __t.u64().name("claim_entity_id"),
  playerEntityId: __t.u64().name("player_entity_id"),
  userName: __t.string().name("user_name"),
  inventoryPermission: __t.bool().name("inventory_permission"),
  buildPermission: __t.bool().name("build_permission"),
  officerPermission: __t.bool().name("officer_permission"),
  coOwnerPermission: __t.bool().name("co_owner_permission"),
});
