// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import OffsetCoordinatesSmallMessage from "./offset_coordinates_small_message_type";


export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  supplies: __t.i32(),
  buildingMaintenance: __t.f32().name("building_maintenance"),
  numTiles: __t.i32().name("num_tiles"),
  numTileNeighbors: __t.u32().name("num_tile_neighbors"),
  get location() {
    return __t.option(OffsetCoordinatesSmallMessage);
  },
  treasury: __t.u32(),
  xpGainedSinceLastCoinMinting: __t.u32().name("xp_gained_since_last_coin_minting"),
  suppliesPurchaseThreshold: __t.u32().name("supplies_purchase_threshold"),
  suppliesPurchasePrice: __t.f32().name("supplies_purchase_price"),
  buildingDescriptionId: __t.i32().name("building_description_id"),
});
