// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import OffsetCoordinatesSmallMessage from "./offset_coordinates_small_message_type";


export default __t.object("CrumbTrailState", {
  entityId: __t.u64(),
  get originalLocation() {
    return OffsetCoordinatesSmallMessage;
  },
  get crumbLocations() {
    return __t.array(OffsetCoordinatesSmallMessage);
  },
  crumbRadiuses: __t.array(__t.i32()),
  get prizeLocation() {
    return OffsetCoordinatesSmallMessage;
  },
  activeStep: __t.i32(),
  prizeEntityIds: __t.array(__t.u64()),
  joinRadius: __t.i32(),
  cleanUpCounter: __t.i32(),
});


