// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("DeployableState", {
  entityId: __t.u64(),
  ownerId: __t.u64(),
  claimEntityId: __t.u64(),
  direction: __t.i32(),
  deployableDescriptionId: __t.i32(),
  nickname: __t.string(),
  hidden: __t.bool(),
});


