// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("DuelState", {
  entityId: __t.u64(),
  initiatorEntityId: __t.u64(),
  acceptorEntityId: __t.u64(),
  victor: __t.option(__t.u64()),
  playerEntityIds: __t.array(__t.u64()),
  outOfRangeTimestamps: __t.array(__t.option(__t.timestamp())),
});


