// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import EmpireRankState from "./empire_rank_state_type";


// The tagged union or sum type for the algebraic type `EmpireRankStateOp`.
const EmpireRankStateOp = __t.enum("EmpireRankStateOp", {get Insert() {
    return EmpireRankState;
  },
  get Delete() {
    return EmpireRankState;
  },
});

export default EmpireRankStateOp;


