// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  empireEntityId: __t.u64().name("empire_entity_id"),
  rank: __t.u8(),
  donatedShards: __t.u32().name("donated_shards"),
  noble: __t.option(__t.timestamp()),
  donatedEmpireCurrency: __t.u32().name("donated_empire_currency"),
});
