// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  buildingEntityId: __t.u64().name("building_entity_id"),
  empireEntityId: __t.u64().name("empire_entity_id"),
  energy: __t.i32(),
  active: __t.bool(),
  startTimestamp: __t.option(__t.timestamp()).name("start_timestamp"),
});
