// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import OffsetCoordinatesSmallMessage from "./offset_coordinates_small_message_type";
import EmpireOwnerType from "./empire_owner_type_type";


export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  capitalBuildingEntityId: __t.u64().name("capital_building_entity_id"),
  name: __t.string(),
  shardTreasury: __t.u32().name("shard_treasury"),
  nobilityThreshold: __t.i32().name("nobility_threshold"),
  numClaims: __t.i32().name("num_claims"),
  get location() {
    return OffsetCoordinatesSmallMessage;
  },
  empireCurrencyTreasury: __t.u32().name("empire_currency_treasury"),
  get ownerType() {
    return EmpireOwnerType.name("owner_type");
  },
});
