// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import OffsetCoordinatesSmallMessage from "./offset_coordinates_small_message_type";


export default __t.object("EmpireSettlementState", {
  buildingEntityId: __t.u64(),
  claimEntityId: __t.u64(),
  empireEntityId: __t.u64(),
  chunkIndex: __t.u64(),
  canHouseEmpireStorehouse: __t.bool(),
  membersDonations: __t.u32(),
  get location() {
    return OffsetCoordinatesSmallMessage;
  },
});


