// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import EnemyType from "./enemy_type_type";
import Biome from "./biome_type";


export default __t.row({
  id: __t.i32().primaryKey(),
  get enemyType() {
    return EnemyType.name("enemy_type");
  },
  get biome() {
    return Biome;
  },
  avgHerdSize: __t.i32().name("avg_herd_size"),
  varHerdSize: __t.f32().name("var_herd_size"),
  herdsPerChunk: __t.f32().name("herds_per_chunk"),
  roamingDistance: __t.i32().name("roaming_distance"),
  spawnEagerness: __t.f32().name("spawn_eagerness"),
  timeOfDayStart: __t.f32().name("time_of_day_start"),
  timeOfDayEnd: __t.f32().name("time_of_day_end"),
  spawnFrequencyMinutes: __t.f32().name("spawn_frequency_minutes"),
});
