// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import FootprintType from "./footprint_type_type";


export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  ownerEntityId: __t.u64().name("owner_entity_id"),
  get footprintType() {
    return FootprintType.name("footprint_type");
  },
});
