// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ItemType from "./item_type_type";


export default __t.object("InputItemStack", {
  itemId: __t.i32(),
  quantity: __t.i32(),
  get itemType() {
    return ItemType;
  },
  discoveryScore: __t.i32(),
  consumptionChance: __t.f32(),
});


