// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("InteriorInstanceDesc", {
  id: __t.i32(),
  interiorShapeId: __t.i32(),
  tier: __t.i32(),
  biome: __t.u8(),
  rentable: __t.bool(),
  generateWallsMesh: __t.bool(),
  generateFloorMesh: __t.bool(),
  defaultLighting: __t.bool(),
  interiorModel: __t.string(),
  wallMaterial: __t.string(),
  floorMaterial: __t.string(),
  minZoom: __t.f32(),
  maxZoom: __t.f32(),
  minAngle: __t.f32(),
  maxAngle: __t.f32(),
  intertiorEnvironmentId: __t.option(__t.i32()),
});


