// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import Pocket from "./pocket_type";


export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  get pockets() {
    return __t.array(Pocket);
  },
  inventoryIndex: __t.i32().name("inventory_index"),
  cargoIndex: __t.i32().name("cargo_index"),
  ownerEntityId: __t.u64().name("owner_entity_id"),
  playerOwnerEntityId: __t.u64().name("player_owner_entity_id"),
});
