// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import LocationState from "./location_state_type";


// The tagged union or sum type for the algebraic type `LocationStateOp`.
const LocationStateOp = __t.enum("LocationStateOp", {get Insert() {
    return LocationState;
  },
  get Delete() {
    return LocationState;
  },
});

export default LocationStateOp;


