// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("LootChestState", {
  entityId: __t.u64(),
  buildingEntityId: __t.u64(),
  lootChestId: __t.i32(),
  directionIndex: __t.i32(),
  buildingSpawnId: __t.i32(),
});


