// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  chunkIndex: __t.u64().name("chunk_index"),
  timestamp: __t.u64(),
  locationX: __t.i32().name("location_x"),
  locationZ: __t.i32().name("location_z"),
  destinationX: __t.i32().name("destination_x"),
  destinationZ: __t.i32().name("destination_z"),
  dimension: __t.u32(),
  isWalking: __t.bool().name("is_walking"),
  pad1: __t.u8().name("_pad1"),
  pad2: __t.u8().name("_pad2"),
  pad3: __t.u8().name("_pad3"),
});
