// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import PassiveCraftStatus from "./passive_craft_status_type";


export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  ownerEntityId: __t.u64().name("owner_entity_id"),
  recipeId: __t.i32().name("recipe_id"),
  buildingEntityId: __t.u64().name("building_entity_id"),
  timestamp: __t.timestamp(),
  get status() {
    return PassiveCraftStatus;
  },
  slot: __t.option(__t.u32()),
});
