// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import PassiveCraftStatus from "./passive_craft_status_type";


export default __t.object("PassiveCraftState", {
  entityId: __t.u64(),
  ownerEntityId: __t.u64(),
  recipeId: __t.i32(),
  buildingEntityId: __t.u64(),
  timestamp: __t.timestamp(),
  get status() {
    return PassiveCraftStatus;
  },
  slot: __t.option(__t.u32()),
});


