// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ChatMessageState from "./chat_message_state_type";


export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  reporterEntityId: __t.u64().name("reporter_entity_id"),
  reportedPlayerEntityId: __t.u64().name("reported_player_entity_id"),
  reportedPlayerUsername: __t.string().name("reported_player_username"),
  reportType: __t.string().name("report_type"),
  reportMessage: __t.string().name("report_message"),
  get reportedChatMessage() {
    return __t.option(ChatMessageState).name("reported_chat_message");
  },
  chatChannelContext: __t.option(__t.array(ChatMessageState)).name("chat_channel_context"),
  chatUserContext: __t.option(__t.array(ChatMessageState)).name("chat_user_context"),
  actioned: __t.bool(),
});
