// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("PremiumPurchaseState", {
  entityId: __t.u64(),
  identity: __t.identity(),
  collectibleDescIds: __t.option(__t.array(__t.i32())),
  price: __t.u32(),
  timestamp: __t.timestamp(),
  processed: __t.bool(),
  quantity: __t.u32(),
});


