// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import MoveValidationParamsDesc from "./move_validation_params_desc_type";


export default __t.object("PrivateParametersDesc", {
  version: __t.i32(),
  get moveValidation() {
    return MoveValidationParamsDesc;
  },
});


