// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("ProspectingState", {
  entityId: __t.u64(),
  prospectingId: __t.i32(),
  crumbTrailEntityId: __t.u64(),
  completedSteps: __t.i32(),
  ongoingStep: __t.i32(),
  totalSteps: __t.i32(),
  nextCrumbAngle: __t.array(__t.f32()),
  lastProspectionTimestamp: __t.timestamp(),
  contribution: __t.i32(),
});


