// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ItemStack from "./item_stack_type";


export default __t.object("ProspectingDesc", {
  id: __t.i32(),
  name: __t.string(),
  description: __t.string(),
  resourceClumpId: __t.i32(),
  placeholderResourceClumpId: __t.i32(),
  enemyAiDescId: __t.i32(),
  isAquaticResource: __t.bool(),
  biomeRequirements: __t.array(__t.i32()),
  equipmentRequirements: __t.array(__t.i32()),
  get requiredItemsToStart() {
    return __t.array(ItemStack);
  },
  get requiredItemsToInteractWithReward() {
    return __t.array(ItemStack);
  },
  get consumedItemsByAbilityTrigger() {
    return __t.array(ItemStack);
  },
  allowAquaticProspecting: __t.bool(),
  breadCrumbCount: __t.array(__t.i32()),
  breadCrumbRadius: __t.array(__t.i32()),
  distanceBetweenBreadCrumbs: __t.array(__t.i32()),
  deadzoneAngleBetweenCrumbs: __t.f32(),
  allowAquaticBreadCrumb: __t.bool(),
  pointerDuration: __t.f32(),
  prospectingDuration: __t.f32(),
  joinRadius: __t.i32(),
  contributionPerVisitedBreadCrumb: __t.i32(),
  breadcrumbFoundMessage: __t.string(),
  resourceUncoveredMessage: __t.string(),
  breadcrumbFoundBySomeoneElseMessage: __t.string(),
  resourceUncoveredBySomeoneElseMessage: __t.string(),
  iconAssetPath: __t.string(),
});


