// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import CompletionCondition from "./completion_condition_type";


export default __t.object("QuestStageDesc", {
  id: __t.i32(),
  chainDescId: __t.i32(),
  name: __t.string(),
  get completionConditions() {
    return __t.array(CompletionCondition);
  },
});


