// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("QuestChainState", {
  entityId: __t.u64(),
  playerEntityId: __t.u64(),
  questChainDescId: __t.i32(),
  stageId: __t.i32(),
  completed: __t.bool(),
  stageRewardsAwarded: __t.array(__t.i32()),
  tracked: __t.bool(),
});


