// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `Rarity`.
const Rarity = __t.enum("Rarity", {Default: __t.unit(),
  Common: __t.unit(),
  Uncommon: __t.unit(),
  Rare: __t.unit(),
  Epic: __t.unit(),
  Legendary: __t.unit(),
  Mythic: __t.unit(),
});

export default Rarity;


