// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import LevelRequirement from "./level_requirement_type";
import ToolRequirement from "./tool_requirement_type";
import InputItemStack from "./input_item_stack_type";
import ExperienceStackF32 from "./experience_stack_f_32_type";
import Biome from "./biome_type";


export default __t.object("ResourcePlacementRecipeDesc", {
  id: __t.i32(),
  name: __t.string(),
  timeRequirement: __t.f32(),
  staminaRequirement: __t.f32(),
  consumedResource: __t.i32(),
  requiredInteriorTier: __t.i32(),
  get levelRequirements() {
    return __t.array(LevelRequirement);
  },
  get toolRequirements() {
    return __t.array(ToolRequirement);
  },
  get consumedItemStacks() {
    return __t.array(InputItemStack);
  },
  get consumedCargoStacks() {
    return __t.array(InputItemStack);
  },
  get experiencePerProgress() {
    return __t.array(ExperienceStackF32);
  },
  discoveryTriggers: __t.array(__t.i32()),
  requiredKnowledges: __t.array(__t.i32()),
  requiredClaimTechIds: __t.array(__t.i32()),
  get requiredBiomes() {
    return __t.array(Biome);
  },
  fullDiscoveryScore: __t.i32(),
  toolMeshIndex: __t.i32(),
  resourceDescriptionId: __t.i32(),
  requiredPavingTier: __t.i32(),
  actionsRequired: __t.i32(),
  recipePerformanceId: __t.i32(),
});


