// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import FootprintTile from "./footprint_tile_type";
import Rarity from "./rarity_type";
import ItemStack from "./item_stack_type";


export default __t.object("ResourceDesc", {
  id: __t.i32(),
  name: __t.string(),
  description: __t.string(),
  flattenable: __t.bool(),
  maxHealth: __t.i32(),
  ignoreDamage: __t.bool(),
  despawnTime: __t.f32(),
  modelAssetName: __t.string(),
  iconAssetName: __t.string(),
  get onDestroyYield() {
    return __t.array(ItemStack);
  },
  onDestroyYieldResourceId: __t.i32(),
  spawnPriority: __t.i32(),
  get footprint() {
    return __t.array(FootprintTile);
  },
  tier: __t.i32(),
  tag: __t.string(),
  get rarity() {
    return Rarity;
  },
  compendiumEntry: __t.bool(),
  enemyParamsId: __t.array(__t.i32()),
  scheduledRespawnTime: __t.f32(),
  notRespawning: __t.bool(),
  showTimeLeft: __t.bool(),
});


