// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import BuffEffect from "./buff_effect_type";


export default __t.row({
  itemId: __t.i32().primaryKey().name("item_id"),
  hp: __t.f32(),
  upToHp: __t.f32().name("up_to_hp"),
  stamina: __t.f32(),
  upToStamina: __t.f32().name("up_to_stamina"),
  hunger: __t.f32(),
  teleportationEnergy: __t.f32().name("teleportation_energy"),
  consumableWhileInCombat: __t.bool().name("consumable_while_in_combat"),
  get buffs() {
    return __t.array(BuffEffect);
  },
});
