// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import BuffEffect from "./buff_effect_type";
import LevelRequirement from "./level_requirement_type";


export default __t.row({
  name: __t.string(),
  id: __t.i32().primaryKey(),
  learnedByPlayer: __t.bool().name("learned_by_player"),
  range: __t.u32(),
  maxRange: __t.f32().name("max_range"),
  autoCast: __t.bool().name("auto_cast"),
  weaponTypeRequirements: __t.array(__t.i32()).name("weapon_type_requirements"),
  leadInTime: __t.f32().name("lead_in_time"),
  inactionTime: __t.f32().name("inaction_time"),
  canMoveDuringLeadIn: __t.bool().name("can_move_during_lead_in"),
  cooldown: __t.f32(),
  globalCooldown: __t.f32().name("global_cooldown"),
  ignoreGlobalCooldown: __t.bool().name("ignore_global_cooldown"),
  strengthMultiplier: __t.f32().name("strength_multiplier"),
  accuracyMultiplier: __t.f32().name("accuracy_multiplier"),
  staminaUse: __t.f32().name("stamina_use"),
  weaponDurabilityLost: __t.i32().name("weapon_durability_lost"),
  get selfBuffs() {
    return __t.array(BuffEffect).name("self_buffs");
  },
  get targetBuffs() {
    return __t.array(BuffEffect).name("target_buffs");
  },
  get levelRequirement() {
    return __t.option(LevelRequirement).name("level_requirement");
  },
  iconAssetName: __t.string().name("icon_asset_name"),
  playerAnimationId: __t.i32().name("player_animation_id"),
  npcAnimationName: __t.string().name("npc_animation_name"),
  hitVfx: __t.string().name("hit_vfx"),
  projectileSpeed: __t.f32().name("projectile_speed"),
  projectileVfx: __t.string().name("projectile_vfx"),
  description: __t.string(),
  selfThreatAgainstBuildings: __t.f32().name("self_threat_against_buildings"),
  selfThreatAgainstEnemies: __t.f32().name("self_threat_against_enemies"),
  baseThreat: __t.f32().name("base_threat"),
  threatPerDamage: __t.f32().name("threat_per_damage"),
  isSelfTargeting: __t.bool().name("is_self_targeting"),
  isTauntAction: __t.bool().name("is_taunt_action"),
});
