// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import BuffEffect from "./buff_effect_type";


export default __t.row({
  id: __t.i32().primaryKey(),
  abilityName: __t.string().name("ability_name"),
  staminaCost: __t.i32().name("stamina_cost"),
  healthCost: __t.i32().name("health_cost"),
  castTime: __t.f32().name("cast_time"),
  range: __t.f32(),
  friendly: __t.bool(),
  radius: __t.f32(),
  get buffs() {
    return __t.array(BuffEffect);
  },
  buffToggle: __t.bool().name("buff_toggle"),
  damage: __t.i32(),
  threatValue: __t.f32().name("threat_value"),
  cooldown: __t.f32(),
  globalCooldown: __t.f32().name("global_cooldown"),
  linkedAbilityBuffDescId: __t.i32().name("linked_ability_buff_desc_id"),
  animation: __t.string(),
  iconPath: __t.string().name("icon_path"),
});
