// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  minElevation: __t.i16().name("min_elevation"),
  maxElevation: __t.i16().name("max_elevation"),
  staminaCost: __t.i32().name("stamina_cost"),
  minClimbProficiency: __t.f32().name("min_climb_proficiency"),
});
