// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import FootprintTile from "./footprint_tile_type";
import Rarity from "./rarity_type";
import ItemStack from "./item_stack_type";


export default __t.row({
  id: __t.i32().primaryKey(),
  name: __t.string(),
  description: __t.string(),
  flattenable: __t.bool(),
  maxHealth: __t.i32().name("max_health"),
  ignoreDamage: __t.bool().name("ignore_damage"),
  despawnTime: __t.f32().name("despawn_time"),
  modelAssetName: __t.string().name("model_asset_name"),
  iconAssetName: __t.string().name("icon_asset_name"),
  get onDestroyYield() {
    return __t.array(ItemStack).name("on_destroy_yield");
  },
  onDestroyYieldResourceId: __t.i32().name("on_destroy_yield_resource_id"),
  spawnPriority: __t.i32().name("spawn_priority"),
  get footprint() {
    return __t.array(FootprintTile);
  },
  tier: __t.i32(),
  tag: __t.string(),
  get rarity() {
    return Rarity;
  },
  compendiumEntry: __t.bool().name("compendium_entry"),
  enemyParamsId: __t.array(__t.i32()).name("enemy_params_id"),
  scheduledRespawnTime: __t.f32().name("scheduled_respawn_time"),
  notRespawning: __t.bool().name("not_respawning"),
  showTimeLeft: __t.bool().name("show_time_left"),
});
