// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import LevelRequirement from "./level_requirement_type";
import CsvStatEntry from "./csv_stat_entry_type";
import EquipmentSlotType from "./equipment_slot_type_type";
import EquipmentVisualType from "./equipment_visual_type_type";
import ClothingVisual from "./clothing_visual_type";
import HandEquipmentVisual from "./hand_equipment_visual_type";


export default __t.row({
  itemId: __t.i32().primaryKey().name("item_id"),
  get slots() {
    return __t.array(EquipmentSlotType);
  },
  get visualType() {
    return EquipmentVisualType.name("visual_type");
  },
  get levelRequirement() {
    return __t.option(LevelRequirement).name("level_requirement");
  },
  get clothingVisual() {
    return __t.option(ClothingVisual).name("clothing_visual");
  },
  get handEquipmentVisual() {
    return __t.option(HandEquipmentVisual).name("hand_equipment_visual");
  },
  get stats() {
    return __t.array(CsvStatEntry);
  },
  requiredAchievements: __t.array(__t.i32()).name("required_achievements"),
  requiredKnowledges: __t.array(__t.i32()).name("required_knowledges"),
  showInProgression: __t.bool().name("show_in_progression"),
});
