// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  imageAddress: __t.string().name("image_address"),
  shardAmount: __t.u32().name("shard_amount"),
  baseShardAmount: __t.u32().name("base_shard_amount"),
  name: __t.string(),
  price: __t.f32(),
  eventName: __t.string().name("event_name"),
});
