// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ClaimTechType from "./claim_tech_type_type";
import ItemStack from "./item_stack_type";


export default __t.row({
  id: __t.i32().primaryKey(),
  name: __t.string(),
  description: __t.string(),
  tier: __t.i32(),
  get techType() {
    return ClaimTechType.name("tech_type");
  },
  suppliesCost: __t.i32().name("supplies_cost"),
  researchTime: __t.i32().name("research_time"),
  requirements: __t.array(__t.i32()),
  get input() {
    return __t.array(ItemStack);
  },
  members: __t.i32(),
  area: __t.i32(),
  supplies: __t.i32(),
  xpToMintHexCoin: __t.u32().name("xp_to_mint_hex_coin"),
  unlocksTechs: __t.array(__t.i32()).name("unlocks_techs"),
});
