// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("TerrainChunkState", {
  chunkIndex: __t.u64(),
  chunkX: __t.i32(),
  chunkZ: __t.i32(),
  dimension: __t.u32(),
  biomes: __t.array(__t.u32()),
  biomeDensity: __t.array(__t.u32()),
  elevations: __t.array(__t.i16()),
  waterLevels: __t.array(__t.i16()),
  waterBodyTypes: __t.byteArray(),
  zoningTypes: __t.byteArray(),
  originalElevations: __t.array(__t.i16()),
});


