// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  chunkIndex: __t.u64().primaryKey().name("chunk_index"),
  chunkX: __t.i32().name("chunk_x"),
  chunkZ: __t.i32().name("chunk_z"),
  dimension: __t.u32(),
  biomes: __t.array(__t.u32()),
  biomeDensity: __t.array(__t.u32()).name("biome_density"),
  elevations: __t.array(__t.i16()),
  waterLevels: __t.array(__t.i16()).name("water_levels"),
  waterBodyTypes: __t.byteArray().name("water_body_types"),
  zoningTypes: __t.byteArray().name("zoning_types"),
  originalElevations: __t.array(__t.i16()).name("original_elevations"),
});
