// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ChatChannel from "./chat_channel_type";
import SurfaceType from "./surface_type_type";
import SkillType from "./skill_type_type";
import BuffCategory from "./buff_category_type";
import ProgressiveActionStatus from "./progressive_action_status_type";
import Permission from "./permission_type";
import PermissionGroup from "./permission_group_type";
import AbilityTypeEnum from "./ability_type_enum_type";


export default __t.row({
  placeholderId: __t.u64().primaryKey().name("placeholder_id"),
  get placeholderSkillType() {
    return SkillType.name("placeholder_skill_type");
  },
  get placeholderBuffCategory() {
    return BuffCategory.name("placeholder_buff_category");
  },
  get placeholder() {
    return ProgressiveActionStatus;
  },
  get placeholderWaterBodyType() {
    return SurfaceType.name("placeholder_water_body_type");
  },
  get chatChannel() {
    return ChatChannel.name("chat_channel");
  },
  get permission() {
    return Permission;
  },
  get permissionGroup() {
    return PermissionGroup.name("permission_group");
  },
  get abilityType() {
    return AbilityTypeEnum.name("ability_type");
  },
});
