// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import UserState from "./user_state_type";


// The tagged union or sum type for the algebraic type `UserStateOp`.
const UserStateOp = __t.enum("UserStateOp", {get Insert() {
    return UserState;
  },
  get Delete() {
    return UserState;
  },
});

export default UserStateOp;


