// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import UserModerationState from "./user_moderation_state_type";


// The tagged union or sum type for the algebraic type `UserModerationStateOp`.
const UserModerationStateOp = __t.enum("UserModerationStateOp", {get Insert() {
    return UserModerationState;
  },
  get Delete() {
    return UserModerationState;
  },
});

export default UserModerationStateOp;


