// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import UserAuthenticationState from "./user_authentication_state_type";


// The tagged union or sum type for the algebraic type `UserAuthenticationStateOp`.
const UserAuthenticationStateOp = __t.enum("UserAuthenticationStateOp", {get Insert() {
    return UserAuthenticationState;
  },
  get Delete() {
    return UserAuthenticationState;
  },
});

export default UserAuthenticationStateOp;


