// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  itemId: __t.i32().primaryKey().name("item_id"),
  tier: __t.i32(),
  weaponType: __t.i32().name("weapon_type"),
  minDamage: __t.i32().name("min_damage"),
  maxDamage: __t.i32().name("max_damage"),
  cooldown: __t.f32(),
  staminaUseMultiplier: __t.f32().name("stamina_use_multiplier"),
});
